# Legacy symbol names are bound by the temporary TissueSim compatibility facade.
# ruff: noqa: F821
"""Graetz lumen-wall closure.

Generated by a behavior-preserving extraction from the frozen TissueSim
baseline. Dependencies are bound by the temporary compatibility facade while
the new typed subsystem APIs replace the legacy global runtime contract.
"""

from __future__ import annotations

from cascade.configuration import _legacy_state as _state
from cascade.runtime import _dependencies

for _dependency_name, _dependency_value in vars(_dependencies).items():
    if not _dependency_name.startswith("__"):
        globals().setdefault(_dependency_name, _dependency_value)
del _dependency_name, _dependency_value

def _graetz_velocity_profile(rho: np.ndarray, profile_name: str) -> np.ndarray:
    profile = str(profile_name or "poiseuille").strip().lower()
    rho_arr = np.asarray(rho, dtype=float)
    if profile == "plug":
        return np.ones_like(rho_arr, dtype=float)
    if profile == "poiseuille":
        return 2.0 * np.maximum(1.0 - rho_arr * rho_arr, 0.0)
    raise ValueError("--graetz-profile must be 'poiseuille' or 'plug'.")


def _graetz_build_matrices(
    Bi: float,
    n_radial: int,
    profile_name: str,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    n = max(int(n_radial), 2)
    rho_nodes = np.linspace(0.0, 1.0, n, dtype=float)
    K = np.zeros((n, n), dtype=float)
    M = np.zeros((n, n), dtype=float)
    cup = np.zeros((n,), dtype=float)
    gp = np.array([-1.0 / math.sqrt(3.0), 1.0 / math.sqrt(3.0)], dtype=float)
    gw = np.array([1.0, 1.0], dtype=float)
    for elem in range(n - 1):
        x0 = float(rho_nodes[elem])
        x1 = float(rho_nodes[elem + 1])
        h = max(x1 - x0, 1e-30)
        ids = (elem, elem + 1)
        for xi, wi in zip(gp, gw):
            rho = 0.5 * (x0 + x1) + 0.5 * h * float(xi)
            jac = 0.5 * h * float(wi)
            N0 = (x1 - rho) / h
            N1 = (rho - x0) / h
            dN = np.array([-1.0 / h, 1.0 / h], dtype=float)
            N = np.array([N0, N1], dtype=float)
            v = float(_graetz_velocity_profile(np.array([rho], dtype=float), profile_name)[0])
            stiff_w = rho * jac
            mass_w = rho * v * jac
            for a in range(2):
                ia = ids[a]
                cup[ia] += 2.0 * mass_w * N[a]
                for b in range(2):
                    ib = ids[b]
                    K[ia, ib] += stiff_w * dN[a] * dN[b]
                    M[ia, ib] += mass_w * N[a] * N[b]
    K[-1, -1] += max(float(Bi), 0.0)
    cup_sum = float(np.sum(cup))
    if cup_sum > 0.0:
        cup /= cup_sum
    return K, M, rho_nodes, cup


def _graetz_get_basis(
    Bi: float,
    n_radial: int,
    n_modes: int,
    profile_name: str,
) -> dict:
    if _state._scipy_linalg is None:
        raise RuntimeError("Graetz closure requires scipy.linalg in the active Python environment.")
    n = max(int(n_radial), 2)
    nm = max(1, min(int(n_modes), n))
    K, M, rho, cup = _graetz_build_matrices(float(Bi), n, profile_name)
    eigvals, eigvecs = _state._scipy_linalg.eigh(K, M, check_finite=False)
    order = np.argsort(eigvals)
    mu2 = np.maximum(np.asarray(eigvals[order[:nm]], dtype=float), 0.0)
    phi = np.asarray(eigvecs[:, order[:nm]], dtype=float)
    for j in range(phi.shape[1]):
        norm = float(math.sqrt(max(phi[:, j].T @ M @ phi[:, j], 1e-30)))
        phi[:, j] /= norm
    return {
        "Bi": float(Bi),
        "rho": rho,
        "K": K,
        "M": M,
        "mu2": mu2,
        "phi": phi,
        "project": phi.T @ M,
        "cup_weights": cup,
    }


def _graetz_get_basis_table(
    n_radial: int,
    n_modes: int,
    profile_name: str,
    *,
    bi_per_decade: int | None = None,
    min_bi: float | None = None,
    max_bi: float | None = None,
) -> dict:
    n = max(int(n_radial), 2)
    nm = max(1, min(int(n_modes), n))
    profile = str(profile_name or "poiseuille").strip().lower()
    per_decade = max(int(bi_per_decade if bi_per_decade is not None else _state.GRAETZ_BI_CACHE_PER_DECADE), 1)
    bi_min = max(float(min_bi if min_bi is not None else _state.GRAETZ_MIN_BI), 1e-30)
    bi_max = max(float(max_bi if max_bi is not None else _state.GRAETZ_MAX_BI), bi_min)
    key_min = int(round(math.log10(bi_min) * per_decade))
    key_max = int(round(math.log10(bi_max) * per_decade))
    cache_key = (profile, n, nm, per_decade, key_min, key_max)
    cached = _state._GRAETZ_BASIS_TABLE_CACHE.get(cache_key)
    if cached is not None:
        return cached
    n_keys = key_max - key_min + 1
    mu2_table = np.zeros((n_keys, nm), dtype=np.float32)
    phi_table = np.zeros((n_keys, n, nm), dtype=np.float32)
    project_table = np.zeros((n_keys, nm, n), dtype=np.float32)
    cup_table = np.zeros((n_keys, n), dtype=np.float32)
    bi_values = np.zeros((n_keys,), dtype=np.float32)
    for idx, key in enumerate(range(key_min, key_max + 1)):
        Bi = 10.0 ** (float(key) / float(per_decade))
        basis = _graetz_get_basis(Bi, n, nm, profile)
        bi_values[idx] = np.float32(Bi)
        mu2_table[idx, :] = np.asarray(basis["mu2"], dtype=np.float32)
        phi_table[idx, :, :] = np.asarray(basis["phi"], dtype=np.float32)
        project_table[idx, :, :] = np.asarray(basis["project"], dtype=np.float32)
        cup_table[idx, :] = np.asarray(basis["cup_weights"], dtype=np.float32)
    table = {
        "profile": profile,
        "n_radial": n,
        "n_modes": nm,
        "per_decade": per_decade,
        "key_min": key_min,
        "key_max": key_max,
        "min_bi": bi_min,
        "max_bi": bi_max,
        "bi_values": bi_values,
        "mu2": mu2_table,
        "phi": phi_table,
        "project": project_table,
        "cup_weights": cup_table,
    }
    _state._GRAETZ_BASIS_TABLE_CACHE[cache_key] = table
    return table


__all__ = ['_graetz_velocity_profile', '_graetz_build_matrices', '_graetz_get_basis', '_graetz_get_basis_table']
