"""Flow-network node indexing and boundary-condition normalization.

Generated by a behavior-preserving extraction from the frozen TissueSim
baseline. Dependencies are bound by the temporary compatibility facade while
the new typed subsystem APIs replace the legacy global runtime contract.
"""

from __future__ import annotations

from cascade.configuration import _legacy_state as _state
from cascade.runtime import _dependencies

for _dependency_name, _dependency_value in vars(_dependencies).items():
    if not _dependency_name.startswith("__"):
        globals().setdefault(_dependency_name, _dependency_value)
del _dependency_name, _dependency_value

def _build_node_indices(geom: np.ndarray, decimals: int = 12) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    prox_points = geom[:, 0:3]
    dist_points = geom[:, 3:6]
    node_lookup: Dict[Tuple[float, float, float], int] = {}
    nodes: List[np.ndarray] = []

    def _get_id(point: np.ndarray) -> int:
        key = tuple(np.round(point, decimals=decimals))
        if key not in node_lookup:
            node_lookup[key] = len(nodes)
            nodes.append(point.copy())
        return node_lookup[key]

    prox_ids = np.array([_get_id(pt) for pt in prox_points], dtype=int)
    dist_ids = np.array([_get_id(pt) for pt in dist_points], dtype=int)
    return prox_ids, dist_ids, np.array(nodes)


def _normalize_kirchhoff_bc_mode(value: str | None = None) -> str:
    mode = str(value or _state.KIRCHHOFF_BC_MODE).strip().lower().replace("-", "_")
    aliases = {
        "mixed": "terminal_pressure",
        "terminal_pressure": "terminal_pressure",
        "pressure": "terminal_pressure",
        "pressure_terminals": "terminal_pressure",
        "terminal_pressure_bc": "terminal_pressure",
        "legacy": "legacy_equal_terminal_flow",
        "legacy_equal_terminal_flow": "legacy_equal_terminal_flow",
        "equal_terminal_flow": "legacy_equal_terminal_flow",
        "equal_terminal_flows": "legacy_equal_terminal_flow",
        "current_outlets": "legacy_equal_terminal_flow",
        "neumann": "legacy_equal_terminal_flow",
        "tree_neumann": "legacy_equal_terminal_flow",
    }
    try:
        return aliases[mode]
    except KeyError as exc:
        raise ValueError(
            "Unknown Kirchhoff BC mode "
            f"{value!r}; expected 'terminal_pressure' or 'legacy_equal_terminal_flow'."
        ) from exc


__all__ = ['_build_node_indices', '_normalize_kirchhoff_bc_mode']
