# Legacy symbol names are bound by the temporary TissueSim compatibility facade.
# ruff: noqa: F821
"""Gauss-Legendre quadrature helpers for exported fields.

Generated by a behavior-preserving extraction from the frozen TissueSim
baseline. Dependencies are bound by the temporary compatibility facade while
the new typed subsystem APIs replace the legacy global runtime contract.
"""

from __future__ import annotations

from cascade.configuration import _legacy_state as _state
from cascade.runtime import _dependencies

for _dependency_name, _dependency_value in vars(_dependencies).items():
    if not _dependency_name.startswith("__"):
        globals().setdefault(_dependency_name, _dependency_value)
del _dependency_name, _dependency_value

def _get_gl_nodes_weights(order: int) -> tuple[np.ndarray, np.ndarray]:
    order = int(order)
    if order <= 0:
        raise ValueError(f"Unsupported GL order: {order}. Use a positive integer.")
    if order == 5:
        return _state._GL5_NODES, _state._GL5_WEIGHTS
    if order == 9:
        return _state._GL9_NODES, _state._GL9_WEIGHTS
    from numpy.polynomial.legendre import leggauss

    nodes, weights = leggauss(order)
    return nodes.astype(float), weights.astype(float)


__all__ = ['_get_gl_nodes_weights']
