# Legacy symbol names are bound by the temporary TissueSim compatibility facade.
# ruff: noqa: F821
"""CSV tables and nondimensional result rows.

Generated by a behavior-preserving extraction from the frozen TissueSim
baseline. Dependencies are bound by the temporary compatibility facade while
the new typed subsystem APIs replace the legacy global runtime contract.
"""

from __future__ import annotations

from cascade.configuration import _legacy_state as _state
from cascade.runtime import _dependencies

for _dependency_name, _dependency_value in vars(_dependencies).items():
    if not _dependency_name.startswith("__"):
        globals().setdefault(_dependency_name, _dependency_value)
del _dependency_name, _dependency_value

def _normalize_angles(values: Sequence[float] | float) -> tuple[float, ...]:
    if isinstance(values, Number):
        return (float(values),)
    if isinstance(values, Sequence):
        return tuple(float(v) for v in values)
    if hasattr(values, "__iter__"):
        return tuple(float(v) for v in values)
    raise TypeError("DLP angle list must be a number or iterable of numbers.")


def _iter_theta_values() -> tuple[float, ...]:
    return _normalize_angles(_state.DLP_ANGLE_VALUES)


def _normalize_lengths(values: Sequence[float] | float) -> tuple[float, ...]:
    return _normalize_angles(values)


def _parse_qin_target_values(value: object) -> tuple[float, ...]:
    """Parse --qin-target as either one number or a comma/list-style sequence."""
    if isinstance(value, Number):
        values = (float(value),)
    elif isinstance(value, Sequence) and not isinstance(value, (str, bytes)):
        parsed: list[float] = []
        for item in value:
            parsed.extend(_parse_qin_target_values(item))
        values = tuple(parsed)
    else:
        text = str(value).strip()
        if not text:
            raise ValueError("--qin-target must contain at least one positive flowrate.")
        if (text[0], text[-1]) in (("(", ")"), ("[", "]")):
            text = text[1:-1].strip()
        parts = [part.strip() for part in text.replace(";", ",").split(",") if part.strip()]
        if not parts:
            raise ValueError("--qin-target must contain at least one positive flowrate.")
        values = tuple(float(part) for part in parts)
    for qin in values:
        if not np.isfinite(qin) or qin <= 0.0:
            raise ValueError(f"--qin-target values must be positive and finite; got {qin!r}.")
    return values


def _parse_distance_sample_count_values(value: object) -> tuple[int, ...]:
    """Parse one or more positive DISTANCE_SAMPLE_COUNT values."""
    if isinstance(value, Number):
        values = (int(value),)
    elif isinstance(value, Sequence) and not isinstance(value, (str, bytes)):
        parsed: list[int] = []
        for item in value:
            parsed.extend(_parse_distance_sample_count_values(item))
        values = tuple(parsed)
    else:
        text = str(value).strip()
        if not text:
            raise ValueError("--distance-sample-counts must contain at least one positive integer.")
        if (text[0], text[-1]) in (("(", ")"), ("[", "]")):
            text = text[1:-1].strip()
        parts = [part.strip() for part in text.replace(";", ",").split(",") if part.strip()]
        if not parts:
            raise ValueError("--distance-sample-counts must contain at least one positive integer.")
        values = tuple(int(float(part)) for part in parts)
    deduped = tuple(dict.fromkeys(values))
    for count in deduped:
        if count <= 0:
            raise ValueError(f"--distance-sample-counts values must be positive; got {count!r}.")
    return deduped


def append_row(path: Path, row: Optional[Dict[str, float]], write_header: bool = False) -> None:
    with path.open("a", newline="") as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=_state.CSV_FIELDNAMES)
        if write_header:
            writer.writeheader()
        if row is not None:
            writer.writerow(row)


def append_nondimensional_row(
    path: Path,
    row: Optional[Dict[str, float | str]],
    write_header: bool = False,
) -> None:
    with path.open("a", newline="") as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=_state.NONDIMENSIONAL_FIELDNAMES)
        if write_header:
            writer.writeheader()
        if row is not None:
            writer.writerow(row)


def _safe_div(num: float, den: float) -> float:
    if not np.isfinite(num) or not np.isfinite(den) or abs(den) <= 1e-30:
        return float("nan")
    return float(num / den)


def _pi_phi_gamma_columns(aggregated: Dict[str, float | str]) -> Dict[str, float]:
    """Return the Pi2/Phi2/Gamma inputs and values appended to the main CSV."""
    fluid = str(aggregated.get("fluid", "")).lower()
    c0_plasma = float(aggregated.get("concentration_inlet", float("nan")))
    avg_radius_cm = float(aggregated.get("avg_radius_mean", float("nan")))
    total_segments = float(aggregated.get("total_segments_mean", float("nan")))
    if not np.isfinite(total_segments) or total_segments <= 0.0:
        target_terminals_raw = float(aggregated.get("target_terminals", float("nan")))
        target_terminals = int(round(target_terminals_raw)) if np.isfinite(target_terminals_raw) else -1
        total_segments = float((2 * target_terminals) + 1) if target_terminals >= 0 else float("nan")
    side_len_cm = float(aggregated.get("cube_side_length", float("nan")))
    q0_ul_min = float(aggregated.get("inlet_flow_ul_per_min_mean", float("nan")))
    if not np.isfinite(q0_ul_min):
        q0_ul_min = float(aggregated.get("qin_target_uL_per_min", float("nan")))

    q0_m3_s = q0_ul_min * 1e-9 / 60.0 if np.isfinite(q0_ul_min) else float("nan")
    side_len_m = side_len_cm * _state.CM_TO_M if np.isfinite(side_len_cm) else float("nan")
    v_t = side_len_m**3 if np.isfinite(side_len_m) else float("nan")
    avg_radius_m = avg_radius_cm * _state.CM_TO_M if np.isfinite(avg_radius_cm) else float("nan")

    c_hb_bound = 0.0
    if fluid == "blood":
        chb_max = float(_state.HD_DISCHARGE * _state.O2_CAP_PER_HCT)
        if np.isfinite(c0_plasma) and _state.ALPHA_MMHG > 0.0:
            p0_mmhg = float(c0_plasma / _state.ALPHA_MMHG)
            c_hb_bound = float(chb_max * severinghaus_saturation(p0_mmhg))
        else:
            c_hb_bound = float("nan")

    c0_eff = c0_plasma + c_hb_bound if np.isfinite(c0_plasma) and np.isfinite(c_hb_bound) else float("nan")
    cstar = (
        float(_state.CONC_MAX_FOR_NORMALIZATION) * 0.01
        if np.isfinite(_state.CONC_MAX_FOR_NORMALIZATION)
        else float("nan")
    )
    solute_diffusivity_cm2_s = float(aggregated.get("solute_diffusivity", _state.SOLUTE_DIFFUSIVITY))
    diffusivity = solute_diffusivity_cm2_s * _state.CM2_TO_M2 if np.isfinite(solute_diffusivity_cm2_s) else float("nan")
    vmax = float(_state.VMAX_MM)
    km = float(_state.K_M_MM)

    l_d = float("nan")
    if np.isfinite(v_t) and np.isfinite(total_segments) and np.isfinite(avg_radius_m) and total_segments > 0.0:
        l_d = float(np.cbrt(v_t / total_segments) - avg_radius_m)

    lambda_rd = float("nan")
    if np.isfinite(diffusivity) and np.isfinite(c0_plasma) and np.isfinite(km) and np.isfinite(vmax):
        if diffusivity >= 0.0 and (c0_plasma + km) > 0.0 and vmax > 0.0:
            lambda_rd = float(np.sqrt(diffusivity * (c0_plasma + km) / vmax))

    pi2 = _safe_div(l_d, lambda_rd)
    phi2 = _safe_div(q0_m3_s * (c0_eff - cstar), v_t * (vmax * cstar / (km + cstar)))
    gamma = _safe_div(c0_eff, km)

    return {
        "C0_plasma": c0_plasma,
        "C_Hb_bound": c_hb_bound,
        "C0_eff": c0_eff,
        "Q0_inlet_m3_s": q0_m3_s,
        "Vmax": vmax,
        "Km": km,
        "Cstar": cstar,
        "D_m2_s": diffusivity,
        "Vt_m3": v_t,
        "l_d_m": l_d,
        "lambda_reaction_diffusion_m": lambda_rd,
        "Pi2": pi2,
        "Phi2": phi2,
        "Gamma": gamma,
    }


def _nondimensional_numbers_row(
    aggregated: Dict[str, float | str],
    *,
    run_name: str,
) -> Dict[str, float | str]:
    fluid = str(aggregated.get("fluid", "")).lower()
    c0_plasma = float(aggregated.get("concentration_inlet", float("nan")))
    avg_radius_cm = float(aggregated.get("avg_radius_mean", float("nan")))
    avg_length_cm = float(aggregated.get("avg_length_mean", float("nan")))
    target_terminals_raw = float(aggregated.get("target_terminals", float("nan")))
    target_terminals = int(round(target_terminals_raw)) if np.isfinite(target_terminals_raw) else -1
    n_segments = float((2 * target_terminals) + 1) if target_terminals >= 0 else float("nan")
    side_len = float(aggregated.get("cube_side_length", float("nan")))
    q0_ul_min = float(aggregated.get("inlet_flow_ul_per_min_mean", float("nan")))

    q0_m3_s = q0_ul_min * 1e-9 / 60.0 if np.isfinite(q0_ul_min) else float("nan")
    side_len_m = side_len * _state.CM_TO_M if np.isfinite(side_len) else float("nan")
    v_t = side_len_m**3 if np.isfinite(side_len_m) else float("nan")
    avg_radius_m = avg_radius_cm * _state.CM_TO_M if np.isfinite(avg_radius_cm) else float("nan")
    avg_length_m = avg_length_cm * _state.CM_TO_M if np.isfinite(avg_length_cm) else float("nan")

    hct_est = float("nan")
    sat_est = float("nan")
    p0_mmhg = float("nan")
    chb_max = 0.0
    c_hb_bound = 0.0
    if fluid == "blood":
        if np.isfinite(avg_radius_cm) and avg_radius_cm > 0.0:
            hct_est = float(tube_hematocrit(avg_radius_cm, hd=_state.HD_DISCHARGE))
        else:
            hct_est = float(_state.HD_DISCHARGE)
        # O2_CAP_PER_HCT is already mol / m^3 per unit hematocrit, so no
        # mL/dL-to-mol/m^3 conversion belongs in the CSV/nondimensional output.
        chb_max = float(_state.HD_DISCHARGE * _state.O2_CAP_PER_HCT)
        if np.isfinite(c0_plasma) and _state.ALPHA_MMHG > 0.0:
            p0_mmhg = float(c0_plasma / _state.ALPHA_MMHG)
            sat_est = float(severinghaus_saturation(p0_mmhg))
            c_hb_bound = float(chb_max * sat_est)
        else:
            c_hb_bound = float("nan")

    c0_eff = c0_plasma + c_hb_bound if np.isfinite(c0_plasma) and np.isfinite(c_hb_bound) else float("nan")
    cstar = (
        float(_state.CONC_MAX_FOR_NORMALIZATION) * 0.01
        if np.isfinite(_state.CONC_MAX_FOR_NORMALIZATION)
        else float("nan")
    )
    diffusivity = float(_state.SOLUTE_DIFFUSIVITY) * _state.CM2_TO_M2
    vmax = float(_state.VMAX_MM)
    km = float(_state.K_M_MM)

    lambda_char = float("nan")
    if np.isfinite(diffusivity) and np.isfinite(vmax) and np.isfinite(km) and np.isfinite(cstar):
        if vmax > 0.0 and (km + cstar) > 0.0 and diffusivity >= 0.0:
            lambda_char = float(np.sqrt(diffusivity * (km + cstar) / vmax))

    l_d = float("nan")
    if np.isfinite(v_t) and np.isfinite(n_segments) and np.isfinite(avg_radius_m) and n_segments > 0.0:
        l_d = float(np.cbrt(v_t / n_segments) - avg_radius_m)

    pi_val = _safe_div(l_d, lambda_char)
    mm_term = _safe_div(cstar, km + cstar)
    phi_val = _safe_div(q0_m3_s * c0_eff, v_t * vmax * mm_term)
    da_val = _safe_div(vmax * (l_d**2), diffusivity * cstar)

    return {
        "run_name": run_name,
        "number_of_trees": float(aggregated.get("number_of_trees", float("nan"))),
        "target_terminals": float(target_terminals),
        "total_segments": n_segments,
        "dlp_angle": float(aggregated.get("dlp_angle", float("nan"))),
        "cube_side_length_m": side_len_m,
        "fluid": fluid,
        "C0_plasma": c0_plasma,
        "C_Hb_bound": c_hb_bound,
        "C0_eff": c0_eff,
        "Q0_inlet_m3_s": q0_m3_s,
        "Vmax": vmax,
        "Km": km,
        "Cstar": cstar,
        "Vt_m3": v_t,
        "l_d_m": l_d,
        "D_m2_s": diffusivity,
        "lambda_m": lambda_char,
        "avg_radius_m": avg_radius_m,
        "avg_length_m": avg_length_m,
        "FracAbove5pct": float(aggregated.get("FracAbove5pct_mean", float("nan"))),
        "FracAbove1pct": float(aggregated.get("FracAbove1pct_mean", float("nan"))),
        "hematocrit_est": hct_est,
        "severinghaus_saturation": sat_est,
        "Pi": pi_val,
        "Phi": phi_val,
        "Da": da_val,
    }


_state._DEFAULT_TREE_PARAMS = None


__all__ = ['_normalize_angles', '_iter_theta_values', '_normalize_lengths', '_parse_qin_target_values', '_parse_distance_sample_count_values', 'append_row', 'append_nondimensional_row', '_safe_div', '_pi_phi_gamma_columns', '_nondimensional_numbers_row']
