"""Tissue cache construction and streaming preparation.

Generated by a behavior-preserving extraction from the frozen TissueSim
baseline. Dependencies are bound by the temporary compatibility facade while
the new typed subsystem APIs replace the legacy global runtime contract.
"""

from __future__ import annotations

from cascade.configuration import _legacy_state as _state
from cascade.runtime import _dependencies

for _dependency_name, _dependency_value in vars(_dependencies).items():
    if not _dependency_name.startswith("__"):
        globals().setdefault(_dependency_name, _dependency_value)
del _dependency_name, _dependency_value

def _segment_decay_factor(
    flow: float,
    radius: float,
    length: float,
    diffusivity: float,
    cin_plasma: float | None = None,
    Chb_max: float | None = None,
) -> float:
    if length <= 0.0 or radius <= 0.0:
        return 1.0
    area = np.pi * radius * radius
    velocity = flow / area if area > 0.0 else 0.0
    if velocity <= 0.0:
        return 1.0

    if cin_plasma is not None and Chb_max is not None:
        B = buffer_factor_B(cin_plasma, Chb_max)
        velocity_eff = velocity * max(B, 1e-6)
    else:
        velocity_eff = velocity

    permeation_rate = _segment_permeation_rate(radius, diffusivity)
    if diffusivity <= 0.0:
        lam = -permeation_rate / velocity_eff
    else:
        discriminant = max(velocity_eff * velocity_eff + 4.0 * diffusivity * permeation_rate, 0.0)
        lam = (velocity_eff - np.sqrt(discriminant)) / (2.0 * diffusivity)
    exponent = np.clip(lam * length, -150.0, 50.0)
    return float(np.exp(exponent))


def normalize_tree_inlet_flow(tree: _state.Tree, target_uL_per_min: Optional[float]) -> Optional[np.ndarray]:
    if target_uL_per_min is None or not np.isfinite(target_uL_per_min):
        return None

    seg_count = int(getattr(tree, "segment_count", 0))
    if seg_count <= 0:
        return None

    flows = np.asarray(tree.data[:seg_count, 22], dtype=float)
    root_flow = float(flows[0]) if flows.size else 0.0
    if not np.isfinite(root_flow) or root_flow == 0.0:
        return None

    target_cms = float(target_uL_per_min) * 1e-3 / 60.0
    scale = target_cms / root_flow
    if not np.isfinite(scale) or scale == 0.0:
        return None

    original = flows.copy()
    flows *= scale
    return original


def build_tissue_cache_from_tree(
    tree: _state.Tree,
    sample_points: np.ndarray,
) -> dict:
    nseg = int(getattr(tree, "segment_count", 0))
    if nseg <= 0:
        return _prepare_tissue_geometry(sample_points, np.empty((0, 3)), np.empty((0, 3)), np.empty((0,)), max_nearby=0)
    # Avoid copying the full (nseg x 31) table; TreeData is already floating-point.
    data = np.asarray(tree.data[:nseg])
    starts = data[:, 0:3]
    ends = data[:, 3:6]
    radii = data[:, 21]
    max_nearby = min(_state.NEAREST_TISSUE_VESSELS, len(starts))
    if _resolve_tissue_accel_mode() == "gpu":
        context = _build_tissue_geometry_context(starts, ends, radii)
        return {
            "gpu": True,
            "context": context,
            "max_nearby": int(max_nearby),
            "n_points": int(sample_points.shape[0]),
        }
    if _state.TISSUE_STREAMING_ENABLED and int(sample_points.shape[0]) >= int(_state.TISSUE_STREAMING_MIN_POINTS):
        context = _build_tissue_geometry_context(starts, ends, radii)
        return {
            "streaming": True,
            "context": context,
            "max_nearby": int(max_nearby),
            "n_points": int(sample_points.shape[0]),
        }
    return _prepare_tissue_geometry(sample_points, starts, ends, radii, max_nearby=max_nearby)


def _compute_tissue_samples_greens_streaming(
    points: np.ndarray,
    starts: np.ndarray,
    ends: np.ndarray,
    radii: np.ndarray,
    cin: np.ndarray,
    flows: np.ndarray,
    *,
    diffusivity: float,
    vmax: float,
    km: float,
    window_factor: float,
    inlet_concentration: float | None,
    tissue_cache: dict | None,
) -> tuple[np.ndarray, np.ndarray]:
    max_nearby = min(_state.NEAREST_TISSUE_VESSELS, len(starts))
    if tissue_cache is not None and tissue_cache.get("streaming"):
        context = tissue_cache["context"]
        max_nearby = int(tissue_cache.get("max_nearby", max_nearby))
    else:
        context = _build_tissue_geometry_context(starts, ends, radii)

    starts_si = context["starts_si"]
    radii_si = context["radii_si"]
    segment_vectors = context["segment_vectors"]
    seg_len_sq = context["seg_len_sq"]
    seg_len = context["seg_len"]
    valid = context["valid_mask"]

    if starts_si.size == 0:
        return np.zeros((0,), dtype=bool), np.zeros((0,), dtype=float)

    cin = cin[valid]
    flows_si = flows[valid] * _state.CM3_TO_M3
    diffusivity_si = diffusivity * _state.CM2_TO_M2

    seg_len = np.sqrt(seg_len_sq)
    cin_pos = np.maximum(np.nan_to_num(cin, nan=0.0), 0.0)
    flows_si = np.nan_to_num(flows_si, nan=0.0)
    radii_si = np.maximum(np.nan_to_num(radii_si, nan=0.0), 0.0)

    denom = np.maximum(km + cin_pos, 1e-30)
    k1 = vmax / denom
    lam_edge = np.sqrt(diffusivity_si / np.maximum(k1, 1e-30))
    phi_edge = radii_si / np.maximum(lam_edge, 1e-30)
    ratio_edge = _k_ratio(phi_edge)
    flow_mag = np.maximum(np.abs(flows_si), 1e-30)
    alpha_edge = (2.0 * np.pi * radii_si / flow_mag) * (diffusivity_si / np.maximum(lam_edge, 1e-30)) * ratio_edge
    if inlet_concentration is None:
        inlet_concentration = get_concentration_inlet()
    lam_ref = float(np.sqrt(diffusivity_si / max(vmax / max(km + float(inlet_concentration), 1e-30), 1e-30)))
    flow_sign = np.sign(flows_si)
    gl_nodes, gl_weights = _get_gl_nodes_weights(_state.GL_ORDER)

    influence_radius = np.asarray(window_factor * lam_edge, dtype=context.get("cache_float", np.float32))
    result = np.zeros(points.shape[0], dtype=float)
    keep_mask_all = np.zeros(points.shape[0], dtype=bool)
    chunk_size = _streaming_tissue_chunk_size(max_nearby)
    n_chunks = int(math.ceil(points.shape[0] / max(chunk_size, 1)))
    print(
        f"  Streaming tissue solve: points={points.shape[0]} max_nearby={max_nearby} "
        f"chunk_points={chunk_size} chunks={n_chunks} prune_by_window={TISSUE_STREAMING_PRUNE_BY_WINDOW} "
        f"chunk_workers={TISSUE_STREAMING_CHUNK_WORKERS}"
    )

    used_numba = bool(_state._HAVE_NUMBA and _state.TISSUE_USE_NUMBA and _state._K0_LUT.size)
    _ensure_tissue_context_kdtree(context)
    state = {
        "context": context,
        "points": points,
        "max_nearby": max_nearby,
        "influence_radius": influence_radius,
        "prune_by_window": bool(_state.TISSUE_STREAMING_PRUNE_BY_WINDOW),
        "used_numba": used_numba,
        "starts_si": starts_si,
        "segment_vectors": segment_vectors,
        "seg_len": seg_len,
        "radii_si": radii_si,
        "cin_pos": cin_pos,
        "alpha_edge": alpha_edge,
        "flow_sign": flow_sign,
        "diffusivity_si": diffusivity_si,
        "km": km,
        "vmax": vmax,
        "window_factor": window_factor,
        "lam_ref": lam_ref,
        "gl_nodes": gl_nodes,
        "gl_weights": gl_weights,
    }
    tasks = [
        (chunk_i, start_idx, min(start_idx + chunk_size, len(points)), state)
        for chunk_i, start_idx in enumerate(range(0, len(points), chunk_size), start=1)
    ]

    old_numba_threads = None
    if used_numba and _state.set_num_threads is not None and _state.get_num_threads is not None:
        try:
            old_numba_threads = int(_state.get_num_threads())
            _state.set_num_threads(max(int(_state.TISSUE_STREAMING_NUMBA_THREADS_PER_WORKER), 1))
            print(
                f"  Streaming tissue: numba_threads_per_chunk="
                f"{max(int(TISSUE_STREAMING_NUMBA_THREADS_PER_WORKER), 1)} "
                f"(was {old_numba_threads})"
            )
        except Exception:
            old_numba_threads = None

    completed = 0
    total_kept = 0
    total_before_candidates = 0
    total_after_candidates = 0
    workers = max(int(_state.TISSUE_STREAMING_CHUNK_WORKERS), 1)
    try:
        if workers > 1 and len(tasks) > 1:
            with ThreadPoolExecutor(max_workers=workers) as executor:
                future_map = {executor.submit(_compute_streaming_tissue_chunk, task): task[0] for task in tasks}
                for fut in as_completed(future_map):
                    chunk_i, start_idx, end_idx, keep_mask, out, kept, before_c, after_c = fut.result()
                    result[start_idx:end_idx] = out
                    keep_mask_all[start_idx:end_idx] = keep_mask
                    completed += 1
                    total_kept += kept
                    total_before_candidates += before_c
                    total_after_candidates += after_c
                    if _state.TISSUE_STREAMING_LOG_EVERY_CHUNKS and (
                        completed == 1 or completed == n_chunks or completed % int(_state.TISSUE_STREAMING_LOG_EVERY_CHUNKS) == 0
                    ):
                        reduction = 100.0 * (1.0 - total_after_candidates / max(total_before_candidates, 1))
                        print(
                            f"    Streaming tissue chunks done {completed}/{n_chunks}: "
                            f"rows_done~{completed * chunk_size} kept={total_kept} "
                            f"candidate_reduction={reduction:.1f}%"
                        )
        else:
            for task in tasks:
                chunk_i, start_idx, end_idx, keep_mask, out, kept, before_c, after_c = _compute_streaming_tissue_chunk(task)
                result[start_idx:end_idx] = out
                keep_mask_all[start_idx:end_idx] = keep_mask
                completed += 1
                total_kept += kept
                total_before_candidates += before_c
                total_after_candidates += after_c
                if _state.TISSUE_STREAMING_LOG_EVERY_CHUNKS and (
                    completed == 1 or completed == n_chunks or completed % int(_state.TISSUE_STREAMING_LOG_EVERY_CHUNKS) == 0
                ):
                    reduction = 100.0 * (1.0 - total_after_candidates / max(total_before_candidates, 1))
                    print(
                        f"    Streaming tissue chunks done {completed}/{n_chunks}: "
                        f"rows_done={end_idx} kept={total_kept} candidate_reduction={reduction:.1f}%"
                    )
    finally:
        if old_numba_threads is not None and _state.set_num_threads is not None:
            try:
                _state.set_num_threads(old_numba_threads)
            except Exception:
                pass

    return keep_mask_all, result


__all__ = ['_segment_decay_factor', 'normalize_tree_inlet_flow', 'build_tissue_cache_from_tree', '_compute_tissue_samples_greens_streaming']
