# Legacy symbol names are bound by the temporary TissueSim compatibility facade.
# ruff: noqa: F821
"""Tissue sampling geometry and spatial caches.

Generated by a behavior-preserving extraction from the frozen TissueSim
baseline. Dependencies are bound by the temporary compatibility facade while
the new typed subsystem APIs replace the legacy global runtime contract.
"""

from __future__ import annotations

from cascade.configuration import _legacy_state as _state
from cascade.runtime import _dependencies

for _dependency_name, _dependency_value in vars(_dependencies).items():
    if not _dependency_name.startswith("__"):
        globals().setdefault(_dependency_name, _dependency_value)
del _dependency_name, _dependency_value

def _diagnostic_stats(name: str, values: np.ndarray) -> str:
    arr = np.asarray(values).reshape(-1)
    arr = arr[np.isfinite(arr)]
    if arr.size == 0:
        return f"{name}=empty"
    q01, q50, q99 = np.quantile(arr, [0.01, 0.5, 0.99])
    return (
        f"{name}[min={float(arr.min()):.3e} p01={float(q01):.3e} "
        f"p50={float(q50):.3e} p99={float(q99):.3e} max={float(arr.max()):.3e}]"
    )


def get_analysis_fluids() -> tuple[str, ...]:
    mode = str(_state.FLUID).lower()
    if mode == "both":
        return ("water", "blood")
    if mode in ("water", "blood"):
        return (mode,)
    raise ValueError('FLUID must be "water", "blood", or "both".')


def get_concentration_inlet(fluid: str | None = None) -> float:
    mode = str(fluid or _state.ACTIVE_FLUID).lower()
    if mode == "both":
        raise ValueError("Active fluid must be 'water' or 'blood'.")
    try:
        return float(_state.CONCENTRATION_INLET_BY_FLUID[mode])
    except KeyError as exc:  # pragma: no cover
        raise ValueError(f"Unknown fluid mode: {mode}") from exc


def _process_tissue_chunk(start_idx: int, end_idx: int, data: dict) -> tuple[int, np.ndarray]:

    points_si = data["points_si"]
    starts_si = data["starts_si"]
    segment_vectors = data["segment_vectors"]
    seg_len = data["seg_len"]
    radii_si = data["radii_si"]
    nearest_idx = data["nearest_idx"]
    proj_raw = data["proj_raw"]
    d_center = data["d_center"]
    keep_mask = data["keep_mask"]
    cin_pos = data["cin_pos"]
    alpha_edge = data["alpha_edge"]
    flow_sign = data["flow_sign"]
    diffusivity_si = data["diffusivity_si"]
    km = data["km"]
    vmax = data["vmax"]
    window_factor = data["window_factor"]
    lam_ref = data["lam_ref"]
    gl_nodes = data["gl_nodes"]
    gl_weights = data["gl_weights"]

    # ramp_params = (.33,3.1,0.,1.57,0.,.443) # min_r, max_r, cs_min, cr_min, cs_max, cr_max
    # min_r_ratio=ramp_params[0],
    # max_r_ratio=ramp_params[1],
    # cs_mult_min=ramp_params[2],
    # cr_mult_min=ramp_params[3],
    # cs_mult_max=ramp_params[4],
    # cr_mult_max=ramp_params[5],

    chunk = points_si[start_idx:end_idx]
    if chunk.size == 0:
        return start_idx, np.zeros((0,), dtype=float)
    idx_local = nearest_idx[start_idx:end_idx]
    proj_local = proj_raw[start_idx:end_idx]
    d_local = d_center[start_idx:end_idx]
    safe_idx_local = np.where(idx_local >= 0, idx_local, 0)
    proj_flow = np.where(flow_sign[safe_idx_local] < 0.0, 1.0 - proj_local, proj_local)
    proj_flow = np.clip(proj_flow, 0.0, 1.0)
    out = np.zeros((len(chunk),), dtype=float)

    for row, point in enumerate(chunk):
        if not keep_mask[start_idx + row]:
            continue
        seg_idx = idx_local[row]
        if seg_idx.size == 0:
            continue
        proj_row = proj_flow[row]
        cap_max = 1e-6
        total = 0.0
        for local_i, seg_i in enumerate(seg_idx):
            if seg_i < 0:
                continue
            L = seg_len[seg_i]
            if L <= 0.0:
                continue
            s_star = float(proj_row[local_i] * L)
            Cc_star = cin_pos[seg_i] * float(np.exp(-alpha_edge[seg_i] * s_star))
            denom_gate = max(km + max(Cc_star, 1e-12), 1e-30)
            lam_gate = float(np.sqrt(diffusivity_si / max(vmax / denom_gate, 1e-30)))
            if d_local[row, local_i] > window_factor * lam_gate:
                continue
            if Cc_star > cap_max:
                cap_max = Cc_star

            halfW = window_factor * lam_ref
            s0 = max(0.0, s_star - halfW)
            s1 = min(L, s_star + halfW)
            if s1 <= s0 + 1e-15:
                continue

            mid = 0.5 * (s0 + s1)
            half = 0.5 * (s1 - s0)
            s = mid + half * gl_nodes
            t = s / L
            xs = starts_si[seg_i] + t[:, None] * segment_vectors[seg_i]
            r_vec = point - xs
            r = np.linalg.norm(r_vec, axis=1)
            valid_r = r > 1e-12
            if not np.any(valid_r):
                continue

            cc_s = cin_pos[seg_i] * np.exp(-alpha_edge[seg_i] * s)
            r_safe = np.where(valid_r, r, 1.0)
            # denom_loc = np.maximum(km + np.maximum(cc_s / 2.0, 1e-12), 1e-30)
            denom_loc = np.maximum(km + np.maximum(cc_s, 1e-12), 1e-30)

            lam_loc = np.sqrt(diffusivity_si / np.maximum(vmax / denom_loc, 1e-30))
            phi_loc = np.maximum(radii_si[seg_i] / np.maximum(lam_loc, 1e-30), 1e-12)
            r_over_lam = r_safe / np.maximum(lam_loc, 1e-30)
            k0_num = _k0_lookup(r_over_lam)
            k0_den = _k0_lookup(phi_loc)
            Ci_R = cc_s * (k0_num / np.maximum(k0_den, 1e-300))
            denom_corr = np.maximum(km + np.minimum(Ci_R, cc_s), 1e-30)



            # ramp_span = max(max_r_ratio - min_r_ratio, 1e-12)
            # t_ramp = np.clip((r_over_lam - min_r_ratio) / ramp_span, 0.0, 1.0)
            # c_low = cs_mult_min * cc_s + np.minimum(cr_mult_min * Ci_R,cc_s)
            # c_high = cs_mult_max * cc_s + np.minimum( cr_mult_max * Ci_R,cc_s)
            # c_eff = (1.0 - t_ramp) * c_low + t_ramp * c_high
            # denom_corr = np.maximum(km + np.maximum(c_eff, 1e-12), 1e-30)


            lam_corr = np.sqrt(diffusivity_si / np.maximum(vmax / denom_corr, 1e-30))
            phi = np.maximum(radii_si[seg_i] / np.maximum(lam_corr, 1e-30), 1e-12)
            ratio = _k_ratio(phi)
            wall_factor = (diffusivity_si / np.maximum(lam_corr, 1e-30)) * ratio
            q_s = (2.0 * np.pi * radii_si[seg_i]) * wall_factor * cc_s
            kernel = np.exp(-r_safe / np.maximum(lam_corr, 1e-30)) / (4.0 * np.pi * r_safe)
            integrand = q_s * (kernel / diffusivity_si)
            integrand[~valid_r] = 0.0

            total += half * float(np.sum(gl_weights * integrand))

        if total < 0.0 or not np.isfinite(total):
            total = 0.0
        if cap_max > -np.inf:
            out[row] = min(total, cap_max)
        else:
            out[row] = total
    return start_idx, out


def _prepare_tissue_geometry(
    points: np.ndarray,
    starts: np.ndarray,
    ends: np.ndarray,
    radii: np.ndarray,
    *,
    max_nearby: int,
) -> dict:
    t_total = perf_counter()
    t0 = perf_counter()
    cache_float = np.float64 if _state.TISSUE_CACHE_FORCE_FLOAT64 else _state.TISSUE_CACHE_FLOAT_DTYPE
    points_si = (points * _state.CM_TO_M).astype(cache_float, copy=False)
    starts_si = (starts * _state.CM_TO_M).astype(cache_float, copy=False)
    ends_si = (ends * _state.CM_TO_M).astype(cache_float, copy=False)
    radii_si = (radii * _state.CM_TO_M).astype(cache_float, copy=False)

    segment_vectors = ends_si - starts_si
    seg_len_sq = np.sum(segment_vectors**2, axis=1)
    min_len_sq = float(_state.TISSUE_MIN_SEGMENT_LENGTH_SI) * float(_state.TISSUE_MIN_SEGMENT_LENGTH_SI)
    valid = np.isfinite(seg_len_sq) & (seg_len_sq > min_len_sq)
    starts_si = starts_si[valid]
    ends_si = ends_si[valid]
    radii_si = radii_si[valid]
    segment_vectors = segment_vectors[valid]
    seg_len_sq = seg_len_sq[valid]
    seg_len = np.sqrt(seg_len_sq)
    t_prepare = perf_counter() - t0
    if starts_si.size == 0:
        return {
            "valid_mask": valid,
            "points_si": points_si,
            "starts_si": starts_si,
            "ends_si": ends_si,
            "radii_si": radii_si,
            "segment_vectors": segment_vectors,
            "seg_len_sq": seg_len_sq,
            "seg_len": seg_len,
            "nearest_idx": np.empty((points.shape[0], 0), dtype=int),
            "proj_raw": np.empty((points.shape[0], 0), dtype=float),
            "d_center": np.empty((points.shape[0], 0), dtype=float),
            "keep_mask": np.zeros((points.shape[0],), dtype=bool),
        }

    nseg = starts_si.shape[0]
    candidate_k = min(nseg, max(max_nearby, max_nearby * _state.TISSUE_KDTREE_CANDIDATE_MULT))
    max_nearby = min(max_nearby, candidate_k, nseg)
    if max_nearby <= 0:
        return {
            "valid_mask": valid,
            "points_si": points_si,
            "starts_si": starts_si,
            "ends_si": ends_si,
            "radii_si": radii_si,
            "segment_vectors": segment_vectors,
            "seg_len_sq": seg_len_sq,
            "seg_len": seg_len,
            "nearest_idx": np.empty((points.shape[0], 0), dtype=int),
            "proj_raw": np.empty((points.shape[0], 0), dtype=float),
            "d_center": np.empty((points.shape[0], 0), dtype=float),
            "keep_mask": np.ones((points.shape[0],), dtype=bool),
        }

    if _state._HAVE_SCIPY_SPATIAL:
        t0 = perf_counter()
        midpoints = 0.5 * (starts_si + ends_si)
        tree = _cKDTree(midpoints)
        t_kdtree = perf_counter() - t0
    else:
        tree = None
        t_kdtree = 0.0

    nearest_idx = np.zeros((points.shape[0], max_nearby), dtype=_state.TISSUE_CACHE_INDEX_DTYPE)
    proj_raw = np.zeros((points.shape[0], max_nearby), dtype=cache_float)
    d_center = np.zeros((points.shape[0], max_nearby), dtype=cache_float)
    keep_mask = np.ones((points.shape[0],), dtype=bool)

    chunk_size = max(int(_state.TISSUE_CACHE_CHUNK_SIZE), 1)
    t_query = 0.0
    t_refine = 0.0
    t_inside = 0.0
    for idx in range(0, len(points_si), chunk_size):
        chunk = points_si[idx: idx + chunk_size]
        if chunk.size == 0:
            continue
        if tree is not None:
            t0 = perf_counter()
            _, cand = _ckdtree_query(tree, chunk, k=candidate_k)
            t_query += perf_counter() - t0
            if cand.ndim == 1:
                cand = cand[:, None]
        else:
            cand = np.tile(np.arange(nseg, dtype=int), (len(chunk), 1))

        t0 = perf_counter()
        starts_c = starts_si[cand]
        seg_c = segment_vectors[cand]
        seg_len_sq_c = seg_len_sq[cand]
        diff = chunk[:, None, :] - starts_c
        proj = np.sum(diff * seg_c, axis=2) / seg_len_sq_c
        proj_clipped = np.clip(proj, 0.0, 1.0)
        closest = starts_c + proj_clipped[:, :, None] * seg_c
        dist = np.linalg.norm(chunk[:, None, :] - closest, axis=2)
        sel = np.argpartition(dist, kth=max_nearby - 1, axis=1)[:, :max_nearby]
        nearest_idx[idx: idx + len(chunk)] = np.take_along_axis(cand, sel, axis=1)
        proj_raw[idx: idx + len(chunk)] = np.take_along_axis(proj, sel, axis=1)
        d_center[idx: idx + len(chunk)] = np.take_along_axis(dist, sel, axis=1)
        t_refine += perf_counter() - t0

        t0 = perf_counter()
        radius_local = np.minimum(
            radii_si[nearest_idx[idx: idx + len(chunk)]],
            np.sqrt(seg_len_sq[nearest_idx[idx: idx + len(chunk)]]),
        )
        proj_sel = proj_raw[idx: idx + len(chunk)]
        inside_any = np.any(
            (proj_sel >= 0.0) & (proj_sel <= 1.0) & (d_center[idx: idx + len(chunk)] <= radius_local),
            axis=1,
        )
        keep_mask[idx: idx + len(chunk)] = ~inside_any
        t_inside += perf_counter() - t0

    if _state.SOLVER_TIMING_DETAILS:
        n_chunks = int(math.ceil(len(points_si) / max(chunk_size, 1)))
        print(
            "  Tissue geometry prep: "
            f"points={len(points_si)} nseg={nseg} candidate_k={candidate_k} keep_k={max_nearby} "
            f"chunk_points={chunk_size} chunks={n_chunks} kdtree_workers={TISSUE_KDTREE_WORKERS} "
            f"prepare={_fmt_seconds(t_prepare)} kdtree={_fmt_seconds(t_kdtree)} "
            f"query={_fmt_seconds(t_query)} refine={_fmt_seconds(t_refine)} "
            f"inside_mask={_fmt_seconds(t_inside)} total={_fmt_seconds(perf_counter() - t_total)}"
        )

    return {
        "valid_mask": valid,
        "points_si": points_si,
        "starts_si": starts_si,
        "ends_si": ends_si,
        "radii_si": radii_si,
        "segment_vectors": segment_vectors,
        "seg_len_sq": seg_len_sq,
        "seg_len": seg_len,
        "nearest_idx": nearest_idx,
        "proj_raw": proj_raw,
        "d_center": d_center,
        "keep_mask": keep_mask,
    }


def _build_tissue_geometry_context(
    starts: np.ndarray,
    ends: np.ndarray,
    radii: np.ndarray,
) -> dict:
    cache_float = np.float64 if _state.TISSUE_CACHE_FORCE_FLOAT64 else _state.TISSUE_CACHE_FLOAT_DTYPE
    starts_si_all = (starts * _state.CM_TO_M).astype(cache_float, copy=False)
    ends_si_all = (ends * _state.CM_TO_M).astype(cache_float, copy=False)
    radii_si_all = (radii * _state.CM_TO_M).astype(cache_float, copy=False)

    segment_vectors_all = ends_si_all - starts_si_all
    seg_len_sq_all = np.sum(segment_vectors_all**2, axis=1)
    min_len_sq = float(_state.TISSUE_MIN_SEGMENT_LENGTH_SI) * float(_state.TISSUE_MIN_SEGMENT_LENGTH_SI)
    valid = np.isfinite(seg_len_sq_all) & (seg_len_sq_all > min_len_sq)
    starts_si = starts_si_all[valid]
    ends_si = ends_si_all[valid]
    radii_si = radii_si_all[valid]
    segment_vectors = segment_vectors_all[valid]
    seg_len_sq = seg_len_sq_all[valid]
    seg_len = np.sqrt(seg_len_sq)

    return {
        "valid_mask": valid,
        "starts_si": starts_si,
        "ends_si": ends_si,
        "radii_si": radii_si,
        "segment_vectors": segment_vectors,
        "seg_len_sq": seg_len_sq,
        "seg_len": seg_len,
        "tree": None,
        "cache_float": cache_float,
    }


def _ensure_tissue_context_kdtree(context: dict):
    tree = context.get("tree")
    if tree is None and _state._HAVE_SCIPY_SPATIAL and int(context["starts_si"].shape[0]) > 0:
        with _state._TISSUE_CONTEXT_KDTREE_LOCK:
            tree = context.get("tree")
            if tree is None:
                t0 = perf_counter()
                midpoints = 0.5 * (context["starts_si"] + context["ends_si"])
                tree = _cKDTree(midpoints)
                context["tree"] = tree
                print(f"  Tissue KDTree build: {_fmt_seconds(perf_counter() - t0)}")
    return tree


def _prepare_tissue_geometry_from_context(
    points: np.ndarray,
    context: dict,
    *,
    max_nearby: int,
) -> dict:
    cache_float = context.get("cache_float", np.float64 if _state.TISSUE_CACHE_FORCE_FLOAT64 else _state.TISSUE_CACHE_FLOAT_DTYPE)
    points_si = (points * _state.CM_TO_M).astype(cache_float, copy=False)
    starts_si = context["starts_si"]
    ends_si = context["ends_si"]
    radii_si = context["radii_si"]
    segment_vectors = context["segment_vectors"]
    seg_len_sq = context["seg_len_sq"]
    seg_len = context["seg_len"]
    valid = context["valid_mask"]
    nseg = int(starts_si.shape[0])

    if nseg == 0:
        return {
            "valid_mask": valid,
            "points_si": points_si,
            "starts_si": starts_si,
            "ends_si": ends_si,
            "radii_si": radii_si,
            "segment_vectors": segment_vectors,
            "seg_len_sq": seg_len_sq,
            "seg_len": seg_len,
            "nearest_idx": np.empty((points.shape[0], 0), dtype=_state.TISSUE_CACHE_INDEX_DTYPE),
            "proj_raw": np.empty((points.shape[0], 0), dtype=cache_float),
            "d_center": np.empty((points.shape[0], 0), dtype=cache_float),
            "keep_mask": np.zeros((points.shape[0],), dtype=bool),
        }

    candidate_k = min(nseg, max(max_nearby, max_nearby * _state.TISSUE_KDTREE_CANDIDATE_MULT))
    max_nearby = min(max_nearby, candidate_k, nseg)
    if max_nearby <= 0:
        return {
            "valid_mask": valid,
            "points_si": points_si,
            "starts_si": starts_si,
            "ends_si": ends_si,
            "radii_si": radii_si,
            "segment_vectors": segment_vectors,
            "seg_len_sq": seg_len_sq,
            "seg_len": seg_len,
            "nearest_idx": np.empty((points.shape[0], 0), dtype=_state.TISSUE_CACHE_INDEX_DTYPE),
            "proj_raw": np.empty((points.shape[0], 0), dtype=cache_float),
            "d_center": np.empty((points.shape[0], 0), dtype=cache_float),
            "keep_mask": np.ones((points.shape[0],), dtype=bool),
        }

    tree = _ensure_tissue_context_kdtree(context)
    nearest_idx = np.zeros((points.shape[0], max_nearby), dtype=_state.TISSUE_CACHE_INDEX_DTYPE)
    proj_raw = np.zeros((points.shape[0], max_nearby), dtype=cache_float)
    d_center = np.zeros((points.shape[0], max_nearby), dtype=cache_float)
    keep_mask = np.ones((points.shape[0],), dtype=bool)

    chunk_size = max(int(_state.TISSUE_CACHE_CHUNK_SIZE), 1)
    for idx in range(0, len(points_si), chunk_size):
        chunk = points_si[idx: idx + chunk_size]
        if chunk.size == 0:
            continue
        if tree is not None:
            _, cand = _ckdtree_query(tree, chunk, k=candidate_k)
            if cand.ndim == 1:
                cand = cand[:, None]
        else:
            cand = np.tile(np.arange(nseg, dtype=int), (len(chunk), 1))

        starts_c = starts_si[cand]
        seg_c = segment_vectors[cand]
        seg_len_sq_c = seg_len_sq[cand]
        diff = chunk[:, None, :] - starts_c
        proj = np.sum(diff * seg_c, axis=2) / seg_len_sq_c
        proj_clipped = np.clip(proj, 0.0, 1.0)
        closest = starts_c + proj_clipped[:, :, None] * seg_c
        dist = np.linalg.norm(chunk[:, None, :] - closest, axis=2)
        sel = np.argpartition(dist, kth=max_nearby - 1, axis=1)[:, :max_nearby]
        nearest_idx[idx: idx + len(chunk)] = np.take_along_axis(cand, sel, axis=1)
        proj_raw[idx: idx + len(chunk)] = np.take_along_axis(proj, sel, axis=1)
        d_center[idx: idx + len(chunk)] = np.take_along_axis(dist, sel, axis=1)

        radius_local = np.minimum(
            radii_si[nearest_idx[idx: idx + len(chunk)]],
            np.sqrt(seg_len_sq[nearest_idx[idx: idx + len(chunk)]]),
        )
        proj_sel = proj_raw[idx: idx + len(chunk)]
        inside_any = np.any(
            (proj_sel >= 0.0) & (proj_sel <= 1.0) & (d_center[idx: idx + len(chunk)] <= radius_local),
            axis=1,
        )
        keep_mask[idx: idx + len(chunk)] = ~inside_any

    return {
        "valid_mask": valid,
        "points_si": points_si,
        "starts_si": starts_si,
        "ends_si": ends_si,
        "radii_si": radii_si,
        "segment_vectors": segment_vectors,
        "seg_len_sq": seg_len_sq,
        "seg_len": seg_len,
        "nearest_idx": nearest_idx,
        "proj_raw": proj_raw,
        "d_center": d_center,
        "keep_mask": keep_mask,
    }


def _compact_tissue_cache_by_influence(tissue_cache: dict, influence_radius: np.ndarray) -> dict:
    nearest_idx = tissue_cache["nearest_idx"]
    if nearest_idx.size == 0:
        return tissue_cache

    safe_idx = np.where(nearest_idx >= 0, nearest_idx, 0)
    valid = (nearest_idx >= 0) & (tissue_cache["d_center"] <= influence_radius[safe_idx])
    counts = np.sum(valid, axis=1)
    max_count = int(np.max(counts)) if counts.size else 0
    if max_count >= nearest_idx.shape[1] and np.all(valid):
        return tissue_cache

    out = dict(tissue_cache)
    idx_compact = np.full((nearest_idx.shape[0], max_count), -1, dtype=nearest_idx.dtype)
    proj_compact = np.zeros((nearest_idx.shape[0], max_count), dtype=tissue_cache["proj_raw"].dtype)
    d_compact = np.zeros((nearest_idx.shape[0], max_count), dtype=tissue_cache["d_center"].dtype)
    for row in range(nearest_idx.shape[0]):
        if counts[row] <= 0:
            continue
        cols = np.flatnonzero(valid[row])
        n = int(cols.size)
        idx_compact[row, :n] = nearest_idx[row, cols]
        proj_compact[row, :n] = tissue_cache["proj_raw"][row, cols]
        d_compact[row, :n] = tissue_cache["d_center"][row, cols]
    out["nearest_idx"] = idx_compact
    out["proj_raw"] = proj_compact
    out["d_center"] = d_compact
    return out


def _streaming_tissue_chunk_size(max_nearby: int) -> int:
    k = max(int(max_nearby), 1)
    target_slots = max(int(_state.TISSUE_STREAMING_TARGET_CANDIDATE_SLOTS), k)
    chunk = max(int(_state.TISSUE_STREAMING_MIN_CHUNK_POINTS), target_slots // k)
    return int(min(max(chunk, 1), int(_state.TISSUE_STREAMING_MAX_CHUNK_POINTS)))


def _compute_streaming_tissue_chunk(task: tuple[int, int, int, dict]) -> tuple[int, int, int, np.ndarray, np.ndarray, int, int, int]:
    chunk_i, start_idx, end_idx, state = task
    context = state["context"]
    points = state["points"]
    max_nearby = int(state["max_nearby"])
    influence_radius = state["influence_radius"]

    chunk_cache = _prepare_tissue_geometry_from_context(
        points[start_idx:end_idx],
        context,
        max_nearby=max_nearby,
    )
    before_candidates = int(np.count_nonzero(chunk_cache["nearest_idx"] >= 0))
    if state["prune_by_window"]:
        chunk_cache = _compact_tissue_cache_by_influence(chunk_cache, influence_radius)
    after_candidates = int(np.count_nonzero(chunk_cache["nearest_idx"] >= 0))

    out = None
    if state["used_numba"]:
        try:
            out = _tissue_kernel_numba(
                chunk_cache["points_si"],
                state["starts_si"],
                state["segment_vectors"],
                state["seg_len"],
                state["radii_si"],
                chunk_cache["nearest_idx"],
                chunk_cache["proj_raw"],
                chunk_cache["d_center"],
                chunk_cache["keep_mask"],
                state["cin_pos"],
                state["alpha_edge"],
                state["flow_sign"],
                float(state["diffusivity_si"]),
                float(state["km"]),
                float(state["vmax"]),
                float(state["window_factor"]),
                float(state["lam_ref"]),
                state["gl_nodes"],
                state["gl_weights"],
                _state._KRATIO_XS,
                _state._K0_LUT,
            )
        except Exception:
            print("WARNING: Numba streaming tissue kernel failed for one chunk; falling back to non-numba chunk.")
            traceback.print_exc()
            out = None

    if out is None:
        worker_data = {
            "points_si": chunk_cache["points_si"],
            "starts_si": state["starts_si"],
            "segment_vectors": state["segment_vectors"],
            "seg_len": state["seg_len"],
            "radii_si": state["radii_si"],
            "nearest_idx": chunk_cache["nearest_idx"],
            "proj_raw": chunk_cache["proj_raw"],
            "d_center": chunk_cache["d_center"],
            "keep_mask": chunk_cache["keep_mask"],
            "cin_pos": state["cin_pos"],
            "alpha_edge": state["alpha_edge"],
            "flow_sign": state["flow_sign"],
            "diffusivity_si": state["diffusivity_si"],
            "km": state["km"],
            "vmax": state["vmax"],
            "window_factor": state["window_factor"],
            "lam_ref": state["lam_ref"],
            "gl_nodes": state["gl_nodes"],
            "gl_weights": state["gl_weights"],
        }
        ranges = [
            (i, min(i + _state.DISTANCE_CHUNK_SIZE, end_idx - start_idx))
            for i in range(0, end_idx - start_idx, _state.DISTANCE_CHUNK_SIZE)
        ]
        out = np.zeros((end_idx - start_idx,), dtype=float)
        for r in ranges:
            local_start, local_out = _process_tissue_chunk(*r, worker_data)
            out[local_start: local_start + len(local_out)] = local_out

    keep_mask = chunk_cache["keep_mask"]
    kept = int(np.count_nonzero(keep_mask))
    return chunk_i, start_idx, end_idx, keep_mask, np.asarray(out, dtype=float), kept, before_candidates, after_candidates


__all__ = ['_diagnostic_stats', 'get_analysis_fluids', 'get_concentration_inlet', '_process_tissue_chunk', '_prepare_tissue_geometry', '_build_tissue_geometry_context', '_ensure_tissue_context_kdtree', '_prepare_tissue_geometry_from_context', '_compact_tissue_cache_by_influence', '_streaming_tissue_chunk_size', '_compute_streaming_tissue_chunk']
