"""CUDA tissue Green's-function evaluation.

Generated by a behavior-preserving extraction from the frozen TissueSim
baseline. Dependencies are bound by the temporary compatibility facade while
the new typed subsystem APIs replace the legacy global runtime contract.
"""

from __future__ import annotations

from cascade.configuration import _legacy_state as _state
from cascade.runtime import _dependencies

for _dependency_name, _dependency_value in vars(_dependencies).items():
    if not _dependency_name.startswith("__"):
        globals().setdefault(_dependency_name, _dependency_value)
del _dependency_name, _dependency_value

_state._TISSUE_GPU_KERNEL = None
_state._CEXT_TISSUE_GPU_KERNEL = None
_state._TISSUE_CONTEXT_KDTREE_LOCK = threading.Lock()


def _get_tissue_gpu_kernel():
    # Mutable runtime state is centralized in configuration._legacy_state.
    if _state._TISSUE_GPU_KERNEL is not None:
        return _state._TISSUE_GPU_KERNEL
    if _state._cp is None:
        raise RuntimeError("CuPy is not available.")
    _state.code = load_cuda_source("tissue_greens_kernel.cu")
    _state._TISSUE_GPU_KERNEL = _state._cp.RawKernel(_state.code, "tissue_greens_kernel")
    return _state._TISSUE_GPU_KERNEL


def _compute_tissue_samples_greens_gpu(
    points: np.ndarray,
    starts: np.ndarray,
    ends: np.ndarray,
    radii: np.ndarray,
    cin: np.ndarray,
    flows: np.ndarray,
    *,
    diffusivity: float,
    vmax: float,
    km: float,
    window_factor: float,
    inlet_concentration: float | None,
    tissue_cache: dict | None,
) -> tuple[np.ndarray, np.ndarray]:
    # Mutable runtime state is centralized in configuration._legacy_state.
    _state._LAST_TISSUE_TIMINGS = {}
    if _resolve_tissue_accel_mode(require_gpu=True) != "gpu" or _state._cp is None:
        raise RuntimeError("Tissue GPU mode could not be initialized.")
    if points.size == 0 or starts.size == 0:
        return np.zeros((0,), dtype=bool), np.zeros((0,), dtype=float)

    t_total = perf_counter()
    max_nearby = min(_state.NEAREST_TISSUE_VESSELS, len(starts))
    if tissue_cache is not None and tissue_cache.get("gpu"):
        context = tissue_cache["context"]
        max_nearby = int(tissue_cache.get("max_nearby", max_nearby))
    else:
        context = _build_tissue_geometry_context(starts, ends, radii)

    starts_si = context["starts_si"]
    radii_si = context["radii_si"]
    segment_vectors = context["segment_vectors"]
    seg_len_sq = context["seg_len_sq"]
    seg_len = context["seg_len"]
    valid = context["valid_mask"]
    nseg = int(starts_si.shape[0])
    if nseg == 0:
        return np.zeros((0,), dtype=bool), np.zeros((0,), dtype=float)

    candidate_k = min(nseg, max(max_nearby, max_nearby * _state.TISSUE_KDTREE_CANDIDATE_MULT))
    keep_k = min(max_nearby, candidate_k, nseg)
    tree = _ensure_tissue_context_kdtree(context)
    if tree is None:
        raise RuntimeError("Tissue GPU mode requires scipy cKDTree for CPU candidate query.")

    t0 = perf_counter()
    cin_valid = np.asarray(cin[valid], dtype=np.float32)
    flows_si = np.asarray(flows[valid] * _state.CM3_TO_M3, dtype=np.float32)
    diffusivity_si = float(diffusivity * _state.CM2_TO_M2)
    cin_pos = np.maximum(np.nan_to_num(cin_valid, nan=0.0), 0.0).astype(np.float32, copy=False)
    flows_si = np.nan_to_num(flows_si, nan=0.0).astype(np.float32, copy=False)
    radii_si_np = np.maximum(np.nan_to_num(np.asarray(radii_si, dtype=np.float32), nan=0.0), 0.0)

    denom = np.maximum(float(km) + cin_pos, 1e-30).astype(np.float32, copy=False)
    k1 = np.asarray(float(vmax) / denom, dtype=np.float32)
    lam_edge = np.sqrt(np.asarray(diffusivity_si / np.maximum(k1, 1e-30), dtype=np.float32))
    phi_edge = radii_si_np / np.maximum(lam_edge, 1e-30)
    ratio_edge = _k_ratio(phi_edge).astype(np.float32, copy=False)
    flow_mag = np.maximum(np.abs(flows_si), 1e-30)
    alpha_edge = ((2.0 * np.pi * radii_si_np / flow_mag) * (diffusivity_si / np.maximum(lam_edge, 1e-30)) * ratio_edge).astype(np.float32, copy=False)
    if inlet_concentration is None:
        inlet_concentration = get_concentration_inlet()
    lam_ref = float(np.sqrt(diffusivity_si / max(vmax / max(km + float(inlet_concentration), 1e-30), 1e-30)))
    flow_sign = np.sign(flows_si).astype(np.float32, copy=False)
    gl_nodes, gl_weights = _get_gl_nodes_weights(_state.GL_ORDER)
    t_setup_cpu = perf_counter() - t0

    t0 = perf_counter()
    starts_g = _state._cp.asarray(np.asarray(starts_si, dtype=np.float32))
    segment_vectors_g = _state._cp.asarray(np.asarray(segment_vectors, dtype=np.float32))
    seg_len_sq_g = _state._cp.asarray(np.asarray(seg_len_sq, dtype=np.float32))
    seg_len_g = _state._cp.asarray(np.asarray(seg_len, dtype=np.float32))
    radii_g = _state._cp.asarray(radii_si_np)
    cin_pos_g = _state._cp.asarray(cin_pos)
    alpha_edge_g = _state._cp.asarray(alpha_edge)
    flow_sign_g = _state._cp.asarray(flow_sign)
    gl_nodes_g = _state._cp.asarray(np.asarray(gl_nodes, dtype=np.float32))
    gl_weights_g = _state._cp.asarray(np.asarray(gl_weights, dtype=np.float32))
    xs_lut_g = _state._cp.asarray(np.asarray(_state._KRATIO_XS, dtype=np.float32))
    k0_lut_g = _state._cp.asarray(np.asarray(_state._K0_LUT, dtype=np.float32))
    ratio_lut_g = _state._cp.asarray(np.asarray(_state._KRATIO_YS, dtype=np.float32))
    _state._cp.cuda.Stream.null.synchronize()
    t_upload_static = perf_counter() - t0

    kernel = _get_tissue_gpu_kernel()
    keep_mask_all = np.zeros(points.shape[0], dtype=bool)
    result = np.zeros(points.shape[0], dtype=np.float32)
    points_si_all = np.asarray(points * _state.CM_TO_M, dtype=np.float32)

    chunk_points = max(int(_state.TISSUE_GPU_CHUNK_POINTS), int(_state.TISSUE_GPU_MIN_CHUNK_POINTS))
    min_chunk = max(int(_state.TISSUE_GPU_MIN_CHUNK_POINTS), 1)
    start_idx = 0
    chunks_done = 0
    t_query = 0.0
    t_transfer = 0.0
    t_refine = 0.0
    t_greens = 0.0
    t_download = 0.0

    while start_idx < points.shape[0]:
        end_idx = min(start_idx + chunk_points, points.shape[0])
        chunk = points_si_all[start_idx:end_idx]
        try:
            t0 = perf_counter()
            _, cand = _ckdtree_query(tree, chunk, k=candidate_k)
            t_query += perf_counter() - t0
            if cand.ndim == 1:
                cand = cand[:, None]

            t0 = perf_counter()
            points_g = _state._cp.asarray(chunk, dtype=_state._cp.float32)
            cand_g = _state._cp.asarray(cand, dtype=_state._cp.int32)
            _state._cp.cuda.Stream.null.synchronize()
            t_transfer += perf_counter() - t0

            t0 = perf_counter()
            starts_c = starts_g[cand_g]
            seg_c = segment_vectors_g[cand_g]
            seg_len_sq_c = seg_len_sq_g[cand_g]
            diff = points_g[:, None, :] - starts_c
            proj = _state._cp.sum(diff * seg_c, axis=2) / seg_len_sq_c
            proj_clip = _state._cp.clip(proj, 0.0, 1.0)
            closest = starts_c + proj_clip[:, :, None] * seg_c
            delta = points_g[:, None, :] - closest
            dist_sq = _state._cp.sum(delta * delta, axis=2)
            sel = _state._cp.argpartition(dist_sq, keep_k - 1, axis=1)[:, :keep_k]
            nearest_g = _state._cp.take_along_axis(cand_g, sel, axis=1).astype(_state._cp.int32, copy=False)
            proj_g = _state._cp.take_along_axis(proj, sel, axis=1).astype(_state._cp.float32, copy=False)
            d_center_g = _state._cp.sqrt(_state._cp.take_along_axis(dist_sq, sel, axis=1)).astype(_state._cp.float32, copy=False)
            radius_local = _state._cp.minimum(radii_g[nearest_g], seg_len_g[nearest_g])
            inside_any = _state._cp.any((proj_g >= 0.0) & (proj_g <= 1.0) & (d_center_g <= radius_local), axis=1)
            keep_g = (~inside_any).astype(_state._cp.uint8, copy=False)
            _state._cp.cuda.Stream.null.synchronize()
            t_refine += perf_counter() - t0

            t0 = perf_counter()
            out_g = _state._cp.zeros((chunk.shape[0],), dtype=_state._cp.float32)
            threads = 128
            blocks = (int(chunk.shape[0]) + threads - 1) // threads
            kernel(
                (blocks,),
                (threads,),
                (
                    points_g.ravel(),
                    starts_g.ravel(),
                    segment_vectors_g.ravel(),
                    seg_len_g,
                    radii_g,
                    nearest_g.ravel(),
                    proj_g.ravel(),
                    d_center_g.ravel(),
                    keep_g,
                    cin_pos_g,
                    alpha_edge_g,
                    flow_sign_g,
                    np.float32(diffusivity_si),
                    np.float32(km),
                    np.float32(vmax),
                    np.float32(window_factor),
                    np.float32(lam_ref),
                    gl_nodes_g,
                    gl_weights_g,
                    np.int32(_state.GL_ORDER),
                    xs_lut_g,
                    k0_lut_g,
                    ratio_lut_g,
                    np.int32(_state._KRATIO_XS.size),
                    np.int32(chunk.shape[0]),
                    np.int32(keep_k),
                    out_g,
                ),
            )
            _state._cp.cuda.Stream.null.synchronize()
            t_greens += perf_counter() - t0

            t0 = perf_counter()
            keep_mask_all[start_idx:end_idx] = _state._cp.asnumpy(keep_g).astype(bool)
            result[start_idx:end_idx] = _state._cp.asnumpy(out_g)
            t_download += perf_counter() - t0
            chunks_done += 1
            start_idx = end_idx
        except _state._cp.cuda.memory.OutOfMemoryError:
            _state._cp.get_default_memory_pool().free_all_blocks()
            if chunk_points <= min_chunk:
                raise
            chunk_points = max(min_chunk, chunk_points // 2)
            print(f"WARNING: GPU OOM in tissue chunk; retrying with --tissue-gpu-chunk-points={chunk_points}")

    if _state.SOLVER_TIMING_DETAILS:
        print(
            "  Tissue GPU solve: "
            f"points={points.shape[0]} active_points={int(np.count_nonzero(keep_mask_all))} "
            f"candidate_k={candidate_k} keep_k={keep_k} chunks={chunks_done} chunk_points={chunk_points} "
            f"setup_cpu={_fmt_seconds(t_setup_cpu)} upload_static={_fmt_seconds(t_upload_static)} "
            f"query={_fmt_seconds(t_query)} transfer={_fmt_seconds(t_transfer)} "
            f"refine={_fmt_seconds(t_refine)} greens={_fmt_seconds(t_greens)} "
            f"download={_fmt_seconds(t_download)} total={_fmt_seconds(perf_counter() - t_total)}"
        )

    total_elapsed = perf_counter() - t_total
    geometry_elapsed = float(t_setup_cpu + t_upload_static + t_query + t_transfer + t_refine + t_download)
    _state._LAST_TISSUE_TIMINGS = {
        "backend": "gpu",
        "t_tissue_geometry_s": geometry_elapsed,
        "t_tissue_oxygen_s": float(t_greens),
        "t_tissue_total_s": float(total_elapsed),
        "t_tissue_kdtree_query_s": float(t_query),
        "t_tissue_gpu_refine_s": float(t_refine),
        "t_tissue_gpu_transfer_s": float(t_transfer + t_download + t_upload_static),
    }

    validate_n = min(int(_state.TISSUE_GPU_VALIDATE_POINTS), int(points.shape[0]))
    if validate_n > 0:
        old_accel = _state.TISSUE_ACCEL_MODE
        old_streaming = _state.TISSUE_STREAMING_ENABLED
        try:
            _state.TISSUE_ACCEL_MODE = "cpu"
            _state.TISSUE_STREAMING_ENABLED = False
            cpu_mask, cpu_vals = compute_tissue_samples_greens(
                points[:validate_n],
                starts,
                ends,
                radii,
                cin,
                flows,
                diffusivity=diffusivity,
                vmax=vmax,
                km=km,
                window_factor=window_factor,
                inlet_concentration=inlet_concentration,
                tissue_cache=None,
            )
        finally:
            _state.TISSUE_ACCEL_MODE = old_accel
            _state.TISSUE_STREAMING_ENABLED = old_streaming
        gpu_mask = keep_mask_all[:validate_n]
        gpu_vals = result[:validate_n].astype(float)
        mask_disagree = int(np.count_nonzero(gpu_mask != cpu_mask))
        finite = np.isfinite(cpu_vals) & np.isfinite(gpu_vals)
        max_abs = float(np.max(np.abs(gpu_vals[finite] - cpu_vals[finite]))) if np.any(finite) else float("nan")
        rel_l2 = _relative_l2(gpu_vals[finite], cpu_vals[finite]) if np.any(finite) else float("nan")
        if _state.CONC_MAX_FOR_NORMALIZATION and np.isfinite(_state.CONC_MAX_FOR_NORMALIZATION):
            cpu_frac = float(np.mean((cpu_vals[cpu_mask] / _state.CONC_MAX_FOR_NORMALIZATION) >= 0.01)) if np.any(cpu_mask) else float("nan")
            gpu_frac = float(np.mean((gpu_vals[gpu_mask] / _state.CONC_MAX_FOR_NORMALIZATION) >= 0.01)) if np.any(gpu_mask) else float("nan")
            frac_delta = gpu_frac - cpu_frac if np.isfinite(cpu_frac) and np.isfinite(gpu_frac) else float("nan")
        else:
            cpu_frac = gpu_frac = frac_delta = float("nan")
        print(
            "  Tissue GPU validation: "
            f"points={validate_n} mask_disagree={mask_disagree} "
            f"max_abs={max_abs:.3e} rel_l2={rel_l2:.3e} "
            f"FracAbove1pct_cpu={cpu_frac:.6g} FracAbove1pct_gpu={gpu_frac:.6g} "
            f"FracAbove1pct_delta={frac_delta:.3e}"
        )

    return keep_mask_all, result.astype(float, copy=False)


def _get_cext_tissue_gpu_kernel():
    # Mutable runtime state is centralized in configuration._legacy_state.
    if _state._CEXT_TISSUE_GPU_KERNEL is not None:
        return _state._CEXT_TISSUE_GPU_KERNEL
    if _state._cp is None:
        raise RuntimeError("CuPy is not available.")
    _state.code = load_cuda_source("cext_tissue_greens_kernel.cu")
    _state._CEXT_TISSUE_GPU_KERNEL = _state._cp.RawKernel(_state.code, "cext_tissue_greens_kernel")
    return _state._CEXT_TISSUE_GPU_KERNEL


def _get_cext_tissue_cell_gpu_kernel():
    # Mutable runtime state is centralized in configuration._legacy_state.
    if _state._CEXT_TISSUE_CELL_GPU_KERNEL is not None:
        return _state._CEXT_TISSUE_CELL_GPU_KERNEL
    if _state._cp is None:
        raise RuntimeError("CuPy is not available.")
    _state.code = load_cuda_source("cext_tissue_cell_greens_kernel.cu")
    _state._CEXT_TISSUE_CELL_GPU_KERNEL = _state._cp.RawKernel(_state.code, "cext_tissue_cell_greens_kernel")
    return _state._CEXT_TISSUE_CELL_GPU_KERNEL


def _build_cext_tissue_cell_list_gpu(
    gl_points_valid: np.ndarray,
    lambda_valid: np.ndarray,
    points_si_all: np.ndarray,
    *,
    window_factor: float,
    radii_si: np.ndarray,
    seg_len_si: np.ndarray | None = None,
) -> tuple[dict, dict[str, float | int]]:
    if _state._cp is None:
        raise RuntimeError("CuPy is not available.")
    t0 = perf_counter()
    gl_flat = np.asarray(gl_points_valid, dtype=np.float32).reshape(-1, 3)
    lambda_flat = np.asarray(lambda_valid, dtype=np.float32).reshape(-1)
    n_nodes = int(gl_flat.shape[0])
    if n_nodes <= 0:
        raise ValueError("Cannot build an empty Cext tissue cell list.")
    finite_lam = lambda_flat[np.isfinite(lambda_flat) & (lambda_flat > 0.0)]
    max_window = float(window_factor) * float(np.max(finite_lam)) if finite_lam.size else 0.0
    max_radius = float(np.nanmax(np.asarray(radii_si, dtype=np.float32))) if np.asarray(radii_si).size else 0.0
    search_radius = max(max_window, max_radius, 1.0e-12)
    mins = np.min(gl_flat, axis=0)
    maxs = np.max(gl_flat, axis=0)
    center = 0.5 * (mins + maxs)
    span = max(float(np.max(maxs - mins)), 1.0e-9)
    side = span + 2.0 * search_radius
    origin = np.asarray(center - 0.5 * side, dtype=np.float32)

    min_grid = max(int(_state.TISSUE_CEXT_CELL_MIN_GRID), 1)
    max_grid = max(min(int(_state.TISSUE_CEXT_CELL_MAX_GRID), 512), min_grid)
    target_occ = max(int(_state.TISSUE_CEXT_CELL_TARGET_OCCUPANCY), 1)
    occ_grid = int(math.ceil((float(n_nodes) / float(target_occ)) ** (1.0 / 3.0)))
    start_grid = max(min_grid, min(max_grid, max(occ_grid // 2, min_grid)))
    stop_grid = max(min(max_grid, max(occ_grid * 2, start_grid)), start_grid)
    max_rad_cells = max(int(_state.TISSUE_CEXT_CELL_MAX_RAD_CELLS), 1)
    empty_cell_weight = 0.05
    best_grid = max(min_grid, min(max_grid, occ_grid))
    best_rad = max(1, int(math.ceil(search_radius / max(float(side) / float(best_grid), 1.0e-30))) + 1)
    best_score = float("inf")
    for grid_candidate in range(start_grid, stop_grid + 1):
        spacing_candidate = float(side) / float(grid_candidate)
        rad_candidate = max(1, int(math.ceil(search_radius / max(spacing_candidate, 1.0e-30))) + 1)
        if rad_candidate > max_rad_cells:
            continue
        avg_occ_candidate = float(n_nodes) / max(float(grid_candidate) ** 3, 1.0)
        cells_visited = float((2 * rad_candidate + 1) ** 3)
        score = cells_visited * (avg_occ_candidate + empty_cell_weight)
        if score < best_score:
            best_score = float(score)
            best_grid = int(grid_candidate)
            best_rad = int(rad_candidate)
    if not np.isfinite(best_score):
        rad_cap_grid = int(math.floor(float(max_rad_cells) * side / max(search_radius, 1.0e-30)))
        best_grid = max(min_grid, min(max_grid, max(rad_cap_grid, min_grid)))
        best_rad = max(1, int(math.ceil(search_radius / max(float(side) / float(best_grid), 1.0e-30))) + 1)
    grid_n = int(best_grid)
    spacing = float(side) / float(grid_n)
    rad_cells = int(best_rad)

    coords = np.floor((gl_flat - origin[None, :]) / np.float32(spacing)).astype(np.int32)
    coords = np.clip(coords, 0, grid_n - 1)
    flat = (
        (coords[:, 0].astype(np.int64) * np.int64(grid_n) + coords[:, 1].astype(np.int64))
        * np.int64(grid_n)
        + coords[:, 2].astype(np.int64)
    )
    order = np.argsort(flat, kind="stable").astype(np.int32, copy=False)
    sorted_flat = np.asarray(flat[order], dtype=np.int64)
    grid_cells = int(grid_n * grid_n * grid_n)
    counts = np.bincount(sorted_flat, minlength=grid_cells)
    cell_ptr = np.zeros((grid_cells + 1,), dtype=np.int32)
    cell_ptr[1:] = np.cumsum(np.asarray(counts, dtype=np.int64), dtype=np.int64).astype(np.int32)
    gl_order = int(lambda_valid.shape[1]) if np.asarray(lambda_valid).ndim >= 2 else 1
    node_seg_ids = np.arange(n_nodes, dtype=np.int64) // max(int(gl_order), 1)
    radii_arr = np.asarray(radii_si, dtype=np.float32).reshape(-1)
    if radii_arr.size:
        node_radius = radii_arr[np.clip(node_seg_ids, 0, radii_arr.size - 1)]
    else:
        node_radius = np.zeros((n_nodes,), dtype=np.float32)
    if seg_len_si is not None and np.asarray(seg_len_si).size:
        seg_len_arr = np.asarray(seg_len_si, dtype=np.float32).reshape(-1)
        node_seg_len = seg_len_arr[np.clip(node_seg_ids, 0, seg_len_arr.size - 1)]
    else:
        node_seg_len = np.zeros((n_nodes,), dtype=np.float32)
    node_source_reach = np.asarray(float(window_factor) * np.maximum(lambda_flat, 0.0), dtype=np.float32)
    node_segment_reach = np.asarray(np.maximum(node_radius, 0.0) + np.maximum(node_seg_len, 0.0), dtype=np.float32)
    cell_source_reach = np.zeros((grid_cells,), dtype=np.float32)
    cell_segment_reach = np.zeros((grid_cells,), dtype=np.float32)
    if n_nodes > 0:
        np.maximum.at(cell_source_reach, flat, node_source_reach)
        np.maximum.at(cell_segment_reach, flat, node_segment_reach)
    build_s = perf_counter() - t0

    t0 = perf_counter()
    cell = {
        "cell_ptr_g": _state._cp.asarray(cell_ptr),
        "cell_node_ids_g": _state._cp.asarray(order),
        "cell_source_reach_g": _state._cp.asarray(cell_source_reach),
        "cell_segment_reach_g": _state._cp.asarray(cell_segment_reach),
        "origin": np.asarray(origin, dtype=np.float32),
        "spacing": float(spacing),
        "grid_n": int(grid_n),
        "rad_cells": int(rad_cells),
        "max_window": float(max_window),
        "search_radius": float(search_radius),
        "n_nodes": int(n_nodes),
    }
    _state._cp.cuda.Stream.null.synchronize()
    upload_s = perf_counter() - t0
    return cell, {
        "build_s": float(build_s),
        "upload_s": float(upload_s),
        "grid_n": int(grid_n),
        "rad_cells": int(rad_cells),
        "avg_occupancy": float(n_nodes) / max(float(grid_cells), 1.0),
        "estimated_cells_per_point": float((2 * int(rad_cells) + 1) ** 3),
        "estimated_nodes_per_point": float((2 * int(rad_cells) + 1) ** 3) * (float(n_nodes) / max(float(grid_cells), 1.0)),
        "mean_cell_source_reach": float(np.mean(cell_source_reach[counts > 0])) if np.any(counts > 0) else 0.0,
        "max_cell_source_reach": float(np.max(cell_source_reach)) if cell_source_reach.size else 0.0,
        "mean_cell_segment_reach": float(np.mean(cell_segment_reach[counts > 0])) if np.any(counts > 0) else 0.0,
        "max_cell_segment_reach": float(np.max(cell_segment_reach)) if cell_segment_reach.size else 0.0,
        "max_window": float(max_window),
        "search_radius": float(search_radius),
    }


def _compute_tissue_samples_greens_from_cext_state_gpu(
    points: np.ndarray,
    starts: np.ndarray,
    ends: np.ndarray,
    radii: np.ndarray,
    cext_state: dict,
    *,
    tissue_cache: dict | None = None,
) -> tuple[np.ndarray, np.ndarray]:
    # Mutable runtime state is centralized in configuration._legacy_state.
    _state._LAST_TISSUE_TIMINGS = {}
    if _state._cp is None or _resolve_tissue_accel_mode(require_gpu=True) != "gpu":
        raise RuntimeError("Cext tissue GPU mode could not be initialized.")
    if points.size == 0 or starts.size == 0:
        return np.zeros((0,), dtype=bool), np.zeros((0,), dtype=float)

    t_total = perf_counter()
    t0 = perf_counter()
    max_nearby = min(_state.NEAREST_TISSUE_VESSELS, len(starts))
    if tissue_cache is not None and tissue_cache.get("gpu"):
        context = tissue_cache["context"]
        max_nearby = int(tissue_cache.get("max_nearby", max_nearby))
    elif tissue_cache is not None and tissue_cache.get("streaming") and isinstance(tissue_cache.get("context"), dict):
        context = tissue_cache["context"]
        max_nearby = int(tissue_cache.get("max_nearby", max_nearby))
    else:
        context = _build_tissue_geometry_context(starts, ends, radii)

    starts_si = context["starts_si"]
    radii_si = context["radii_si"]
    segment_vectors = context["segment_vectors"]
    seg_len_sq = context["seg_len_sq"]
    seg_len = context["seg_len"]
    valid = np.asarray(context["valid_mask"], dtype=bool)
    nseg = int(starts_si.shape[0])
    if nseg == 0:
        return np.zeros((0,), dtype=bool), np.zeros((0,), dtype=float)

    candidate_k = min(nseg, max(max_nearby, max_nearby * _state.TISSUE_KDTREE_CANDIDATE_MULT))
    keep_k = min(max_nearby, candidate_k, nseg)
    # If the KDTree candidate request is already dense, querying/sorting most
    # segments on CPU is slower than doing the exact all-segment refinement on
    # GPU and avoids transferring the large candidate-index matrix.
    use_all_segment_refine = candidate_k >= nseg or (candidate_k / max(float(nseg), 1.0)) >= 0.5
    tree = None
    valid_source_ids = np.flatnonzero(valid).astype(np.int64, copy=False)
    gl_points_all = np.asarray(cext_state["gl_points_si"], dtype=np.float32)
    lambda_all = np.asarray(cext_state["lambda_iv_gl"], dtype=np.float32)
    q_weighted_all = np.asarray(cext_state["q_weighted_gl"], dtype=np.float32)
    mono2_weight_all = np.asarray(cext_state.get("mono2_weight_gl", np.zeros_like(q_weighted_all)), dtype=np.float32)
    dipole2_weight_all = np.asarray(cext_state.get("dipole2_weight_gl", np.zeros_like(q_weighted_all)), dtype=np.float32)
    seg_cap_all = np.asarray(cext_state["seg_cap_gl"], dtype=np.float32)
    gl_points_valid = np.asarray(gl_points_all[valid_source_ids], dtype=np.float32)
    lambda_valid = np.asarray(lambda_all[valid_source_ids], dtype=np.float32)
    q_weighted_valid = np.asarray(q_weighted_all[valid_source_ids], dtype=np.float32)
    mono2_weight_valid = np.asarray(mono2_weight_all[valid_source_ids], dtype=np.float32)
    dipole2_weight_valid = np.asarray(dipole2_weight_all[valid_source_ids], dtype=np.float32)
    seg_cap_valid = np.asarray(seg_cap_all[valid_source_ids], dtype=np.float32)
    gl_order = int(gl_points_valid.shape[1]) if gl_points_valid.ndim >= 3 else 0
    if gl_order <= 0:
        return np.ones((points.shape[0],), dtype=bool), np.zeros((points.shape[0],), dtype=float)

    diffusivity_si = float(cext_state["diffusivity_si"])
    window_factor = float(cext_state.get("window_factor", _state.CEXT_WINDOW_FACTOR))
    t_setup_cpu = perf_counter() - t0

    t0 = perf_counter()
    starts_g = _state._cp.asarray(np.asarray(starts_si, dtype=np.float32))
    segment_vectors_g = _state._cp.asarray(np.asarray(segment_vectors, dtype=np.float32))
    seg_len_sq_g = _state._cp.asarray(np.asarray(seg_len_sq, dtype=np.float32))
    seg_len_g = _state._cp.asarray(np.asarray(seg_len, dtype=np.float32))
    radii_g = _state._cp.asarray(np.asarray(radii_si, dtype=np.float32))
    gl_points_g = _state._cp.asarray(gl_points_valid)
    lambda_g = _state._cp.asarray(lambda_valid)
    q_weighted_g = _state._cp.asarray(q_weighted_valid)
    mono2_weight_g = _state._cp.asarray(mono2_weight_valid)
    dipole2_weight_g = _state._cp.asarray(dipole2_weight_valid)
    seg_cap_g = _state._cp.asarray(seg_cap_valid)
    _state._cp.cuda.Stream.null.synchronize()
    t_upload_static = perf_counter() - t0

    keep_mask_all = np.zeros(points.shape[0], dtype=bool)
    result = np.zeros(points.shape[0], dtype=np.float32)
    points_si_all = np.asarray(points * _state.CM_TO_M, dtype=np.float32)

    chunk_points = max(int(_state.TISSUE_GPU_CHUNK_POINTS), int(_state.TISSUE_GPU_MIN_CHUNK_POINTS))
    min_chunk = max(int(_state.TISSUE_GPU_MIN_CHUNK_POINTS), 1)
    start_idx = 0
    chunks_done = 0
    t_query = 0.0
    t_transfer = 0.0
    t_refine = 0.0
    t_greens = 0.0
    t_download = 0.0

    validate_n = min(int(_state.TISSUE_GPU_VALIDATE_POINTS), int(points.shape[0]))
    if bool(_state.TISSUE_CEXT_CELL_LIST_ENABLE) and validate_n <= 0:
        try:
            cell, cell_metrics = _build_cext_tissue_cell_list_gpu(
                gl_points_valid,
                lambda_valid,
                points_si_all,
                window_factor=window_factor,
                radii_si=np.asarray(radii_si, dtype=np.float32),
                seg_len_si=np.asarray(seg_len, dtype=np.float32),
            )
            kernel_cell = _get_cext_tissue_cell_gpu_kernel()
            start_idx = 0
            chunks_done = 0
            while start_idx < points.shape[0]:
                end_idx = min(start_idx + chunk_points, points.shape[0])
                chunk = points_si_all[start_idx:end_idx]
                try:
                    t0 = perf_counter()
                    points_g = _state._cp.asarray(chunk, dtype=_state._cp.float32)
                    keep_g = _state._cp.empty((chunk.shape[0],), dtype=_state._cp.uint8)
                    out_g = _state._cp.zeros((chunk.shape[0],), dtype=_state._cp.float32)
                    _state._cp.cuda.Stream.null.synchronize()
                    t_transfer += perf_counter() - t0

                    t0 = perf_counter()
                    threads = 128
                    blocks = (int(chunk.shape[0]) + threads - 1) // threads
                    origin = np.asarray(cell["origin"], dtype=np.float32)
                    kernel_cell(
                        (blocks,),
                        (threads,),
                        (
                            points_g.ravel(),
                            cell["cell_ptr_g"],
                            cell["cell_node_ids_g"],
                            cell["cell_source_reach_g"],
                            cell["cell_segment_reach_g"],
                            starts_g.ravel(),
                            segment_vectors_g.ravel(),
                            seg_len_sq_g,
                            seg_len_g,
                            radii_g,
                            gl_points_g.ravel(),
                            lambda_g.ravel(),
                            q_weighted_g.ravel(),
                            mono2_weight_g.ravel(),
                            dipole2_weight_g.ravel(),
                            seg_cap_g,
                            np.float32(diffusivity_si),
                            np.float32(window_factor),
                            np.float32(float(origin[0])),
                            np.float32(float(origin[1])),
                            np.float32(float(origin[2])),
                            np.float32(float(cell["spacing"])),
                            np.int32(int(cell["grid_n"])),
                            np.int32(int(cell["rad_cells"])),
                            np.int32(chunk.shape[0]),
                            np.int32(gl_order),
                            keep_g,
                            out_g,
                        ),
                    )
                    _state._cp.cuda.Stream.null.synchronize()
                    t_greens += perf_counter() - t0

                    t0 = perf_counter()
                    keep_mask_all[start_idx:end_idx] = _state._cp.asnumpy(keep_g).astype(bool)
                    result[start_idx:end_idx] = _state._cp.asnumpy(out_g)
                    t_download += perf_counter() - t0
                    chunks_done += 1
                    start_idx = end_idx
                except _state._cp.cuda.memory.OutOfMemoryError:
                    _state._cp.get_default_memory_pool().free_all_blocks()
                    if chunk_points <= min_chunk:
                        raise
                    chunk_points = max(min_chunk, chunk_points // 2)
                    print(f"WARNING: GPU OOM in Cext tissue cell-list chunk; retrying with --tissue-gpu-chunk-points={chunk_points}")

            if _state.SOLVER_TIMING_DETAILS:
                print(
                    "  Tissue GPU Cext solve: "
                    f"points={points.shape[0]} active_points={int(np.count_nonzero(keep_mask_all))} "
                    f"candidate_mode=cell_list cell_grid={int(cell_metrics['grid_n'])} "
                    f"rad_cells={int(cell_metrics['rad_cells'])} avg_cell_occ={float(cell_metrics['avg_occupancy']):.3f} "
                    f"est_nodes_per_point={float(cell_metrics['estimated_nodes_per_point']):.1f} "
                    f"chunks={chunks_done} chunk_points={chunk_points} "
                    f"setup_cpu={_fmt_seconds(t_setup_cpu)} upload_static={_fmt_seconds(t_upload_static)} "
                    f"cell_build={_fmt_seconds(cell_metrics['build_s'])} cell_upload={_fmt_seconds(cell_metrics['upload_s'])} "
                    f"query={_fmt_seconds(0.0)} transfer={_fmt_seconds(t_transfer)} "
                    f"refine={_fmt_seconds(0.0)} greens={_fmt_seconds(t_greens)} "
                    f"download={_fmt_seconds(t_download)} total={_fmt_seconds(perf_counter() - t_total)}"
                )

            total_elapsed = perf_counter() - t_total
            geometry_elapsed = float(
                t_setup_cpu
                + t_upload_static
                + float(cell_metrics["build_s"])
                + float(cell_metrics["upload_s"])
                + t_transfer
                + t_download
            )
            _state._LAST_TISSUE_TIMINGS = {
                "backend": "cext_gpu_cell_list",
                "source_mode": "cext_converged_q_flux",
                "cache_mode": "gpu_cell_list",
                "t_tissue_geometry_s": geometry_elapsed,
                "t_tissue_oxygen_s": float(t_greens),
                "t_tissue_total_s": float(total_elapsed),
                "t_tissue_kdtree_query_s": 0.0,
                "t_tissue_gpu_refine_s": 0.0,
                "t_tissue_gpu_transfer_s": float(t_transfer + t_download + t_upload_static + float(cell_metrics["upload_s"])),
            }
            return keep_mask_all, result.astype(float, copy=False)
        except Exception:
            print("WARNING: Cext tissue cell-list GPU path failed; falling back to KDTree/refine path.")
            traceback.print_exc()
            _state._cp.get_default_memory_pool().free_all_blocks()
            keep_mask_all[:] = False
            result[:] = np.float32(0.0)
            chunks_done = 0
            t_query = 0.0
            t_transfer = 0.0
            t_refine = 0.0
            t_greens = 0.0
            t_download = 0.0

    kernel = _get_cext_tissue_gpu_kernel()
    if not use_all_segment_refine:
        tree = _ensure_tissue_context_kdtree(context)
        if tree is None:
            raise RuntimeError("Cext tissue GPU mode requires scipy cKDTree for CPU candidate query.")

    while start_idx < points.shape[0]:
        end_idx = min(start_idx + chunk_points, points.shape[0])
        chunk = points_si_all[start_idx:end_idx]
        try:
            cand = None
            if not use_all_segment_refine:
                t0 = perf_counter()
                _, cand = _ckdtree_query(tree, chunk, k=candidate_k)
                t_query += perf_counter() - t0
                if cand.ndim == 1:
                    cand = cand[:, None]

            t0 = perf_counter()
            points_g = _state._cp.asarray(chunk, dtype=_state._cp.float32)
            if use_all_segment_refine:
                cand_g = None
            else:
                cand_g = _state._cp.asarray(cand, dtype=_state._cp.int32)
            _state._cp.cuda.Stream.null.synchronize()
            t_transfer += perf_counter() - t0

            t0 = perf_counter()
            if use_all_segment_refine:
                starts_c = starts_g[None, :, :]
                seg_c = segment_vectors_g[None, :, :]
                seg_len_sq_c = seg_len_sq_g[None, :]
            else:
                starts_c = starts_g[cand_g]
                seg_c = segment_vectors_g[cand_g]
                seg_len_sq_c = seg_len_sq_g[cand_g]
            diff = points_g[:, None, :] - starts_c
            proj = _state._cp.sum(diff * seg_c, axis=2) / seg_len_sq_c
            proj_clip = _state._cp.clip(proj, 0.0, 1.0)
            closest = starts_c + proj_clip[:, :, None] * seg_c
            delta = points_g[:, None, :] - closest
            dist_sq = _state._cp.sum(delta * delta, axis=2)
            sel = _state._cp.argpartition(dist_sq, keep_k - 1, axis=1)[:, :keep_k]
            if use_all_segment_refine:
                nearest_g = sel.astype(_state._cp.int32, copy=False)
            else:
                nearest_g = _state._cp.take_along_axis(cand_g, sel, axis=1).astype(_state._cp.int32, copy=False)
            proj_g = _state._cp.take_along_axis(proj, sel, axis=1).astype(_state._cp.float32, copy=False)
            d_center_g = _state._cp.sqrt(_state._cp.take_along_axis(dist_sq, sel, axis=1)).astype(_state._cp.float32, copy=False)
            radius_local = _state._cp.minimum(radii_g[nearest_g], seg_len_g[nearest_g])
            inside_any = _state._cp.any((proj_g >= 0.0) & (proj_g <= 1.0) & (d_center_g <= radius_local), axis=1)
            keep_g = (~inside_any).astype(_state._cp.uint8, copy=False)
            _state._cp.cuda.Stream.null.synchronize()
            t_refine += perf_counter() - t0

            t0 = perf_counter()
            out_g = _state._cp.zeros((chunk.shape[0],), dtype=_state._cp.float32)
            threads = 128
            blocks = (int(chunk.shape[0]) + threads - 1) // threads
            kernel(
                (blocks,),
                (threads,),
                (
                    points_g.ravel(),
                    nearest_g.ravel(),
                    keep_g,
                    gl_points_g.ravel(),
                    segment_vectors_g.ravel(),
                    lambda_g.ravel(),
                    q_weighted_g.ravel(),
                    mono2_weight_g.ravel(),
                    dipole2_weight_g.ravel(),
                    seg_cap_g,
                    np.float32(diffusivity_si),
                    np.float32(window_factor),
                    np.int32(chunk.shape[0]),
                    np.int32(keep_k),
                    np.int32(gl_order),
                    out_g,
                ),
            )
            _state._cp.cuda.Stream.null.synchronize()
            t_greens += perf_counter() - t0

            t0 = perf_counter()
            keep_mask_all[start_idx:end_idx] = _state._cp.asnumpy(keep_g).astype(bool)
            result[start_idx:end_idx] = _state._cp.asnumpy(out_g)
            t_download += perf_counter() - t0
            chunks_done += 1
            start_idx = end_idx
        except _state._cp.cuda.memory.OutOfMemoryError:
            _state._cp.get_default_memory_pool().free_all_blocks()
            if chunk_points <= min_chunk:
                raise
            chunk_points = max(min_chunk, chunk_points // 2)
            print(f"WARNING: GPU OOM in Cext tissue chunk; retrying with --tissue-gpu-chunk-points={chunk_points}")

    if _state.SOLVER_TIMING_DETAILS:
        print(
            "  Tissue GPU Cext solve: "
            f"points={points.shape[0]} active_points={int(np.count_nonzero(keep_mask_all))} "
            f"candidate_k={candidate_k} keep_k={keep_k} candidate_mode={'all_gpu' if use_all_segment_refine else 'kdtree'} "
            f"chunks={chunks_done} chunk_points={chunk_points} "
            f"setup_cpu={_fmt_seconds(t_setup_cpu)} upload_static={_fmt_seconds(t_upload_static)} "
            f"query={_fmt_seconds(t_query)} transfer={_fmt_seconds(t_transfer)} "
            f"refine={_fmt_seconds(t_refine)} greens={_fmt_seconds(t_greens)} "
            f"download={_fmt_seconds(t_download)} total={_fmt_seconds(perf_counter() - t_total)}"
        )

    total_elapsed = perf_counter() - t_total
    geometry_elapsed = float(t_setup_cpu + t_upload_static + t_query + t_transfer + t_refine + t_download)
    _state._LAST_TISSUE_TIMINGS = {
        "backend": "cext_gpu",
        "source_mode": "cext_converged_q_flux",
        "cache_mode": "gpu_streaming",
        "t_tissue_geometry_s": geometry_elapsed,
        "t_tissue_oxygen_s": float(t_greens),
        "t_tissue_total_s": float(total_elapsed),
        "t_tissue_kdtree_query_s": float(t_query),
        "t_tissue_gpu_refine_s": float(t_refine),
        "t_tissue_gpu_transfer_s": float(t_transfer + t_download + t_upload_static),
    }

    validate_n = min(int(_state.TISSUE_GPU_VALIDATE_POINTS), int(points.shape[0]))
    if validate_n > 0:
        old_accel = _state.TISSUE_ACCEL_MODE
        old_streaming = _state.TISSUE_STREAMING_ENABLED
        try:
            _state.TISSUE_ACCEL_MODE = "cpu"
            _state.TISSUE_STREAMING_ENABLED = False
            cpu_mask, cpu_vals = compute_tissue_samples_greens_from_cext_state(
                points[:validate_n],
                starts,
                ends,
                radii,
                cext_state,
                tissue_cache=None,
            )
        finally:
            _state.TISSUE_ACCEL_MODE = old_accel
            _state.TISSUE_STREAMING_ENABLED = old_streaming
        gpu_mask = keep_mask_all[:validate_n]
        gpu_vals = result[:validate_n].astype(float)
        mask_disagree = int(np.count_nonzero(gpu_mask != cpu_mask))
        finite = np.isfinite(cpu_vals) & np.isfinite(gpu_vals)
        max_abs = float(np.max(np.abs(gpu_vals[finite] - cpu_vals[finite]))) if np.any(finite) else float("nan")
        rel_l2 = _relative_l2(gpu_vals[finite], cpu_vals[finite]) if np.any(finite) else float("nan")
        print(
            "  Cext tissue GPU validation: "
            f"points={validate_n} mask_disagree={mask_disagree} "
            f"max_abs={max_abs:.3e} rel_l2={rel_l2:.3e}"
        )

    return keep_mask_all, result.astype(float, copy=False)


__all__ = ['_get_tissue_gpu_kernel', '_compute_tissue_samples_greens_gpu', '_get_cext_tissue_gpu_kernel', '_get_cext_tissue_cell_gpu_kernel', '_build_cext_tissue_cell_list_gpu', '_compute_tissue_samples_greens_from_cext_state_gpu']
