# Legacy symbol names are bound by the temporary TissueSim compatibility facade.
# ruff: noqa: F821
"""Streaming tissue Green's-function workers.

Generated by a behavior-preserving extraction from the frozen TissueSim
baseline. Dependencies are bound by the temporary compatibility facade while
the new typed subsystem APIs replace the legacy global runtime contract.
"""

from __future__ import annotations

from cascade.configuration import _legacy_state as _state
from cascade.runtime import _dependencies

for _dependency_name, _dependency_value in vars(_dependencies).items():
    if not _dependency_name.startswith("__"):
        globals().setdefault(_dependency_name, _dependency_value)
del _dependency_name, _dependency_value

def _process_cext_tissue_chunk(start_idx: int, end_idx: int, data: dict) -> tuple[int, np.ndarray]:
    points_si = data["points_si"]
    nearest_idx = data["nearest_idx"]
    keep_mask = data["keep_mask"]
    valid_source_ids = data["valid_source_ids"]
    gl_points_si = data["gl_points_si"]
    segment_vectors = data.get("segment_vectors")
    lambda_iv_gl = data["lambda_iv_gl"]
    q_weighted_gl = data["q_weighted_gl"]
    mono2_weight_gl = data.get("mono2_weight_gl")
    dipole2_weight_gl = data.get("dipole2_weight_gl")
    seg_cap_gl = data["seg_cap_gl"]
    diffusivity_si = float(data["diffusivity_si"])
    window_factor = float(data["window_factor"])

    chunk = points_si[start_idx:end_idx]
    out = np.zeros((len(chunk),), dtype=float)
    if chunk.size == 0:
        return start_idx, out

    idx_local = nearest_idx[start_idx:end_idx]
    gl_order = int(gl_points_si.shape[1]) if gl_points_si.ndim >= 3 else 0
    for row, point in enumerate(chunk):
        if not keep_mask[start_idx + row]:
            continue
        total = 0.0
        cap_max = 0.0
        for compact_seg in idx_local[row]:
            if compact_seg < 0 or compact_seg >= valid_source_ids.size:
                continue
            source_seg = int(valid_source_ids[int(compact_seg)])
            if source_seg < 0 or source_seg >= gl_points_si.shape[0]:
                continue
            seg_contributed = False
            for source_node in range(gl_order):
                source_lambda = max(float(lambda_iv_gl[source_seg, source_node]), 1e-30)
                source_point = gl_points_si[source_seg, source_node]
                r = float(np.linalg.norm(point - source_point))
                if r <= 1e-12 or r > window_factor * source_lambda:
                    continue
                kernel = math.exp(-r / source_lambda) / (4.0 * math.pi * diffusivity_si * r)
                q = float(q_weighted_gl[source_seg, source_node])
                o2_weight = 0.0
                if mono2_weight_gl is not None:
                    o2_weight += float(mono2_weight_gl[source_seg, source_node])
                if dipole2_weight_gl is not None:
                    o2_weight += float(dipole2_weight_gl[source_seg, source_node])
                total += q * kernel
                if o2_weight != 0.0 and segment_vectors is not None:
                    vec = np.asarray(segment_vectors[source_seg], dtype=float)
                    vlen = float(np.linalg.norm(vec))
                    if vlen > 1e-30:
                        dr = np.asarray(point - source_point, dtype=float)
                        tdotr = float(np.dot(vec, dr) / vlen)
                        mu2 = min((tdotr * tdotr) / max(r * r, 1e-30), 1.0)
                        inv_r = 1.0 / r
                        inv_l = 1.0 / source_lambda
                        pH = ((1.0 - 3.0 * mu2) * (inv_r * inv_r + inv_l * inv_r)
                              + (1.0 - mu2) * inv_l * inv_l) * kernel
                        total += o2_weight * pH
                seg_contributed = True
            if seg_contributed:
                cap_max = max(cap_max, float(seg_cap_gl[source_seg]))
        if total < 0.0 or not np.isfinite(total):
            total = 0.0
        if cap_max > 0.0:
            total = min(total, cap_max)
        out[row] = total
    return start_idx, out


def _compute_cext_streaming_tissue_chunk(task: tuple[int, int, int, dict]) -> tuple[int, int, int, np.ndarray, np.ndarray, int, int]:
    chunk_i, start_idx, end_idx, state = task
    chunk_cache = _prepare_tissue_geometry_from_context(
        state["points"][start_idx:end_idx],
        state["context"],
        max_nearby=int(state["max_nearby"]),
    )
    before_candidates = int(np.count_nonzero(chunk_cache["nearest_idx"] >= 0))
    if state["prune_by_window"]:
        chunk_cache = _compact_tissue_cache_by_influence(chunk_cache, state["influence_radius"])
    after_candidates = int(np.count_nonzero(chunk_cache["nearest_idx"] >= 0))
    worker_data = {
        "points_si": chunk_cache["points_si"],
        "nearest_idx": chunk_cache["nearest_idx"],
        "keep_mask": chunk_cache["keep_mask"],
        "valid_source_ids": state["valid_source_ids"],
        "gl_points_si": state["gl_points_si"],
        "lambda_iv_gl": state["lambda_iv_gl"],
        "q_weighted_gl": state["q_weighted_gl"],
        "mono2_weight_gl": state["mono2_weight_gl"],
        "dipole2_weight_gl": state["dipole2_weight_gl"],
        "segment_vectors": state["segment_vectors"],
        "seg_cap_gl": state["seg_cap_gl"],
        "diffusivity_si": state["diffusivity_si"],
        "window_factor": state["window_factor"],
    }
    _, out = _process_cext_tissue_chunk(0, end_idx - start_idx, worker_data)
    keep_mask = np.asarray(chunk_cache["keep_mask"], dtype=bool)
    return chunk_i, start_idx, end_idx, keep_mask, np.asarray(out, dtype=float), before_candidates, after_candidates


__all__ = ['_process_cext_tissue_chunk', '_compute_cext_streaming_tissue_chunk']
