"""Aitken, Anderson, and trust-region acceleration.

Generated by a behavior-preserving extraction from the frozen TissueSim
baseline. Dependencies are bound by the temporary compatibility facade while
the new typed subsystem APIs replace the legacy global runtime contract.
"""

from __future__ import annotations

import numpy as np

from cascade.configuration import _legacy_state as _state
from .diagnostics import (
    _cext_adaptive_aitken_omega,
    _cext_apply_trust_region,
    _cext_project_candidate,
    _cext_residual_metrics,
    _cext_should_enable_anderson,
    _clip_cext_omega,
)

def _cext_apply_component_acceleration(
    current_flat: np.ndarray,
    mapped_flat: np.ndarray,
    state: dict | None,
    *,
    accel_mode: str,
) -> tuple[np.ndarray, dict, dict]:
    current_arr = np.asarray(current_flat, dtype=np.float32).reshape(-1)
    mapped_arr = np.asarray(mapped_flat, dtype=np.float32).reshape(-1)
    if state is None:
        state = {}
    residual_flat, max_delta_last, rel_residual_last = _cext_residual_metrics(current_arr, mapped_arr)
    prev_abs_residual = float(state.get("prev_abs_residual", float("inf")))
    prev_residual_flat = state.get("prev_residual_flat")
    if prev_residual_flat is not None:
        prev_residual_flat = np.asarray(prev_residual_flat, dtype=np.float32)
        if prev_residual_flat.shape != residual_flat.shape:
            prev_residual_flat = None
    residual_ratio = (
        float(max_delta_last) / max(float(prev_abs_residual), 1.0e-30)
        if np.isfinite(prev_abs_residual)
        else 0.0
    )

    stable_iters = int(state.get("stable_iters", 0))
    anderson_g_history = [np.asarray(arr, dtype=np.float32).copy() for arr in state.get("anderson_g_history", [])]
    anderson_r_history = [np.asarray(arr, dtype=np.float32).copy() for arr in state.get("anderson_r_history", [])]
    accel_rejections = int(state.get("accel_rejections", 0))
    accel_restarts = int(state.get("accel_restarts", 0))
    anderson_depth_used = int(state.get("anderson_depth_used", 0))
    omega_last_prev = float(state.get("omega_last", _clip_cext_omega(_state.CEXT_VESS_COUPLING_OMEGA)))

    if np.isfinite(prev_abs_residual) and max_delta_last > max(float(_state.CEXT_VESS_COUPLING_ACCEL_RESTART_FACTOR), 1.0) * prev_abs_residual:
        anderson_g_history.clear()
        anderson_r_history.clear()
        accel_restarts += 1
        stable_iters = 0
    elif np.isfinite(prev_abs_residual) and residual_ratio <= max(float(_state.CEXT_VESS_COUPLING_ANDERSON_GATE_RATIO), 0.0):
        stable_iters += 1
    elif np.isfinite(prev_abs_residual):
        stable_iters = 0

    omega_fallback = _clip_cext_omega(_state.CEXT_VESS_COUPLING_OMEGA)
    fallback_step = "picard"
    if accel_mode in ("aitken", "anderson"):
        omega_fallback = _cext_adaptive_aitken_omega(prev_residual_flat, residual_flat, omega_last_prev)
        fallback_step = "aitken"
    fallback_candidate = _cext_project_candidate(current_arr + np.float32(omega_fallback) * residual_flat)
    if fallback_candidate is None:
        fallback_candidate = _cext_project_candidate(mapped_arr)
        omega_fallback = _clip_cext_omega(1.0, fallback=omega_fallback)
        fallback_step = "picard"
    if fallback_candidate is None:
        fallback_candidate = np.asarray(mapped_arr, dtype=np.float32)
    trusted_fallback = _cext_apply_trust_region(current_arr, fallback_candidate, mapped_arr)
    if trusted_fallback is not None:
        fallback_candidate = np.asarray(trusted_fallback, dtype=np.float32)

    candidate_flat = np.asarray(fallback_candidate, dtype=np.float32)
    omega_last = float(omega_fallback)
    accel_step_last = fallback_step

    g_hist_entry = np.asarray(mapped_arr, dtype=np.float32).copy()
    r_hist_entry = np.asarray(residual_flat, dtype=np.float32).copy()
    anderson_g_history.append(g_hist_entry)
    anderson_r_history.append(r_hist_entry)
    max_hist = max(int(_state.CEXT_VESS_COUPLING_ANDERSON_DEPTH), 1)
    if len(anderson_g_history) > max_hist:
        anderson_g_history.pop(0)
        anderson_r_history.pop(0)

    iter_local = int(state.get("iter_count", 0)) + 1
    anderson_allowed = (
        accel_mode == "anderson"
        and _cext_should_enable_anderson(
            iter_idx=iter_local,
            stable_iters=stable_iters,
            prev_abs_residual=prev_abs_residual,
            curr_abs_residual=max_delta_last,
            omega_fallback=omega_fallback,
        )
    )
    if anderson_allowed:
        accel_candidate, predicted_abs, depth_used, coeff_l1 = _cext_anderson_candidate(anderson_g_history, anderson_r_history)
        anderson_depth_used = max(anderson_depth_used, int(depth_used))
        accept_factor = max(float(_state.CEXT_VESS_COUPLING_ACCEL_ACCEPT_FACTOR), 0.0)
        if (
            accel_candidate is not None
            and np.isfinite(predicted_abs)
            and predicted_abs <= max_delta_last * accept_factor
            and np.isfinite(coeff_l1)
            and coeff_l1 <= 20.0
        ):
            accel_candidate = _cext_project_candidate(accel_candidate)
            if accel_candidate is not None:
                step_base = float(np.nanmax(np.abs(np.asarray(fallback_candidate, dtype=float) - np.asarray(current_arr, dtype=float)))) if current_arr.size else 0.0
                step_accel = float(np.nanmax(np.abs(np.asarray(accel_candidate, dtype=float) - np.asarray(current_arr, dtype=float)))) if current_arr.size else 0.0
                step_factor = max(float(_state.CEXT_VESS_COUPLING_ACCEL_STEP_FACTOR), 1.0)
                lam = 1.0
                if step_base > 0.0 and step_accel > step_factor * step_base:
                    lam = min(1.0, (step_factor * step_base) / max(step_accel, 1.0e-30))
                blended = np.asarray(fallback_candidate, dtype=np.float32) + np.float32(lam) * (np.asarray(accel_candidate, dtype=np.float32) - np.asarray(fallback_candidate, dtype=np.float32))
                projected_blend = _cext_apply_trust_region(current_arr, blended, mapped_arr)
                if projected_blend is not None:
                    candidate_flat = np.asarray(projected_blend, dtype=np.float32)
                    accel_step_last = "anderson" if lam >= 0.999 else "anderson_blend"
        else:
            accel_rejections += 1
            anderson_g_history.clear()
            anderson_r_history.clear()
            accel_restarts += 1
            stable_iters = 0

    state_out = {
        "prev_residual_flat": np.asarray(residual_flat, dtype=np.float32).copy(),
        "prev_abs_residual": float(max_delta_last),
        "stable_iters": int(stable_iters),
        "anderson_g_history": anderson_g_history,
        "anderson_r_history": anderson_r_history,
        "accel_rejections": int(accel_rejections),
        "accel_restarts": int(accel_restarts),
        "anderson_depth_used": int(anderson_depth_used),
        "omega_last": float(omega_last),
        "iter_count": int(iter_local),
    }
    metrics = {
        "max_delta_last": float(max_delta_last),
        "rel_residual_last": float(rel_residual_last),
        "omega_last": float(omega_last),
        "accel_step_last": accel_step_last,
        "accel_rejections": int(accel_rejections),
        "accel_restarts": int(accel_restarts),
        "anderson_depth_used": int(anderson_depth_used),
        "stable_iters": int(stable_iters),
    }
    return candidate_flat, state_out, metrics


def _cext_anderson_candidate(
    g_history: list[np.ndarray],
    r_history: list[np.ndarray],
) -> tuple[np.ndarray | None, float, int, float]:
    depth = max(int(_state.CEXT_VESS_COUPLING_ANDERSON_DEPTH), 0)
    if depth <= 1 or len(g_history) < 2 or len(r_history) < 2:
        return None, float("inf"), 0, float("inf")
    g_used = list(g_history[-depth:])
    r_used = list(r_history[-depth:])
    p = min(len(g_used), len(r_used))
    if p < 2:
        return None, float("inf"), 0, float("inf")
    g_used = g_used[-p:]
    r_used = r_used[-p:]

    gram = np.zeros((p, p), dtype=np.float64)
    for i in range(p):
        ri = np.asarray(r_used[i], dtype=np.float32)
        for j in range(i, p):
            val = float(np.dot(ri, np.asarray(r_used[j], dtype=np.float32)))
            gram[i, j] = val
            gram[j, i] = val
    gram.flat[:: p + 1] += max(float(_state.CEXT_VESS_COUPLING_ANDERSON_REG), 0.0)
    ones = np.ones((p, 1), dtype=np.float64)
    system = np.block(
        [
            [gram, ones],
            [ones.T, np.zeros((1, 1), dtype=np.float64)],
        ]
    )
    rhs = np.zeros((p + 1,), dtype=np.float64)
    rhs[-1] = 1.0
    try:
        sol = np.linalg.solve(system, rhs)
        alpha = np.asarray(sol[:p], dtype=np.float64)
    except np.linalg.LinAlgError:
        return None, float("inf"), 0, float("inf")
    if not np.all(np.isfinite(alpha)):
        return None, float("inf"), 0, float("inf")

    candidate = np.zeros_like(np.asarray(g_used[-1], dtype=np.float32), dtype=np.float32)
    predicted = np.zeros_like(np.asarray(r_used[-1], dtype=np.float32), dtype=np.float32)
    for coeff, g_arr, r_arr in zip(alpha, g_used, r_used):
        coeff32 = np.float32(coeff)
        candidate += coeff32 * np.asarray(g_arr, dtype=np.float32)
        predicted += coeff32 * np.asarray(r_arr, dtype=np.float32)
    predicted_abs = float(np.nanmax(np.abs(np.asarray(predicted, dtype=float)))) if predicted.size else 0.0
    coeff_l1 = float(np.sum(np.abs(alpha)))
    return candidate, predicted_abs, int(p), coeff_l1


__all__ = ['_cext_apply_component_acceleration', '_cext_anderson_candidate']
