# Legacy symbol names are bound by the temporary TissueSim compatibility facade.
# ruff: noqa: F821
"""External-field backend selection and level scheduling.

Generated by a behavior-preserving extraction from the frozen TissueSim
baseline. Dependencies are bound by the temporary compatibility facade while
the new typed subsystem APIs replace the legacy global runtime contract.
"""

from __future__ import annotations

from cascade.configuration import _legacy_state as _state
from cascade.runtime import _dependencies

for _dependency_name, _dependency_value in vars(_dependencies).items():
    if not _dependency_name.startswith("__"):
        globals().setdefault(_dependency_name, _dependency_value)
del _dependency_name, _dependency_value

def _resolve_cext_accel_mode(*, require_gpu: bool = False) -> str:
    mode = str(_state.CEXT_ACCEL_MODE or "cpu").strip().lower()
    if mode not in ("cpu", "gpu", "auto"):
        raise ValueError("--cext-accel must be 'cpu', 'gpu', or 'auto'.")
    if mode == "auto":
        if _cupy_device_available():
            return "gpu"
        return "cpu"
    if mode == "gpu" and not _cupy_device_available():
        if require_gpu:
            raise RuntimeError(
                "Cext GPU mode requested but no compatible CuPy CUDA device is available. "
                "Verify `import cupy` in the CASCADE environment."
            )
        return "cpu"
    return mode


def _resolve_cext_frozen_accel_mode(*, require_gpu: bool = False) -> str:
    mode = str(_state.CEXT_FROZEN_ACCEL_MODE or "cpu").strip().lower()
    if mode not in ("cpu", "gpu", "auto"):
        raise ValueError("--cext-frozen-accel must be 'cpu', 'gpu', or 'auto'.")
    if mode == "auto":
        if _cupy_device_available():
            return "gpu"
        return "cpu"
    if mode == "gpu" and not _cupy_device_available():
        if require_gpu:
            raise RuntimeError(
                "Frozen Cext GPU mode requested but no compatible CuPy CUDA device is available. "
                "Verify `import cupy` in the CASCADE environment."
            )
        return "cpu"
    return mode


def _build_topdown_level_slices(order: np.ndarray, parents: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    order_arr = np.asarray(order, dtype=np.int64).reshape(-1)
    parents_arr = np.asarray(parents, dtype=np.int64).reshape(-1)
    nseg = int(parents_arr.shape[0])
    if nseg <= 0:
        empty = np.empty((0,), dtype=np.int32)
        return empty, np.zeros((1,), dtype=np.int32), empty
    if _state._HAVE_NUMBA:
        return _build_topdown_level_slices_numba(order_arr, parents_arr)
    depth = np.zeros((nseg,), dtype=np.int32)
    for idx in order_arr:
        idx_i = int(idx)
        if idx_i < 0 or idx_i >= nseg:
            continue
        parent = int(parents_arr[idx_i])
        if parent >= 0 and parent < nseg:
            depth[idx_i] = np.int32(depth[parent] + 1)
        else:
            depth[idx_i] = np.int32(0)
    max_depth = int(np.max(depth)) if depth.size else 0
    counts = np.zeros((max_depth + 1,), dtype=np.int32)
    for idx in order_arr:
        idx_i = int(idx)
        if 0 <= idx_i < nseg:
            counts[int(depth[idx_i])] += 1
    level_offsets = np.zeros((counts.size + 1,), dtype=np.int32)
    np.cumsum(counts, out=level_offsets[1:])
    write_pos = level_offsets[:-1].copy()
    level_order = np.empty((nseg,), dtype=np.int32)
    for idx in order_arr:
        idx_i = int(idx)
        if idx_i < 0 or idx_i >= nseg:
            continue
        d = int(depth[idx_i])
        pos = int(write_pos[d])
        level_order[pos] = np.int32(idx_i)
        write_pos[d] = np.int32(pos + 1)
    return level_order, level_offsets, depth


__all__ = ['_resolve_cext_accel_mode', '_resolve_cext_frozen_accel_mode', '_build_topdown_level_slices']
