"""External-field validation, residuals, and active-set diagnostics.

Generated by a behavior-preserving extraction from the frozen TissueSim
baseline. Dependencies are bound by the temporary compatibility facade while
the new typed subsystem APIs replace the legacy global runtime contract.
"""

from __future__ import annotations

from cascade.configuration import _legacy_state as _state
from cascade.runtime import _dependencies

for _dependency_name, _dependency_value in vars(_dependencies).items():
    if not _dependency_name.startswith("__"):
        globals().setdefault(_dependency_name, _dependency_value)
del _dependency_name, _dependency_value

def _validate_cext_gpu_batch(
    context: dict,
    ext_state: dict,
    target_seg_ids: np.ndarray,
    row_ptr: np.ndarray,
    col_idx: np.ndarray,
    gpu_out: np.ndarray,
) -> None:
    validate_n = min(int(_state.CEXT_GPU_VALIDATE_SEGMENTS), int(target_seg_ids.size))
    if validate_n <= 0:
        return
    if row_ptr.size <= 1:
        return
    cpu_row_end = int(row_ptr[validate_n])
    cpu_out = _compute_cext_batch_cpu(
        context,
        ext_state,
        np.asarray(target_seg_ids[:validate_n], dtype=np.int32),
        np.asarray(row_ptr[: validate_n + 1], dtype=np.int32),
        np.asarray(col_idx[:cpu_row_end], dtype=np.int32),
    )
    gpu_slice = np.asarray(gpu_out[:validate_n], dtype=float)
    finite = np.isfinite(cpu_out) & np.isfinite(gpu_slice)
    max_abs = float(np.max(np.abs(np.asarray(cpu_out, dtype=float)[finite] - gpu_slice[finite]))) if np.any(finite) else float("nan")
    rel_l2 = _relative_l2(np.asarray(cpu_out, dtype=float)[finite], gpu_slice[finite]) if np.any(finite) else float("nan")
    print(
        "  Cext GPU validate: "
        f"segments={validate_n} max_abs={max_abs:.6e} rel_l2={rel_l2:.6e}"
    )


def _default_cext_timing_details(*, backend: str = "none") -> dict[str, float | str | int | bool]:
    return {
        "backend": backend,
        "t_cext_total_s": 0.0,
        "t_cext_hct_setup_s": 0.0,
        "t_cext_context_build_s": 0.0,
        "t_cext_solver_setup_s": 0.0,
        "t_cext_query_s": 0.0,
        "t_cext_kernel_s": 0.0,
        "t_cext_gpu_transfer_s": 0.0,
        "t_cext_frozen_gpu_transfer_s": 0.0,
        "t_cext_init_s": 0.0,
        "t_cext_init_kernel_s": 0.0,
        "t_cext_init_gpu_transfer_s": 0.0,
        "t_cext_init_frozen_gpu_transfer_s": 0.0,
        "t_cext_init_frozen_kernel_s": 0.0,
        "t_cext_init_cache_s": 0.0,
        "t_cext_init_hybrid_call_s": 0.0,
        "t_cext_final_frozen_gpu_transfer_s": 0.0,
        "t_cext_final_frozen_kernel_s": 0.0,
        "t_cext_final_cache_s": 0.0,
        "t_cext_final_source_state_s": 0.0,
        "t_cext_hybrid_deposit_s": 0.0,
        "t_cext_hybrid_fft_s": 0.0,
        "t_cext_hybrid_o2_terms_s": 0.0,
        "t_cext_hybrid_self_subtract_s": 0.0,
        "t_cext_hybrid_local_corr_s": 0.0,
        "t_cext_hybrid_sample_s": 0.0,
        "t_cext_treecode_build_s": 0.0,
        "t_cext_treecode_aggregate_s": 0.0,
        "t_cext_treecode_traversal_s": 0.0,
        "t_cext_treecode_exact_s": 0.0,
        "cext_hybrid_bg_solver": "",
        "cext_treecode_theta": 0.0,
        "cext_treecode_order": 0,
        "cext_treecode_leaf_nodes": 0,
        "cext_treecode_lambda_bins": 0,
        "cext_treecode_near_radius_si": 0.0,
        "cext_treecode_node_count": 0,
        "cext_treecode_leaf_count": 0,
        "cext_treecode_max_depth": 0,
        "cext_treecode_accepted_nodes": 0,
        "cext_treecode_opened_nodes": 0,
        "cext_treecode_exact_pairs": 0,
        "cext_init_mode": str(_state.CEXT_INIT_MODE).lower(),
        "cext_init_performed": False,
        "cext_outer_iterations_completed": 0,
        "cext_total_iterations_effective": 0,
        "cext_accel_mode": str(_state.CEXT_VESS_COUPLING_ACCEL).lower(),
        "cext_accel_step_last": "picard",
        "cext_accel_rejections": 0,
        "cext_accel_restarts": 0,
        "cext_omega_last": float(_state.CEXT_VESS_COUPLING_OMEGA),
        "cext_rel_residual_last": 0.0,
        "cext_max_delta_last": 0.0,
        "cext_best_max_delta": 0.0,
        "cext_best_seen_stop": False,
        "cext_step_rejections": 0,
        "cext_candidate_batches": 0,
        "cext_frozen_backend": "none",
        "cext_active_source_count": 0,
        "cext_frozen_source_count": 0,
        "cext_active_target_count": 0,
        "cext_frozen_target_count": 0,
        "cext_active_component_count": 0,
        "cext_largest_component_size": 0,
        "cext_active_freeze_events": 0,
        "cext_active_refreshes": 0,
        "cext_target_freeze_events": 0,
        "cext_target_reactivations": 0,
        "cext_hybrid_bg_grid": 0,
        "cext_hybrid_lambda_bins": 0,
        "cext_hybrid_lambda_bin_policy": "",
        "cext_hybrid_lambda_bin_edges_hash": "",
        "cext_hybrid_near_radius_si": 0.0,
        "cext_tail_mode_entered": False,
        "cext_tail_solver": "none",
        "cext_tail_core_count": 0,
        "cext_tail_nonlinear_iters": 0,
        "cext_tail_gmres_iters": 0,
    }


def _maybe_trace_cext_iteration(
    iteration: int,
    ext_state: dict,
    *,
    solver: str,
    context: dict | None = None,
    backend: str | None = None,
    max_delta: float | None = None,
    rel_residual: float | None = None,
) -> None:
    callback = _state.CEXT_TRACE_CALLBACK
    if callback is None:
        return
    iteration_i = int(iteration)
    trace_iterations = _state.CEXT_TRACE_ITERATIONS
    if trace_iterations is not None and iteration_i not in trace_iterations:
        return
    if context is not None and "c_ext_gl" in ext_state and "c_wall_gl" in ext_state:
        _build_cext_iteration_cache(context, ext_state)
    c_ext_gl = ext_state.get("c_ext_gl")
    if c_ext_gl is None:
        return
    c_ext_arr = np.asarray(c_ext_gl, dtype=np.float32).copy()

    def _trace_array(name: str) -> np.ndarray:
        value = ext_state.get(name)
        if value is None:
            return np.full_like(c_ext_arr, np.nan, dtype=np.float32)
        arr = np.asarray(value, dtype=np.float32)
        if arr.shape != c_ext_arr.shape:
            return np.full_like(c_ext_arr, np.nan, dtype=np.float32)
        return arr.copy()

    tissue_cx = np.empty((0,), dtype=np.float32)
    if bool(_state.CEXT_TRACE_TISSUE_ENABLED) and context is not None:
        points = _state.CEXT_TRACE_TISSUE_POINTS
        if points is not None:
            points_arr = np.asarray(points, dtype=float)
            if points_arr.size:
                cext_state = _snapshot_cext_source_state(
                    context,
                    ext_state,
                    solver=str(solver),
                    backend=str(backend or ext_state.get("backend", "")),
                )
                starts_cm = np.asarray(context["flow_starts_si"], dtype=float) / _state.CM_TO_M
                ends_cm = np.asarray(context["flow_ends_si"], dtype=float) / _state.CM_TO_M
                radii_cm = np.asarray(context["radii_si"], dtype=float) / _state.CM_TO_M
                mask, values = compute_tissue_samples_greens_from_cext_state(
                    points_arr,
                    starts_cm,
                    ends_cm,
                    radii_cm,
                    cext_state,
                    tissue_cache=_state.CEXT_TRACE_TISSUE_CACHE,
                )
                tissue_cx = np.asarray(values[np.asarray(mask, dtype=bool)], dtype=np.float32).reshape(-1)

    callback(
        iteration=iteration_i,
        c_ext_gl=c_ext_arr,
        c_iv_gl=_trace_array("c_iv_gl"),
        c_bulk_gl=_trace_array("c_bulk_gl"),
        c_wall_gl=_trace_array("c_wall_gl"),
        lambda_iv_gl=_trace_array("lambda_iv_gl"),
        k_if_gl=_trace_array("k_if_gl"),
        q_line_gl=_trace_array("q_line_gl"),
        tissue_cx=tissue_cx,
        solver=str(solver),
        fluid=str(_state.ACTIVE_FLUID),
        max_delta=None if max_delta is None else float(max_delta),
        rel_residual=None if rel_residual is None else float(rel_residual),
    )


def _cext_relaxation_bounds() -> tuple[float, float]:
    omega_min = max(float(_state.CEXT_VESS_COUPLING_OMEGA_MIN), 0.0)
    omega_max = max(float(_state.CEXT_VESS_COUPLING_OMEGA_MAX), omega_min)
    return omega_min, omega_max


def _clip_cext_omega(value: float, *, fallback: float | None = None) -> float:
    omega_min, omega_max = _cext_relaxation_bounds()
    candidate = float(value)
    if not np.isfinite(candidate):
        candidate = float(_state.CEXT_VESS_COUPLING_OMEGA if fallback is None else fallback)
    return float(np.clip(candidate, omega_min, omega_max))


def _cext_residual_metrics(
    current: np.ndarray,
    mapped: np.ndarray,
) -> tuple[np.ndarray, float, float]:
    residual = np.asarray(mapped, dtype=np.float32) - np.asarray(current, dtype=np.float32)
    abs_inf = float(np.nanmax(np.abs(np.asarray(residual, dtype=float)))) if residual.size else 0.0
    scale = float(np.nanmax(np.abs(np.asarray(mapped, dtype=float)))) if mapped.size else float(_state.VESS_CONC_FLOOR)
    scale = max(scale, float(_state.VESS_CONC_FLOOR))
    rel_inf = abs_inf / scale if scale > 0.0 else 0.0
    return np.asarray(residual, dtype=np.float32), abs_inf, float(rel_inf)


def _cext_source_state_delta_metrics(
    prev_c_ext_gl: np.ndarray | None,
    prev_c_iv_gl: np.ndarray | None,
    curr_c_ext_gl: np.ndarray,
    curr_c_iv_gl: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    curr_c_ext = np.asarray(curr_c_ext_gl, dtype=np.float32)
    curr_c_iv = np.asarray(curr_c_iv_gl, dtype=np.float32)
    nseg = int(curr_c_ext.shape[0])
    if (
        prev_c_ext_gl is None
        or prev_c_iv_gl is None
        or np.asarray(prev_c_ext_gl).shape != curr_c_ext.shape
        or np.asarray(prev_c_iv_gl).shape != curr_c_iv.shape
    ):
        return np.full((nseg,), np.inf, dtype=np.float32), np.full((nseg,), np.inf, dtype=np.float32)
    prev_c_ext = np.asarray(prev_c_ext_gl, dtype=np.float32)
    prev_c_iv = np.asarray(prev_c_iv_gl, dtype=np.float32)
    abs_delta = np.maximum(
        np.max(np.abs(curr_c_ext - prev_c_ext), axis=1),
        np.max(np.abs(curr_c_iv - prev_c_iv), axis=1),
    ).astype(np.float32, copy=False)
    scale = np.maximum.reduce(
        [
            np.max(np.abs(curr_c_ext), axis=1),
            np.max(np.abs(prev_c_ext), axis=1),
            np.max(np.abs(curr_c_iv), axis=1),
            np.max(np.abs(prev_c_iv), axis=1),
            np.full((nseg,), float(_state.VESS_CONC_FLOOR), dtype=np.float32),
        ]
    ).astype(np.float32, copy=False)
    rel_delta = np.divide(
        abs_delta,
        np.maximum(scale, np.float32(_state.VESS_CONC_FLOOR)),
        out=np.full_like(abs_delta, np.inf, dtype=np.float32),
        where=np.maximum(scale, np.float32(_state.VESS_CONC_FLOOR)) > 0.0,
    )
    return abs_delta, rel_delta


def _cext_active_source_cell_stats(
    context: dict,
    source_mask: np.ndarray,
    source_abs_delta: np.ndarray,
    source_rel_delta: np.ndarray,
) -> dict:
    n_cells = int(context.get("gpu_direct_n_cells", 0))
    source_mask_arr = np.asarray(source_mask, dtype=bool).reshape(-1)
    home_flat = np.asarray(context.get("gpu_direct_home_cell_flat", np.zeros((source_mask_arr.size,), dtype=np.int64)), dtype=np.int64)
    active_ids = np.flatnonzero(source_mask_arr).astype(np.int32, copy=False)
    cell_counts = np.zeros((max(n_cells, 0),), dtype=np.int32)
    cell_abs_max = np.zeros((max(n_cells, 0),), dtype=np.float32)
    cell_rel_max = np.zeros((max(n_cells, 0),), dtype=np.float32)
    max_active_reach = 0.0
    if active_ids.size > 0 and n_cells > 0:
        active_flat = np.asarray(home_flat[active_ids], dtype=np.int64)
        counts = np.bincount(active_flat, minlength=n_cells)
        cell_counts = np.asarray(counts, dtype=np.int32)
        np.maximum.at(cell_abs_max, active_flat, np.asarray(source_abs_delta[active_ids], dtype=np.float32))
        np.maximum.at(cell_rel_max, active_flat, np.asarray(source_rel_delta[active_ids], dtype=np.float32))
        reach_si = np.asarray(context.get("reach_si", np.zeros((source_mask_arr.size,), dtype=np.float32)), dtype=np.float32)
        max_active_reach = float(np.max(np.asarray(reach_si[active_ids], dtype=np.float32))) if active_ids.size else 0.0
    return {
        "active_ids": active_ids,
        "cell_counts": cell_counts,
        "cell_abs_max": cell_abs_max,
        "cell_rel_max": cell_rel_max,
        "max_active_reach": float(max_active_reach),
    }


def _cext_target_query_cells(
    context: dict,
    target_seg_ids: np.ndarray,
    *,
    max_active_reach: float,
    neighbor_pad: int,
) -> list[np.ndarray]:
    target_ids = np.asarray(target_seg_ids, dtype=np.int32).reshape(-1)
    if target_ids.size == 0:
        return []
    cell_size = float(context.get("cell_size", 0.0))
    dims = np.asarray(context.get("gpu_direct_cell_dims", np.zeros((3,), dtype=np.int32)), dtype=np.int32)
    origin = np.asarray(context.get("gpu_direct_cell_origin", np.zeros((3,), dtype=np.int32)), dtype=np.int32)
    midpoints = np.asarray(context.get("midpoints_si", np.zeros((0, 3), dtype=np.float32)), dtype=np.float32)
    reach_si = np.asarray(context.get("reach_si", np.zeros((midpoints.shape[0],), dtype=np.float32)), dtype=np.float32)
    if target_ids.size == 0 or cell_size <= 0.0 or dims.size < 3 or int(np.prod(dims)) <= 0:
        return [np.zeros((0,), dtype=np.int32) for _ in range(target_ids.size)]
    reach_scale = max(float(_state.CEXT_APPROX_WINDOW_SCALE), 0.0)
    out: list[np.ndarray] = []
    pad = max(int(neighbor_pad), 0)
    dim_x = int(dims[0])
    dim_y = int(dims[1])
    dim_z = int(dims[2])
    for target_seg in target_ids:
        mid = np.asarray(midpoints[int(target_seg)], dtype=float)
        query_reach = reach_scale * float(reach_si[int(target_seg)] + max_active_reach)
        lo = np.floor((mid - query_reach) / cell_size).astype(np.int64) - origin.astype(np.int64) - pad
        hi = np.floor((mid + query_reach) / cell_size).astype(np.int64) - origin.astype(np.int64) + pad
        lo = np.maximum(lo, 0)
        hi = np.minimum(hi, np.asarray([dim_x - 1, dim_y - 1, dim_z - 1], dtype=np.int64))
        cells: list[int] = []
        for ix in range(int(lo[0]), int(hi[0]) + 1):
            for iy in range(int(lo[1]), int(hi[1]) + 1):
                base = dim_x * iy
                for iz in range(int(lo[2]), int(hi[2]) + 1):
                    flat = ix + dim_x * (iy + dim_y * iz)
                    cells.append(int(flat))
        out.append(np.asarray(cells, dtype=np.int32))
    return out


def _cext_target_neighbor_metrics(
    context: dict,
    target_seg_ids: np.ndarray,
    cell_stats: dict,
    *,
    neighbor_pad: int,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, list[np.ndarray]]:
    target_ids = np.asarray(target_seg_ids, dtype=np.int32).reshape(-1)
    if target_ids.size == 0:
        empty = np.zeros((0,), dtype=np.float32)
        return empty.astype(np.int32), empty, empty, []
    query_cells = _cext_target_query_cells(
        context,
        target_ids,
        max_active_reach=float(cell_stats.get("max_active_reach", 0.0)),
        neighbor_pad=neighbor_pad,
    )
    cell_counts = np.asarray(cell_stats.get("cell_counts", np.zeros((0,), dtype=np.int32)), dtype=np.int32)
    cell_abs_max = np.asarray(cell_stats.get("cell_abs_max", np.zeros((0,), dtype=np.float32)), dtype=np.float32)
    cell_rel_max = np.asarray(cell_stats.get("cell_rel_max", np.zeros((0,), dtype=np.float32)), dtype=np.float32)
    neighbor_counts = np.zeros((target_ids.size,), dtype=np.int32)
    neighbor_abs = np.zeros((target_ids.size,), dtype=np.float32)
    neighbor_rel = np.zeros((target_ids.size,), dtype=np.float32)
    for idx, cells in enumerate(query_cells):
        if cells.size <= 0:
            continue
        valid_cells = cells[(cells >= 0) & (cells < cell_counts.size)]
        if valid_cells.size <= 0:
            continue
        neighbor_counts[idx] = int(np.sum(cell_counts[valid_cells], dtype=np.int64))
        neighbor_abs[idx] = float(np.max(cell_abs_max[valid_cells])) if valid_cells.size else 0.0
        neighbor_rel[idx] = float(np.max(cell_rel_max[valid_cells])) if valid_cells.size else 0.0
    return neighbor_counts, neighbor_abs, neighbor_rel, query_cells


def _cext_hybrid_local_target_ids(
    context: dict,
    hybrid: dict,
    active_target_ids: np.ndarray,
    active_source_mask: np.ndarray,
) -> np.ndarray:
    target_ids = np.asarray(active_target_ids, dtype=np.int32).reshape(-1)
    if target_ids.size <= 0:
        return np.zeros((0,), dtype=np.int32)
    node_seg_ids = np.asarray(hybrid.get("node_seg_ids", np.zeros((0,), dtype=np.int32)), dtype=np.int32)
    node_cell_flat = np.asarray(hybrid.get("local_node_cell_flat", np.zeros((0,), dtype=np.int32)), dtype=np.int32)
    if node_seg_ids.size <= 0 or node_cell_flat.size != node_seg_ids.size:
        return target_ids
    source_mask = np.asarray(active_source_mask, dtype=bool).reshape(-1)
    if source_mask.size <= 0 or int(np.count_nonzero(source_mask)) >= int(source_mask.size):
        return target_ids
    grid_n = int(hybrid.get("grid_n", 0))
    grid_cells = int(grid_n * grid_n * grid_n)
    if grid_n <= 0 or grid_cells <= 0:
        return target_ids
    active_nodes = source_mask[np.clip(node_seg_ids, 0, max(source_mask.size - 1, 0))]
    active_cells = node_cell_flat[np.asarray(active_nodes, dtype=bool)]
    active_cells = active_cells[(active_cells >= 0) & (active_cells < grid_cells)]
    if active_cells.size <= 0:
        return np.zeros((0,), dtype=np.int32)
    active_grid = np.zeros((grid_cells,), dtype=bool)
    active_grid[np.asarray(active_cells, dtype=np.int64)] = True
    active_grid = active_grid.reshape((grid_n, grid_n, grid_n))
    rad_cells = int(max(int(hybrid.get("local_rad_cells", 0)), 0))
    if rad_cells > 0:
        if _state._HAVE_SCIPY_NDIMAGE and _state._scipy_ndimage is not None:
            structure = np.ones((2 * rad_cells + 1, 2 * rad_cells + 1, 2 * rad_cells + 1), dtype=bool)
            active_grid = _state._scipy_ndimage.binary_dilation(active_grid, structure=structure, border_value=False)
        else:
            expanded = np.zeros_like(active_grid, dtype=bool)
            active_idx = np.argwhere(active_grid)
            for ix, iy, iz in active_idx:
                lo_x = max(int(ix) - rad_cells, 0)
                hi_x = min(int(ix) + rad_cells + 1, grid_n)
                lo_y = max(int(iy) - rad_cells, 0)
                hi_y = min(int(iy) + rad_cells + 1, grid_n)
                lo_z = max(int(iz) - rad_cells, 0)
                hi_z = min(int(iz) + rad_cells + 1, grid_n)
                expanded[lo_x:hi_x, lo_y:hi_y, lo_z:hi_z] = True
            active_grid = expanded
    gl_order = int(np.asarray(context.get("gl_points_si", np.zeros((0, 0, 3), dtype=np.float32))).shape[1])
    if gl_order <= 0:
        return target_ids
    target_node_ids = (target_ids[:, None].astype(np.int64) * np.int64(gl_order) + np.arange(gl_order, dtype=np.int64)[None, :]).reshape(-1)
    valid_nodes = (target_node_ids >= 0) & (target_node_ids < node_cell_flat.size)
    target_node_cells = np.full((target_node_ids.size,), -1, dtype=np.int32)
    target_node_cells[valid_nodes] = node_cell_flat[target_node_ids[valid_nodes]]
    target_active = np.zeros((target_node_ids.size,), dtype=bool)
    valid_cells = (target_node_cells >= 0) & (target_node_cells < grid_cells)
    if np.any(valid_cells):
        target_active[valid_cells] = active_grid.reshape(-1)[target_node_cells[valid_cells]]
    target_active = target_active.reshape((target_ids.size, gl_order))
    return np.asarray(target_ids[np.any(target_active, axis=1)], dtype=np.int32)


def _cext_build_active_components_from_cells(
    target_seg_ids: np.ndarray,
    query_cells: list[np.ndarray],
    cell_stats: dict,
) -> tuple[list[np.ndarray], int]:
    target_ids = np.asarray(target_seg_ids, dtype=np.int32).reshape(-1)
    ntarget = int(target_ids.size)
    if ntarget <= 0:
        return [], 0
    if ntarget == 1:
        return [np.asarray(target_ids, dtype=np.int32)], 1
    cell_counts = np.asarray(cell_stats.get("cell_counts", np.zeros((0,), dtype=np.int32)), dtype=np.int32)
    parent = np.arange(ntarget, dtype=np.int32)

    def find(x: int) -> int:
        while parent[x] != x:
            parent[x] = parent[int(parent[x])]
            x = int(parent[x])
        return x

    def union(a: int, b: int) -> None:
        ra = find(a)
        rb = find(b)
        if ra != rb:
            parent[rb] = ra

    cell_to_targets: dict[int, int] = {}
    for local_idx, cells in enumerate(query_cells):
        if cells.size <= 0:
            continue
        valid_cells = cells[(cells >= 0) & (cells < cell_counts.size)]
        for cell in np.unique(valid_cells):
            if int(cell_counts[int(cell)]) <= 0:
                continue
            prev = cell_to_targets.get(int(cell))
            if prev is None:
                cell_to_targets[int(cell)] = int(local_idx)
            else:
                union(int(prev), int(local_idx))

    groups: dict[int, list[int]] = defaultdict(list)
    for local_idx in range(ntarget):
        groups[find(local_idx)].append(local_idx)
    components = [np.asarray(target_ids[np.asarray(local_ids, dtype=np.int32)], dtype=np.int32) for local_ids in groups.values()]
    components.sort(key=lambda arr: int(arr.size), reverse=True)
    largest = int(components[0].size) if components else 0
    return components, largest


def _cext_component_source_ids_from_cells(
    context: dict,
    active_source_mask: np.ndarray,
    component_cells: Sequence[np.ndarray],
) -> np.ndarray:
    cell_ptr = np.asarray(context.get("gpu_direct_cell_ptr", np.zeros((1,), dtype=np.int32)), dtype=np.int32)
    cell_seg_ids = np.asarray(context.get("gpu_direct_cell_seg_ids", np.zeros((0,), dtype=np.int32)), dtype=np.int32)
    active_mask = np.asarray(active_source_mask, dtype=bool).reshape(-1)
    if cell_ptr.size <= 1 or cell_seg_ids.size <= 0 or not np.any(active_mask):
        return np.zeros((0,), dtype=np.int32)
    source_ids: list[np.ndarray] = []
    for cells in component_cells:
        valid_cells = np.asarray(cells, dtype=np.int32)
        valid_cells = valid_cells[(valid_cells >= 0) & (valid_cells + 1 < cell_ptr.size)]
        if valid_cells.size <= 0:
            continue
        for cell in np.unique(valid_cells):
            start = int(cell_ptr[int(cell)])
            stop = int(cell_ptr[int(cell) + 1])
            if stop <= start:
                continue
            segs = np.asarray(cell_seg_ids[start:stop], dtype=np.int32)
            if segs.size > 0:
                source_ids.append(segs[np.asarray(active_mask[segs], dtype=bool)])
    if not source_ids:
        return np.zeros((0,), dtype=np.int32)
    return np.unique(np.concatenate(source_ids).astype(np.int32, copy=False))


def _cext_adaptive_aitken_omega(
    prev_residual: np.ndarray | None,
    curr_residual: np.ndarray,
    prev_omega: float,
) -> float:
    omega = _clip_cext_omega(prev_omega)
    if prev_residual is None or np.asarray(prev_residual).shape != np.asarray(curr_residual).shape:
        return omega
    delta = np.asarray(curr_residual, dtype=np.float32) - np.asarray(prev_residual, dtype=np.float32)
    denom = float(np.dot(delta, delta))
    if not np.isfinite(denom) or denom <= 1.0e-30:
        return omega
    numer = float(np.dot(np.asarray(prev_residual, dtype=np.float32), delta))
    return _clip_cext_omega(-omega * numer / denom, fallback=omega)


def _cext_project_candidate(candidate: np.ndarray) -> np.ndarray | None:
    arr = np.asarray(candidate, dtype=np.float32)
    if arr.size == 0:
        return np.asarray(arr, dtype=np.float32)
    if not np.all(np.isfinite(arr)):
        return None
    return np.maximum(arr, np.float32(0.0)).astype(np.float32, copy=False)


def _cext_apply_trust_region(
    current: np.ndarray,
    candidate: np.ndarray,
    mapped: np.ndarray,
) -> np.ndarray | None:
    projected = _cext_project_candidate(candidate)
    if projected is None:
        return None
    trust_abs = max(float(_state.CEXT_VESS_COUPLING_TRUST_ABS), 0.0)
    trust_rel = max(float(_state.CEXT_VESS_COUPLING_TRUST_REL), 0.0)
    if trust_abs <= 0.0 and trust_rel <= 0.0:
        return projected
    current_arr = np.asarray(current, dtype=np.float32)
    mapped_arr = np.asarray(mapped, dtype=np.float32)
    step = np.asarray(projected, dtype=np.float32) - current_arr
    scale = np.maximum(
        np.maximum(np.abs(current_arr), np.abs(mapped_arr)),
        np.float32(_state.VESS_CONC_FLOOR),
    )
    cap = np.float32(trust_abs) + np.float32(trust_rel) * scale
    bounded = current_arr + np.clip(step, -cap, cap).astype(np.float32, copy=False)
    return _cext_project_candidate(bounded)


def _cext_should_enable_anderson(
    *,
    iter_idx: int,
    stable_iters: int,
    prev_abs_residual: float,
    curr_abs_residual: float,
    omega_fallback: float,
) -> bool:
    if iter_idx < max(int(_state.CEXT_VESS_COUPLING_ANDERSON_START), 1):
        return False
    if stable_iters < max(int(_state.CEXT_VESS_COUPLING_ANDERSON_MIN_STABLE_ITERS), 0):
        return False
    if not np.isfinite(prev_abs_residual) or prev_abs_residual <= 0.0:
        return False
    ratio = float(curr_abs_residual) / max(float(prev_abs_residual), 1.0e-30)
    if ratio > max(float(_state.CEXT_VESS_COUPLING_ANDERSON_GATE_RATIO), 0.0):
        return False
    omega_min, _ = _cext_relaxation_bounds()
    if float(omega_fallback) <= omega_min * max(float(_state.CEXT_VESS_COUPLING_ANDERSON_OMEGA_GATE_FACTOR), 1.0):
        return False
    return True


__all__ = ['_validate_cext_gpu_batch', '_default_cext_timing_details', '_maybe_trace_cext_iteration', '_cext_relaxation_bounds', '_clip_cext_omega', '_cext_residual_metrics', '_cext_source_state_delta_metrics', '_cext_active_source_cell_stats', '_cext_target_query_cells', '_cext_target_neighbor_metrics', '_cext_hybrid_local_target_ids', '_cext_build_active_components_from_cells', '_cext_component_source_ids_from_cells', '_cext_adaptive_aitken_omega', '_cext_project_candidate', '_cext_apply_trust_region', '_cext_should_enable_anderson']
