"""Direct CPU and GPU external-field evaluation.

Generated by a behavior-preserving extraction from the frozen TissueSim
baseline. Dependencies are bound by the temporary compatibility facade while
the new typed subsystem APIs replace the legacy global runtime contract.
"""

from __future__ import annotations

from cascade.configuration import _legacy_state as _state
from cascade.runtime import _dependencies

for _dependency_name, _dependency_value in vars(_dependencies).items():
    if not _dependency_name.startswith("__"):
        globals().setdefault(_dependency_name, _dependency_value)
del _dependency_name, _dependency_value

def _compute_cext_batch_cpu(
    context: dict,
    ext_state: dict,
    target_seg_ids: np.ndarray,
    row_ptr: np.ndarray,
    col_idx: np.ndarray,
) -> np.ndarray:
    gl_order = int(np.asarray(context["gl_points_si"]).shape[1])
    if target_seg_ids.size == 0:
        return np.zeros((0, gl_order), dtype=np.float32)
    if _state._HAVE_NUMBA and _state._compute_cext_batch_numba is not None:
        return _state._compute_cext_batch_numba(
            np.asarray(target_seg_ids, dtype=np.int32),
            np.asarray(row_ptr, dtype=np.int32),
            np.asarray(col_idx, dtype=np.int32),
            np.asarray(context["gl_points_si"], dtype=np.float32),
            np.asarray(context["midpoints_si"], dtype=np.float32),
            np.asarray(context["radii_si"], dtype=np.float32),
            np.asarray(ext_state["lambda_iv_gl"], dtype=np.float32),
            np.asarray(ext_state["q_weighted_gl"], dtype=np.float32),
            np.asarray(ext_state["seg_cap_gl"], dtype=np.float32),
            np.asarray(context["exclude_idx"], dtype=np.int32),
            np.asarray(context["exclude_count"], dtype=np.uint8),
            float(context["diffusivity_si"]),
            float(ext_state["window_factor"]),
        )

    out = np.zeros((int(target_seg_ids.size), gl_order), dtype=np.float32)
    radii_si = np.asarray(context["radii_si"], dtype=float)
    gl_points_si = np.asarray(context["gl_points_si"], dtype=float)
    midpoints_si = np.asarray(context["midpoints_si"], dtype=float)
    exclude_idx = np.asarray(context["exclude_idx"], dtype=np.int32)
    exclude_count = np.asarray(context["exclude_count"], dtype=np.uint8)
    lambda_iv_gl = np.asarray(ext_state["lambda_iv_gl"], dtype=float)
    q_weighted_gl = np.asarray(ext_state["q_weighted_gl"], dtype=float)
    seg_cap_gl = np.asarray(ext_state["seg_cap_gl"], dtype=float)
    diffusivity_si = float(context["diffusivity_si"])
    window_factor = float(ext_state["window_factor"])
    for batch_idx, target_seg in enumerate(np.asarray(target_seg_ids, dtype=np.int32)):
        target_i = int(target_seg)
        exclude_local = {
            int(v)
            for v in exclude_idx[target_i, : int(exclude_count[target_i])]
            if int(v) >= 0
        }
        for target_node in range(gl_order):
            target_point = gl_points_si[target_i, target_node]
            target_lambda = max(float(lambda_iv_gl[target_i, target_node]), 1e-30)
            total = 0.0
            cap_max = 0.0
            for pos in range(int(row_ptr[batch_idx]), int(row_ptr[batch_idx + 1])):
                source_i = int(col_idx[pos])
                if source_i in exclude_local:
                    continue
                radius_sum = float(radii_si[target_i] + radii_si[source_i])
                coarse_r = math.sqrt(float(np.dot(midpoints_si[source_i] - midpoints_si[target_i], midpoints_si[source_i] - midpoints_si[target_i])) + radius_sum * radius_sum)
                source_lambda_max = max(float(np.max(lambda_iv_gl[source_i])), 1e-30)
                coarse_lambda = max(target_lambda, source_lambda_max)
                if coarse_r > window_factor * coarse_lambda:
                    continue
                seg_cap = float(seg_cap_gl[source_i])
                seg_contributed = False
                for source_node in range(gl_order):
                    source_lambda = max(float(lambda_iv_gl[source_i, source_node]), 1e-30)
                    source_point = gl_points_si[source_i, source_node]
                    r = math.sqrt(float(np.dot(source_point - target_point, source_point - target_point)) + radius_sum * radius_sum)
                    if r > window_factor * source_lambda:
                        continue
                    r = max(r, 1e-30)
                    kernel = math.exp(-r / source_lambda) / (4.0 * math.pi * diffusivity_si * r)
                    total += float(q_weighted_gl[source_i, source_node]) * kernel
                    seg_contributed = True
                if seg_contributed:
                    cap_max = max(cap_max, seg_cap)
            if total < 0.0 or not np.isfinite(total):
                total = 0.0
            if cap_max > 0.0:
                total = min(total, cap_max)
            out[batch_idx, target_node] = np.float32(total)
    return out


def _ensure_cext_gpu_static(context: dict) -> dict:
    if _state._cp is None:
        raise RuntimeError("CuPy is not available.")
    static = context.get("gpu_static")
    if static is not None:
        return static
    static = {
        "gl_points_si": _state._cp.asarray(np.asarray(context["gl_points_si"], dtype=np.float32)),
        "midpoints_si": _state._cp.asarray(np.asarray(context["midpoints_si"], dtype=np.float32)),
        "segment_vectors": _state._cp.asarray(np.asarray(context["segment_vectors"], dtype=np.float32)),
        "radii_si": _state._cp.asarray(np.asarray(context["radii_si"], dtype=np.float32)),
        "lengths_si": _state._cp.asarray(np.asarray(context["lengths_si"], dtype=np.float32)),
        "ds_gl": _state._cp.asarray(np.asarray(context["ds_gl"], dtype=np.float32)),
        "gl_t": _state._cp.asarray(np.asarray(context["gl_t"], dtype=np.float32)),
        "flows_si": _state._cp.asarray(np.asarray(context["flows_si"], dtype=np.float32)),
        "parents": _state._cp.asarray(np.asarray(context["parents"], dtype=np.int32)),
        "level_order": _state._cp.asarray(np.asarray(context["level_order"], dtype=np.int32)),
        "level_offsets": _state._cp.asarray(np.asarray(context["level_offsets"], dtype=np.int32)),
        "exclude_idx": _state._cp.asarray(np.asarray(context["exclude_idx"], dtype=np.int32)),
        "exclude_count": _state._cp.asarray(np.asarray(context["exclude_count"], dtype=np.uint8)),
        "xs_lut": _state._cp.asarray(np.asarray(_state._KRATIO_XS, dtype=np.float32)),
        "ratio_lut": _state._cp.asarray(np.asarray(_state._KRATIO_YS, dtype=np.float32)),
        "reach_si": _state._cp.asarray(np.asarray(context["reach_si"], dtype=np.float32)),
        "gpu_direct_cell_ptr": _state._cp.asarray(np.asarray(context.get("gpu_direct_cell_ptr", np.zeros((1,), dtype=np.int32)), dtype=np.int32)),
        "gpu_direct_cell_seg_ids": _state._cp.asarray(np.asarray(context.get("gpu_direct_cell_seg_ids", np.zeros((0,), dtype=np.int32)), dtype=np.int32)),
        "all_target_seg_ids": _state._cp.arange(int(np.asarray(context["midpoints_si"]).shape[0]), dtype=_state._cp.int32),
    }
    context["gpu_static"] = static
    return static


def _ensure_cext_gpu_geometry_static(context: dict) -> dict:
    """Upload only geometry arrays needed by FFT helper kernels."""
    if _state._cp is None:
        raise RuntimeError("CuPy is not available.")
    static = context.get("gpu_geometry_static")
    if static is not None:
        return static
    static = {
        "gl_points_si": _state._cp.asarray(np.asarray(context["gl_points_si"], dtype=np.float32)),
        "segment_vectors": _state._cp.asarray(np.asarray(context["segment_vectors"], dtype=np.float32)),
    }
    context["gpu_geometry_static"] = static
    return static


def _context_uses_cext_gpu_direct(context: dict) -> bool:
    return bool(context.get("candidate_query_mode") == "gpu_direct")


def _compute_cext_batch_gpu_into(
    context: dict,
    batch: dict,
    lambda_iv_g,
    q_weighted_g,
    mono2_weight_g,
    dipole2_weight_g,
    seg_cap_g,
    c_ext_new_g,
) -> None:
    if _state._cp is None:
        raise RuntimeError("CuPy is not available.")
    static = _ensure_cext_gpu_static(context)
    kernel = _get_cext_gpu_kernel()
    gpu_batch = batch.get("gpu")
    if not isinstance(gpu_batch, dict):
        raise RuntimeError("Missing cached GPU candidate batch.")
    target_ids_g = gpu_batch["target_seg_ids"]
    row_ptr_g = gpu_batch["row_ptr"]
    col_idx_g = gpu_batch["col_idx"]
    gl_order = int(np.asarray(context["gl_points_si"]).shape[1])
    threads = 128
    blocks = (int(target_ids_g.size) * gl_order + threads - 1) // threads
    kernel(
        (blocks,),
        (threads,),
        (
            target_ids_g,
            row_ptr_g,
            col_idx_g,
            static["gl_points_si"].ravel(),
            static["midpoints_si"].ravel(),
            static["segment_vectors"].ravel(),
            static["radii_si"],
            lambda_iv_g.ravel(),
            q_weighted_g.ravel(),
            mono2_weight_g.ravel(),
            dipole2_weight_g.ravel(),
            seg_cap_g,
            static["exclude_idx"].ravel(),
            static["exclude_count"],
            np.int32(gl_order),
            np.int32(context["exclude_idx"].shape[1]),
            np.int32(target_ids_g.size),
            np.float32(context["diffusivity_si"]),
            np.float32(float(_state.CEXT_WINDOW_FACTOR)),
            c_ext_new_g.ravel(),
        ),
    )


def _compute_cext_direct_gpu(
    context: dict,
    ext_state: dict,
    *,
    source_plan: dict | None = None,
    target_plan: dict | None = None,
) -> tuple[np.ndarray, np.ndarray, float, float]:
    if _state._cp is None:
        raise RuntimeError("CuPy is not available.")
    static = _ensure_cext_gpu_static(context)
    kernel = _get_cext_gpu_direct_kernel()
    gl_order = int(np.asarray(context["gl_points_si"]).shape[1])
    nseg = int(np.asarray(context["gl_points_si"]).shape[0])
    plan = source_plan if isinstance(source_plan, dict) else None
    active_count = int(plan.get("active_count", nseg)) if plan is not None else nseg
    target_cfg = target_plan if isinstance(target_plan, dict) else None
    target_count = int(target_cfg.get("target_count", nseg)) if target_cfg is not None else nseg
    if active_count <= 0 or target_count <= 0:
        zeros = np.zeros(np.asarray(ext_state["c_ext_gl"], dtype=np.float32).shape, dtype=np.float32)
        return zeros, zeros.copy(), 0.0, 0.0

    t_transfer = perf_counter()
    lambda_iv_g = _state._cp.asarray(np.asarray(ext_state["lambda_iv_gl"], dtype=np.float32))
    q_weighted_g = _state._cp.asarray(np.asarray(ext_state["q_weighted_gl"], dtype=np.float32))
    mono2_weight_g = _state._cp.asarray(np.asarray(ext_state.get("mono2_weight_gl", np.zeros_like(ext_state["q_weighted_gl"])), dtype=np.float32))
    dipole2_weight_g = _state._cp.asarray(np.asarray(ext_state.get("dipole2_weight_gl", np.zeros_like(ext_state["q_weighted_gl"])), dtype=np.float32))
    seg_cap_g = _state._cp.asarray(np.asarray(ext_state["seg_cap_gl"], dtype=np.float32))
    c_ext_total_g = _state._cp.zeros((target_count, gl_order), dtype=_state._cp.float32)
    c_ext_cap_g = _state._cp.zeros((target_count, gl_order), dtype=_state._cp.float32)
    if plan is None or bool(plan.get("uses_static", False)):
        cell_ptr_g = static["gpu_direct_cell_ptr"]
        cell_seg_ids_g = static["gpu_direct_cell_seg_ids"]
    else:
        if "gpu_cell_ptr" not in plan:
            plan["gpu_cell_ptr"] = _state._cp.asarray(np.asarray(plan.get("cell_ptr", np.zeros((1,), dtype=np.int32)), dtype=np.int32))
            plan["gpu_cell_seg_ids"] = _state._cp.asarray(np.asarray(plan.get("cell_seg_ids", np.zeros((0,), dtype=np.int32)), dtype=np.int32))
        cell_ptr_g = plan["gpu_cell_ptr"]
        cell_seg_ids_g = plan["gpu_cell_seg_ids"]
    if target_cfg is None or bool(target_cfg.get("uses_static", False)):
        target_seg_ids = np.asarray(np.arange(nseg, dtype=np.int32), dtype=np.int32)
        target_seg_ids_g = static["all_target_seg_ids"]
    else:
        target_seg_ids = np.asarray(target_cfg.get("target_seg_ids", np.zeros((0,), dtype=np.int32)), dtype=np.int32)
        if "gpu_target_seg_ids" not in target_cfg:
            target_cfg["gpu_target_seg_ids"] = _state._cp.asarray(target_seg_ids, dtype=_state._cp.int32)
        target_seg_ids_g = target_cfg["gpu_target_seg_ids"]
    _state._cp.cuda.Stream.null.synchronize()
    transfer_total = perf_counter() - t_transfer

    cell_origin = np.asarray(context.get("gpu_direct_cell_origin", np.zeros((3,), dtype=np.int32)), dtype=np.int32)
    cell_dims = np.asarray(context.get("gpu_direct_cell_dims", np.zeros((3,), dtype=np.int32)), dtype=np.int32)
    threads = 128
    blocks = (target_count * gl_order + threads - 1) // threads
    t_kernel = perf_counter()
    kernel(
        (blocks,),
        (threads,),
        (
            target_seg_ids_g,
            static["gl_points_si"].ravel(),
            static["midpoints_si"].ravel(),
            static["segment_vectors"].ravel(),
            static["radii_si"],
            static["reach_si"],
            lambda_iv_g.ravel(),
            q_weighted_g.ravel(),
            mono2_weight_g.ravel(),
            dipole2_weight_g.ravel(),
            seg_cap_g,
            static["exclude_idx"].ravel(),
            static["exclude_count"],
            cell_ptr_g,
            cell_seg_ids_g,
            np.int32(cell_origin[0]),
            np.int32(cell_origin[1]),
            np.int32(cell_origin[2]),
            np.int32(cell_dims[0]),
            np.int32(cell_dims[1]),
            np.int32(cell_dims[2]),
            np.float32(float(context["cell_size"])),
            np.float32(float(context.get("max_reach_si", 0.0))),
            np.float32(max(float(_state.CEXT_APPROX_WINDOW_SCALE), 0.0)),
            np.int32(gl_order),
            np.int32(int(np.asarray(context["exclude_idx"]).shape[1])),
            np.int32(target_count),
            np.float32(float(context["diffusivity_si"])),
            np.float32(float(_state.CEXT_WINDOW_FACTOR)),
            c_ext_total_g.ravel(),
            c_ext_cap_g.ravel(),
        ),
    )
    _state._cp.cuda.Stream.null.synchronize()
    kernel_total = perf_counter() - t_kernel

    t_download = perf_counter()
    c_ext_total_local = _state._cp.asnumpy(c_ext_total_g)
    c_ext_cap_local = _state._cp.asnumpy(c_ext_cap_g)
    _state._cp.cuda.Stream.null.synchronize()
    transfer_total += perf_counter() - t_download
    c_ext_total = np.zeros(np.asarray(ext_state["c_ext_gl"], dtype=np.float32).shape, dtype=np.float32)
    c_ext_cap = np.zeros_like(c_ext_total)
    c_ext_total[np.asarray(target_seg_ids, dtype=np.int32)] = np.asarray(c_ext_total_local, dtype=np.float32)
    c_ext_cap[np.asarray(target_seg_ids, dtype=np.int32)] = np.asarray(c_ext_cap_local, dtype=np.float32)
    return c_ext_total, c_ext_cap, kernel_total, transfer_total


__all__ = ['_compute_cext_batch_cpu', '_ensure_cext_gpu_static', '_ensure_cext_gpu_geometry_static', '_context_uses_cext_gpu_direct', '_compute_cext_batch_gpu_into', '_compute_cext_direct_gpu']
