# Legacy symbol names are bound by the temporary TissueSim compatibility facade.
# ruff: noqa: F821
"""Coupled hybrid-FFT external-field solver.

Generated by a behavior-preserving extraction from the frozen TissueSim
baseline. Dependencies are bound by the temporary compatibility facade while
the new typed subsystem APIs replace the legacy global runtime contract.
"""

from __future__ import annotations

from cascade.configuration import _legacy_state as _state
from cascade.runtime import _dependencies

for _dependency_name, _dependency_value in vars(_dependencies).items():
    if not _dependency_name.startswith("__"):
        globals().setdefault(_dependency_name, _dependency_value)
del _dependency_name, _dependency_value

def _solve_channel_concentrations_topdown_ext_hybrid_bg(
    tree: _state.Tree,
    flows: np.ndarray,
    starts: np.ndarray,
    ends: np.ndarray,
    radii: np.ndarray,
    lengths: np.ndarray,
    *,
    inlet_concentration: float,
    diffusivity: float,
    vmax: float,
    km: float,
    fluid: str,
    network_topology: dict | None = None,
) -> Tuple[np.ndarray, np.ndarray]:
    # Mutable runtime state is centralized in configuration._legacy_state.
    solver_name = "network_ext_hybrid_bg" if network_topology is not None else "topdown_ext_hybrid_bg"
    if float(_state.CEXT_WINDOW_FACTOR) <= 0.0:
        if network_topology is not None:
            cin, cout, _, _ = solve_network_concentrations(
                starts,
                ends,
                radii,
                lengths,
                flows,
                network_topology["inlet_nodes"],
                network_topology.get("outlet_nodes"),
                inlet_concentration,
                fluid=fluid,
                prox_ids=network_topology["prox_ids"],
                dist_ids=network_topology["dist_ids"],
                diffusivity=diffusivity,
                vmax=vmax,
                km=km,
            )
            _state._LAST_CONCENTRATION_TIMINGS = _default_cext_timing_details(backend="disabled")
            return cin, cout
        cin, cout = _solve_channel_concentrations_topdown(
            tree,
            flows,
            inlet_concentration=inlet_concentration,
            diffusivity=diffusivity,
            vmax=vmax,
            km=km,
            fluid=fluid,
        )
        _state._LAST_CONCENTRATION_TIMINGS = _default_cext_timing_details(backend="disabled")
        return cin, cout

    nseg = int(np.asarray(flows).size) if network_topology is not None else int(getattr(tree, "segment_count", 0))
    if nseg <= 0:
        empty = np.empty((0,), dtype=float)
        return empty, empty

    if _state._cp is None:
        if network_topology is not None:
            raise RuntimeError("General network + FFT Cext requires a compatible CuPy/CUDA installation.")
        return _solve_channel_concentrations_topdown_ext(
            tree,
            flows,
            starts,
            ends,
            radii,
            lengths,
            inlet_concentration=inlet_concentration,
            diffusivity=diffusivity,
            vmax=vmax,
            km=km,
            fluid=fluid,
        )

    t_total = perf_counter()
    t_stage = t_total
    fluid_mode = (fluid or getattr(getattr(tree, "parameters", None), "fluid", None) or _state.ACTIVE_FLUID).lower()
    hct_context = None if network_topology is not None else _hematocrit_context_for_tree(tree)
    radii_arr = np.asarray(radii, dtype=float) if network_topology is not None else np.asarray(hct_context["radii"], dtype=float)
    flows_arr = np.asarray(flows, dtype=float)
    chb_max = np.zeros_like(radii_arr)
    hct_source = "none"
    if fluid_mode == "blood":
        if network_topology is not None:
            HT = np.asarray([tube_hematocrit(radius, hd=_state.HD_DISCHARGE) for radius in radii_arr], dtype=float)
            hct_source = "network-radius"
        else:
            cached_hct = _get_tree_hematocrit_cache(
                tree,
                nseg,
                model=_state.HEMATOCRIT_MODEL,
                flows=flows_arr,
            )
            if cached_hct is not None:
                HD, HT = cached_hct
                hct_source = "cache"
            else:
                HD, HT = compute_tree_hematocrit(
                    tree,
                    hd_root=_state.HD_DISCHARGE,
                    flows=flows_arr,
                    model=_state.HEMATOCRIT_MODEL,
                    order=np.asarray(hct_context["order"], dtype=np.int64),
                )
                _store_tree_hematocrit_cache(
                    tree,
                    HD,
                    HT,
                    model=_state.HEMATOCRIT_MODEL,
                    flows=flows_arr,
                    fixed_flow_bc=False,
                )
                hct_source = "computed"
        chb_max = np.asarray(HT, dtype=float) * float(_state.O2_CAP_PER_HCT)
    hct_setup_s = perf_counter() - t_stage

    t_stage = perf_counter()
    context = _build_cext_geometry_context(
        tree,
        flows_arr,
        starts,
        ends,
        radii,
        lengths,
        inlet_concentration=inlet_concentration,
        diffusivity=diffusivity,
        vmax=vmax,
        km=km,
        build_candidate_index=False,
        network_topology=network_topology,
    )
    context_build_s = perf_counter() - t_stage

    t_stage = perf_counter()
    backend = _resolve_cext_accel_mode()
    frozen_backend = _resolve_cext_frozen_accel_mode()
    if backend != "gpu":
        if network_topology is not None:
            raise RuntimeError("General network + FFT Cext requires the GPU Cext backend.")
        return _solve_channel_concentrations_topdown_ext(
            tree,
            flows,
            starts,
            ends,
            radii,
            lengths,
            inlet_concentration=inlet_concentration,
            diffusivity=diffusivity,
            vmax=vmax,
            km=km,
            fluid=fluid,
        )
    context["candidate_query_mode"] = "hybrid_bg"
    context["candidate_build_time_s"] = 0.0
    hybrid = _ensure_cext_hybrid_bg_context(context)
    cache_key = _cext_state_cache_key(
        fluid_mode=fluid_mode,
        inlet_concentration=float(inlet_concentration),
        diffusivity_si=float(diffusivity * _state.CM2_TO_M2),
        vmax=float(vmax),
        km=float(km),
    )
    ext_state = _initialize_cext_state(
        tree,
        cache_key=cache_key,
        nseg=nseg,
        inlet_concentration=float(inlet_concentration),
        vmax=float(vmax),
        km=float(km),
    )

    query_total = 0.0
    kernel_total = 0.0
    transfer_total = 0.0
    frozen_transfer_total = 0.0
    hybrid_deposit_total = 0.0
    hybrid_fft_total = 0.0
    hybrid_o2_total = 0.0
    hybrid_self_sub_total = 0.0
    hybrid_local_total = 0.0
    hybrid_sample_total = 0.0
    hybrid_bg_solver_mode = ""
    init_elapsed = 0.0
    init_kernel_total = 0.0
    init_transfer_total = 0.0
    init_frozen_transfer_total = 0.0
    init_frozen_kernel_total = 0.0
    init_cache_total = 0.0
    init_hybrid_call_total = 0.0
    iteration_cache_total = 0.0
    final_frozen_transfer_total = 0.0
    final_frozen_kernel_total = 0.0
    final_cache_total = 0.0
    final_source_state_total = 0.0
    init_performed = False
    completed_iters = 0
    max_delta_last = 0.0
    rel_residual_last = 0.0
    omega_last = _clip_cext_omega(_state.CEXT_VESS_COUPLING_OMEGA)
    accel_step_last = "picard"
    accel_rejections = 0
    accel_restarts = 0
    anderson_depth_used = 0
    init_mode = str(_state.CEXT_INIT_MODE or "zero").strip().lower()
    accel_mode = str(_state.CEXT_VESS_COUPLING_ACCEL or "none").strip().lower()
    if accel_mode not in ("none", "aitken", "anderson"):
        raise ValueError("--cext-vess-coupling-accel must be 'none', 'aitken', or 'anderson'.")
    if init_mode not in ("zero", "decoupled_greens"):
        raise ValueError("--cext-init-mode must be 'zero' or 'decoupled_greens'.")

    prev_residual_flat: np.ndarray | None = None
    prev_abs_residual = float("inf")
    stable_iters = 0
    anderson_g_history: list[np.ndarray] = []
    anderson_r_history: list[np.ndarray] = []
    best_c_ext_gl: np.ndarray | None = None
    best_max_delta = float("inf")
    best_rel_residual = float("inf")
    best_iter = 0
    best_stall_iters = 0
    best_seen_stop = False
    omega_floor, _omega_ceiling = _cext_relaxation_bounds()
    last_eval_c_ext_gl: np.ndarray | None = None
    last_eval_mapped_gl: np.ndarray | None = None
    last_eval_max_delta = float("inf")
    last_eval_omega = float(omega_last)
    step_rejections = 0

    active_set_enabled = bool(_state.CEXT_ACTIVE_SET_ENABLE) and bool(_state.CEXT_HYBRID_BG_ENABLE_SOURCE_FREEZING)
    if _resolve_cext_hybrid_bg_mode() == "fft" and bool(_state.CEXT_HYBRID_FFT_QUANTILE_BINS):
        active_set_enabled = False
    # The target-freezing path was designed for direct solves. In the hybrid
    # solver it adds large CPU neighbor scans but rarely freezes anything,
    # while local-target pruning already shrinks the expensive GPU correction.
    target_active_set_enabled = False
    # Earlier freezing was faster only when the map was already close. On large
    # hybrid runs it changed the operator too early and caused residual spikes.
    hybrid_active_set_start = max(int(_state.CEXT_ACTIVE_SET_START), 6)
    hybrid_active_set_stable_iters = max(int(_state.CEXT_ACTIVE_SET_STABLE_ITERS), 3)
    hybrid_freeze_resid_gate = max(
        10.0 * float(_state.CEXT_VESS_COUPLING_TOL),
        float(_state.CEXT_ACTIVE_SET_ABS_TOL),
    )
    active_source_mask = np.ones((nseg,), dtype=bool)
    active_source_stable_counts = np.zeros((nseg,), dtype=np.int16)
    active_freeze_events = 0
    active_refreshes = 0
    last_active_refresh_iter = 0
    active_source_count = int(nseg)
    frozen_source_count = 0
    active_source_plan: dict | None = None
    prev_source_c_ext_gl: np.ndarray | None = None
    prev_source_c_iv_gl: np.ndarray | None = None
    min_active_sources = max(
        1,
        int(_state.CEXT_ACTIVE_SET_MIN_ACTIVE_COUNT),
        int(math.ceil(max(float(_state.CEXT_ACTIVE_SET_MIN_ACTIVE_FRACTION), 0.0) * float(nseg))),
    )
    frozen_mass_grids_g = None
    frozen_phi_grids_g = None
    active_target_mask = np.ones((nseg,), dtype=bool)
    active_target_stable_counts = np.zeros((nseg,), dtype=np.int16)
    active_target_count = int(nseg)
    frozen_target_count = 0
    target_freeze_events = 0
    target_reactivations = 0
    active_component_count = 1
    largest_component_size = int(nseg)
    min_active_targets = max(1, int(_state.CEXT_TARGET_ACTIVE_SET_MIN_ACTIVE_COUNT))
    active_target_plan: dict | None = None
    target_mask_changed = False
    runtime_state = _ensure_cext_hybrid_bg_runtime_state(context, hybrid, ext_state)
    gpu_iteration_cache_enabled = (
        bool(_state.CEXT_HYBRID_GPU_ITERATION_CACHE)
        and str(_resolve_cext_hybrid_bg_mode()).strip().lower() == "fft"
        and not bool(active_set_enabled)
    )
    all_target_ids = np.arange(nseg, dtype=np.int32)
    setup_s = perf_counter() - t_stage

    if _state.SOLVER_TIMING_DETAILS:
        print(
            f"  Concentration {'network_ext_hybrid_bg' if network_topology is not None else 'topdown_ext_hybrid_bg'}: "
            f"nseg={nseg} fluid={fluid_mode} backend={backend} frozen={frozen_backend} gl_order={GL_ORDER_CEXT} "
            f"hct={hct_source} accel={accel_mode} active_set={'on' if active_set_enabled else 'off'} "
            f"wall={LUMEN_WALL_CLOSURE} o2_terms={FINITE_RADIUS_O2_TERMS} "
            f"cext_lambda={_normalize_cext_lambda_source()} "
            f"graetz_max_fp_iters={GRAETZ_MAX_FP_ITERS} tail_buffer_patch=enabled "
            f"grid={int(hybrid['grid_n'])} bins={int(hybrid['lambda_bins'])} "
            f"bg_mode={_resolve_cext_hybrid_bg_mode()} "
            f"bg_solver={_resolve_cext_hybrid_bg_solver_mode()} "
            f"near={float(hybrid['near_radius_si']):.3e}"
        )

    if init_mode == "decoupled_greens":
        t_init = perf_counter()
        cin_seg, cout_seg, c_iv_gl, frozen_backend, init_frozen_transfer = _run_topdown_ext_frozen_step(
            context,
            ext_state,
            inlet_concentration=float(inlet_concentration),
            vmax=float(vmax),
            km=float(km),
            chb_max=np.asarray(chb_max, dtype=np.float32),
            fluid_mode=fluid_mode,
            frozen_backend=frozen_backend,
        )
        init_frozen_timings = dict(_state._LAST_CEXT_FROZEN_STEP_TIMINGS)
        ext_state["cin_seg"] = cin_seg
        ext_state["cout_seg"] = cout_seg
        ext_state["c_iv_gl"] = np.asarray(c_iv_gl, dtype=np.float32)
        t_cache = perf_counter()
        if gpu_iteration_cache_enabled:
            _build_cext_iteration_cache_gpu(context, ext_state, runtime_state)
        else:
            _build_cext_iteration_cache(context, ext_state)
        init_cache_total += perf_counter() - t_cache
        _cext_hybrid_init_lambda_bins(hybrid, ext_state)
        if not gpu_iteration_cache_enabled:
            _sync_cext_hybrid_bg_runtime_state(ext_state, runtime_state)
        t_hybrid = perf_counter()
        c_ext_new, hybrid_timings = _compute_cext_hybrid_bg_gpu(
            context,
            ext_state,
            hybrid,
            active_source_plan=active_source_plan,
            target_plan=active_target_plan,
            runtime_state=runtime_state,
        )
        init_hybrid_call_total += perf_counter() - t_hybrid
        ext_state["c_ext_gl"] = np.asarray(c_ext_new, dtype=np.float32)
        runtime_state["c_ext_gl"].set(np.asarray(ext_state["c_ext_gl"], dtype=np.float32))
        hybrid_bg_solver_mode = str(hybrid_timings.get("bg_solver_mode", hybrid_bg_solver_mode or _resolve_cext_hybrid_bg_solver_mode()))
        init_elapsed = perf_counter() - t_init
        init_kernel_total = (
            float(hybrid_timings.get("deposit_s", 0.0))
            + float(hybrid_timings.get("fft_s", 0.0))
            + float(hybrid_timings.get("fft_o2_terms_s", 0.0))
            + float(hybrid_timings.get("fft_discrete_self_subtract_s", 0.0))
            + float(hybrid_timings.get("local_corr_s", 0.0))
            + float(hybrid_timings.get("sample_s", 0.0))
        )
        init_transfer_total = float(hybrid_timings.get("transfer_s", 0.0))
        init_frozen_transfer_total = float(init_frozen_transfer)
        init_frozen_kernel_total = float(init_frozen_timings.get("kernel_s", 0.0))
        init_performed = True
        if _state.SOLVER_TIMING_DETAILS:
            print(
                "    Cext init predictor: "
                f"max_cext={float(np.nanmax(np.asarray(ext_state['c_ext_gl'], dtype=float))) if ext_state['c_ext_gl'].size else 0.0:.3e}"
            )
        _maybe_trace_cext_iteration(0, ext_state, solver=solver_name, context=context, backend=backend)

    if not init_performed:
        _maybe_trace_cext_iteration(0, ext_state, solver=solver_name, context=context, backend=backend)

    for iter_idx in range(1, int(_state.CEXT_VESS_COUPLING_MAX_ITER) + 1):
        cin_seg, cout_seg, c_iv_gl, frozen_backend, frozen_transfer = _run_topdown_ext_frozen_step(
            context,
            ext_state,
            inlet_concentration=float(inlet_concentration),
            vmax=float(vmax),
            km=float(km),
            chb_max=np.asarray(chb_max, dtype=np.float32),
            fluid_mode=fluid_mode,
            frozen_backend=frozen_backend,
        )
        frozen_transfer_total += float(frozen_transfer)
        ext_state["cin_seg"] = cin_seg
        ext_state["cout_seg"] = cout_seg
        ext_state["c_iv_gl"] = np.asarray(c_iv_gl, dtype=np.float32)
        t_iter_cache = perf_counter()
        if gpu_iteration_cache_enabled:
            _build_cext_iteration_cache_gpu(context, ext_state, runtime_state)
        else:
            _build_cext_iteration_cache(context, ext_state)
        iteration_cache_total += perf_counter() - t_iter_cache
        _cext_hybrid_init_lambda_bins(hybrid, ext_state)
        source_c_ext_snapshot = np.asarray(ext_state["c_ext_gl"], dtype=np.float32).copy()
        source_c_iv_snapshot = np.asarray(ext_state["c_iv_gl"], dtype=np.float32).copy()
        current_c_ext_gl = np.asarray(ext_state["c_ext_gl"], dtype=np.float32)
        if not gpu_iteration_cache_enabled:
            _sync_cext_hybrid_bg_runtime_state(ext_state, runtime_state)

        refresh_due = False
        source_abs_delta = np.zeros((nseg,), dtype=np.float32)
        source_rel_delta = np.zeros((nseg,), dtype=np.float32)
        if active_set_enabled:
            source_abs_delta, source_rel_delta = _cext_source_state_delta_metrics(
                prev_source_c_ext_gl,
                prev_source_c_iv_gl,
                source_c_ext_snapshot,
                source_c_iv_snapshot,
            )
            active_mask_now = np.asarray(active_source_mask, dtype=bool)
            stable_local = np.asarray(
                (source_abs_delta <= float(_state.CEXT_ACTIVE_SET_ABS_TOL)) | (source_rel_delta <= float(_state.CEXT_ACTIVE_SET_REL_TOL)),
                dtype=bool,
            )
            active_source_stable_counts[active_mask_now & stable_local] += np.int16(1)
            active_source_stable_counts[active_mask_now & ~stable_local] = np.int16(0)

            freeze_now = np.zeros((nseg,), dtype=bool)
            global_freeze_ready = (
                np.isfinite(prev_abs_residual)
                and float(prev_abs_residual) <= float(hybrid_freeze_resid_gate)
            )
            if iter_idx >= int(hybrid_active_set_start) and global_freeze_ready:
                eligible = active_mask_now & (active_source_stable_counts >= int(hybrid_active_set_stable_iters))
                max_freeze = max(int(np.count_nonzero(active_mask_now)) - int(min_active_sources), 0)
                eligible_ids = np.flatnonzero(eligible)
                if max_freeze > 0 and eligible_ids.size > 0:
                    if eligible_ids.size > max_freeze:
                        rank_key = np.asarray(source_rel_delta[eligible_ids], dtype=np.float32)
                        keep_order = np.argsort(rank_key, kind="stable")[:max_freeze]
                        eligible_ids = np.asarray(eligible_ids[keep_order], dtype=np.int64)
                    freeze_now[np.asarray(eligible_ids, dtype=np.int64)] = True
                    active_source_mask[freeze_now] = False
                    active_source_stable_counts[freeze_now] = np.int16(0)
                    active_freeze_events += int(np.count_nonzero(freeze_now))
                    active_source_plan = None
            active_source_count = int(np.count_nonzero(active_source_mask))
            frozen_source_count = int(nseg - active_source_count)
            refresh_period = max(int(_state.CEXT_ACTIVE_SET_REFRESH_PERIOD), 0)
            if frozen_source_count > 0 and refresh_period > 0 and (iter_idx - last_active_refresh_iter) >= refresh_period:
                refresh_due = True
            if frozen_source_count > 0 and (np.any(freeze_now) or refresh_due):
                frozen_mass_grids_g, frozen_phi_grids_g, frozen_timings = _rebuild_cext_hybrid_frozen_cache(
                    context,
                    ext_state,
                    hybrid,
                    ~active_source_mask,
                    runtime_state=runtime_state,
                )
                hybrid_deposit_total += float(frozen_timings.get("deposit_s", 0.0))
                hybrid_fft_total += float(frozen_timings.get("fft_s", 0.0))
                hybrid_bg_solver_mode = str(frozen_timings.get("bg_solver_mode", hybrid_bg_solver_mode or _resolve_cext_hybrid_bg_solver_mode()))
                active_refreshes += 1
                last_active_refresh_iter = int(iter_idx)
            elif frozen_source_count <= 0:
                frozen_mass_grids_g = None
                frozen_phi_grids_g = None
                active_source_plan = None
            if active_source_count < nseg and active_source_plan is None:
                active_source_plan = _build_cext_hybrid_local_source_plan(hybrid, active_source_mask)
        else:
            active_source_count = int(nseg)
            frozen_source_count = 0
            active_source_plan = None
            frozen_mass_grids_g = None
            frozen_phi_grids_g = None

        source_cell_stats = _cext_active_source_cell_stats(
            context,
            active_source_mask,
            source_abs_delta,
            source_rel_delta,
        ) if target_active_set_enabled else {"cell_count": int(context.get("gpu_direct_n_cells", 0))}

        if target_active_set_enabled and frozen_target_count > 0:
            frozen_target_ids = np.flatnonzero(~active_target_mask).astype(np.int32, copy=False)
            if frozen_target_ids.size > 0:
                neighbor_counts_frozen, neighbor_abs_frozen, neighbor_rel_frozen, _ = _cext_target_neighbor_metrics(
                    context,
                    frozen_target_ids,
                    source_cell_stats,
                    neighbor_pad=int(_state.CEXT_TARGET_ACTIVE_SET_NEIGHBOR_PAD),
                )
                reactivate = (neighbor_counts_frozen > 0) & (
                    (neighbor_abs_frozen > float(_state.CEXT_TARGET_ACTIVE_SET_ABS_TOL))
                    | (neighbor_rel_frozen > float(_state.CEXT_TARGET_ACTIVE_SET_REL_TOL))
                )
                if np.any(reactivate):
                    reactivate_ids = np.asarray(frozen_target_ids[np.asarray(reactivate, dtype=bool)], dtype=np.int32)
                    active_target_mask[reactivate_ids] = True
                    active_target_stable_counts[reactivate_ids] = np.int16(0)
                    target_reactivations += int(reactivate_ids.size)
                    active_target_plan = None
                    target_mask_changed = True

        if target_active_set_enabled:
            active_target_count = int(np.count_nonzero(active_target_mask))
            frozen_target_count = int(nseg - active_target_count)
            active_target_ids = np.flatnonzero(active_target_mask).astype(np.int32, copy=False)
        else:
            active_target_count = int(nseg)
            frozen_target_count = 0
            active_target_ids = all_target_ids
        active_component_count = 1 if active_target_count > 0 else 0
        largest_component_size = int(active_target_count)
        if active_target_ids.size <= 0:
            max_delta_last = 0.0
            rel_residual_last = 0.0
            accel_step_last = "picard"
            omega_last = _clip_cext_omega(_state.CEXT_VESS_COUPLING_OMEGA)
            stable_iters = 0
            completed_iters = iter_idx
            prev_source_c_ext_gl = source_c_ext_snapshot
            prev_source_c_iv_gl = source_c_iv_snapshot
            prev_residual_flat = None
            prev_abs_residual = float("inf")
            anderson_g_history = []
            anderson_r_history = []
            break

        if active_target_plan is None:
            active_target_plan = None if active_target_count >= nseg else _build_cext_gpu_direct_target_plan(context, active_target_ids)

        if target_mask_changed:
            prev_residual_flat = None
            prev_abs_residual = float("inf")
            stable_iters = 0
            anderson_g_history = []
            anderson_r_history = []
            accel_rejections = 0
            accel_restarts = 0
            anderson_depth_used = 0
            target_mask_changed = False

        local_target_ids = active_target_ids
        local_target_positions = None
        local_target_plan = active_target_plan
        if active_set_enabled and active_source_count < nseg and active_target_ids.size > 0:
            local_target_ids = _cext_hybrid_local_target_ids(
                context,
                hybrid,
                active_target_ids,
                active_source_mask,
            )
            if local_target_ids.size != active_target_ids.size:
                local_target_positions = np.searchsorted(active_target_ids, local_target_ids).astype(np.int32, copy=False)
                local_target_plan = _build_cext_gpu_direct_target_plan(context, local_target_ids)

        c_ext_new, hybrid_timings = _compute_cext_hybrid_bg_gpu(
            context,
            ext_state,
            hybrid,
            active_source_mask=active_source_mask if active_set_enabled else None,
            active_source_plan=active_source_plan,
            target_plan=active_target_plan,
            local_target_plan=local_target_plan,
            local_target_positions=local_target_positions,
            runtime_state=runtime_state,
            frozen_mass_grids_g=frozen_mass_grids_g,
            frozen_phi_grids_g=frozen_phi_grids_g,
        )
        hybrid_deposit_total += float(hybrid_timings.get("deposit_s", 0.0))
        hybrid_fft_total += float(hybrid_timings.get("fft_s", 0.0))
        hybrid_o2_total += float(hybrid_timings.get("fft_o2_terms_s", 0.0))
        hybrid_self_sub_total += float(hybrid_timings.get("fft_discrete_self_subtract_s", 0.0))
        hybrid_local_total += float(hybrid_timings.get("local_corr_s", 0.0))
        hybrid_sample_total += float(hybrid_timings.get("sample_s", 0.0))
        hybrid_bg_solver_mode = str(hybrid_timings.get("bg_solver_mode", hybrid_bg_solver_mode or _resolve_cext_hybrid_bg_solver_mode()))
        transfer_total += float(hybrid_timings.get("transfer_s", 0.0))
        kernel_total += (
            float(hybrid_timings.get("fft_s", 0.0))
            + float(hybrid_timings.get("fft_o2_terms_s", 0.0))
            + float(hybrid_timings.get("fft_discrete_self_subtract_s", 0.0))
            + float(hybrid_timings.get("local_corr_s", 0.0))
            + float(hybrid_timings.get("sample_s", 0.0))
        )

        current_target_gl = np.asarray(current_c_ext_gl if active_target_count >= nseg else current_c_ext_gl[active_target_ids], dtype=np.float32)
        accel_state_in = {
            "prev_residual_flat": prev_residual_flat,
            "prev_abs_residual": prev_abs_residual,
            "stable_iters": stable_iters,
            "anderson_g_history": anderson_g_history,
            "anderson_r_history": anderson_r_history,
            "accel_rejections": accel_rejections,
            "accel_restarts": accel_restarts,
            "anderson_depth_used": anderson_depth_used,
            "omega_last": omega_last,
            "iter_count": completed_iters,
        }
        candidate_flat, accel_state, accel_metrics = _cext_apply_component_acceleration(
            current_target_gl.reshape(-1),
            np.asarray(c_ext_new, dtype=np.float32).reshape(-1),
            accel_state_in,
            accel_mode=accel_mode,
        )
        if active_target_count >= nseg:
            candidate_c_ext_gl = np.asarray(candidate_flat.reshape(current_target_gl.shape), dtype=np.float32)
            mapped_c_ext_gl = np.asarray(c_ext_new, dtype=np.float32).reshape(current_target_gl.shape).copy()
        else:
            candidate_c_ext_gl = np.asarray(current_c_ext_gl, dtype=np.float32).copy()
            candidate_c_ext_gl[active_target_ids] = np.asarray(candidate_flat.reshape(current_target_gl.shape), dtype=np.float32)
            mapped_c_ext_gl = np.asarray(current_c_ext_gl, dtype=np.float32).copy()
            mapped_c_ext_gl[active_target_ids] = np.asarray(c_ext_new, dtype=np.float32).reshape(current_target_gl.shape)

        comp_abs = np.max(np.abs(np.asarray(c_ext_new, dtype=np.float32) - current_target_gl), axis=1)
        comp_scale = np.maximum.reduce(
            [
                np.max(np.abs(np.asarray(c_ext_new, dtype=np.float32)), axis=1),
                np.max(np.abs(current_target_gl), axis=1),
                np.full((active_target_ids.size,), float(_state.VESS_CONC_FLOOR), dtype=np.float32),
            ]
        )
        comp_rel = np.divide(
            np.asarray(comp_abs, dtype=np.float32),
            np.maximum(comp_scale, np.float32(_state.VESS_CONC_FLOOR)),
            out=np.zeros_like(np.asarray(comp_abs, dtype=np.float32)),
            where=np.maximum(comp_scale, np.float32(_state.VESS_CONC_FLOOR)) > 0.0,
        )

        if target_active_set_enabled and active_target_ids.size > 0:
            target_abs_delta_field = np.zeros((nseg,), dtype=np.float32)
            target_rel_delta_field = np.zeros((nseg,), dtype=np.float32)
            target_abs_delta_field[active_target_ids] = np.asarray(comp_abs, dtype=np.float32)
            target_rel_delta_field[active_target_ids] = np.asarray(comp_rel, dtype=np.float32)
            stable_target_local = (
                (target_abs_delta_field[active_target_ids] <= float(_state.CEXT_TARGET_ACTIVE_SET_ABS_TOL))
                | (target_rel_delta_field[active_target_ids] <= float(_state.CEXT_TARGET_ACTIVE_SET_REL_TOL))
            )
            active_target_stable_counts[active_target_ids[np.asarray(stable_target_local, dtype=bool)]] += np.int16(1)
            active_target_stable_counts[active_target_ids[~np.asarray(stable_target_local, dtype=bool)]] = np.int16(0)

            if iter_idx >= max(int(_state.CEXT_TARGET_ACTIVE_SET_START), 1):
                eligible_target_ids = np.asarray(
                    active_target_ids[
                        active_target_stable_counts[active_target_ids] >= max(int(_state.CEXT_TARGET_ACTIVE_SET_STABLE_ITERS), 1)
                    ],
                    dtype=np.int32,
                )
                max_target_freeze = max(int(np.count_nonzero(active_target_mask)) - int(min_active_targets), 0)
                if max_target_freeze > 0 and eligible_target_ids.size > 0:
                    neighbor_counts_t, neighbor_abs_t, neighbor_rel_t, _ = _cext_target_neighbor_metrics(
                        context,
                        eligible_target_ids,
                        source_cell_stats,
                        neighbor_pad=int(_state.CEXT_TARGET_ACTIVE_SET_NEIGHBOR_PAD),
                    )
                    can_freeze = (neighbor_counts_t <= 0) | (
                        (neighbor_abs_t <= float(_state.CEXT_TARGET_ACTIVE_SET_ABS_TOL))
                        & (neighbor_rel_t <= float(_state.CEXT_TARGET_ACTIVE_SET_REL_TOL))
                    )
                    freeze_target_ids = np.asarray(eligible_target_ids[np.asarray(can_freeze, dtype=bool)], dtype=np.int32)
                    if freeze_target_ids.size > max_target_freeze:
                        rank_key = np.asarray(target_rel_delta_field[freeze_target_ids], dtype=np.float32)
                        keep_order = np.argsort(rank_key, kind="stable")[:max_target_freeze]
                        freeze_target_ids = np.asarray(freeze_target_ids[keep_order], dtype=np.int32)
                    if freeze_target_ids.size > 0:
                        active_target_mask[freeze_target_ids] = False
                        active_target_stable_counts[freeze_target_ids] = np.int16(0)
                        target_freeze_events += int(freeze_target_ids.size)
                        active_target_plan = None
                        target_mask_changed = True

        ext_state["c_ext_gl"] = np.asarray(candidate_c_ext_gl, dtype=np.float32)
        runtime_state["c_ext_gl"].set(np.asarray(ext_state["c_ext_gl"], dtype=np.float32))
        completed_iters = iter_idx
        prev_source_c_ext_gl = source_c_ext_snapshot
        prev_source_c_iv_gl = source_c_iv_snapshot
        prev_residual_val = accel_state["prev_residual_flat"]
        prev_residual_flat = None if prev_residual_val is None else np.asarray(prev_residual_val, dtype=np.float32).copy()
        prev_abs_residual = float(accel_state["prev_abs_residual"])
        stable_iters = int(accel_state["stable_iters"])
        anderson_g_history = [np.asarray(arr, dtype=np.float32).copy() for arr in accel_state["anderson_g_history"]]
        anderson_r_history = [np.asarray(arr, dtype=np.float32).copy() for arr in accel_state["anderson_r_history"]]
        accel_rejections = int(accel_metrics["accel_rejections"])
        accel_restarts = int(accel_metrics["accel_restarts"])
        anderson_depth_used = int(accel_metrics["anderson_depth_used"])
        omega_last = float(accel_metrics["omega_last"])
        accel_step_last = str(accel_metrics["accel_step_last"])
        max_delta_last = float(accel_metrics["max_delta_last"])
        rel_residual_last = float(accel_metrics["rel_residual_last"])
        step_rejected = False
        if (
            last_eval_c_ext_gl is not None
            and last_eval_mapped_gl is not None
            and np.isfinite(last_eval_max_delta)
            and max_delta_last
            > max(float(last_eval_max_delta) * max(float(_state.CEXT_VESS_COUPLING_STEP_REJECT_FACTOR), 1.0), float(last_eval_max_delta) + 0.05 * float(_state.CEXT_VESS_COUPLING_TOL))
        ):
            retry_omega = max(
                float(omega_floor),
                min(float(last_eval_omega), float(last_eval_omega) * max(float(_state.CEXT_VESS_COUPLING_STEP_RETRY_FACTOR), 0.0)),
            )
            retry_candidate = np.asarray(last_eval_c_ext_gl, dtype=np.float32) + np.float32(retry_omega) * (
                np.asarray(last_eval_mapped_gl, dtype=np.float32) - np.asarray(last_eval_c_ext_gl, dtype=np.float32)
            )
            trusted_retry = _cext_apply_trust_region(
                np.asarray(last_eval_c_ext_gl, dtype=np.float32).reshape(-1),
                np.asarray(retry_candidate, dtype=np.float32).reshape(-1),
                np.asarray(last_eval_mapped_gl, dtype=np.float32).reshape(-1),
            )
            if trusted_retry is not None:
                retry_candidate = np.asarray(trusted_retry, dtype=np.float32).reshape(np.asarray(last_eval_c_ext_gl).shape)
            candidate_c_ext_gl = np.asarray(retry_candidate, dtype=np.float32)
            step_rejected = True
            step_rejections += 1
            accel_rejections += 1
            accel_restarts += 1
            prev_residual_flat = None
            prev_abs_residual = float("inf")
            stable_iters = 0
            anderson_g_history = []
            anderson_r_history = []
            omega_last = float(retry_omega)
            last_eval_omega = float(retry_omega)
            accel_step_last = "reject_retry"
            if _state.SOLVER_TIMING_DETAILS:
                print(
                    "    Cext residual rejected: "
                    f"bad_max_delta={max_delta_last:.3e} prior_max_delta={last_eval_max_delta:.3e} "
                    f"retry_omega={retry_omega:.3f}"
                )
        if not step_rejected:
            last_eval_c_ext_gl = np.asarray(current_c_ext_gl, dtype=np.float32).copy()
            last_eval_mapped_gl = np.asarray(mapped_c_ext_gl, dtype=np.float32).copy()
            last_eval_max_delta = float(max_delta_last)
            last_eval_omega = max(float(omega_last), float(omega_floor))
        else:
            ext_state["c_ext_gl"] = np.asarray(candidate_c_ext_gl, dtype=np.float32)
            runtime_state["c_ext_gl"].set(np.asarray(ext_state["c_ext_gl"], dtype=np.float32))
        active_target_count = int(np.count_nonzero(active_target_mask))
        frozen_target_count = int(nseg - active_target_count)
        active_component_count = 1 if active_target_count > 0 else 0
        largest_component_size = int(active_target_count)
        if (
            active_set_enabled
            and frozen_source_count > 0
            and max_delta_last > max(4.0 * float(hybrid_freeze_resid_gate), 2.0 * float(hybrid_freeze_resid_gate + 1e-30))
        ):
            active_source_mask[:] = True
            active_source_stable_counts[:] = np.int16(0)
            active_source_count = int(nseg)
            frozen_source_count = 0
            frozen_mass_grids_g = None
            frozen_phi_grids_g = None
            active_source_plan = None
            prev_residual_flat = None
            prev_abs_residual = float("inf")
            stable_iters = 0
            anderson_g_history = []
            anderson_r_history = []
            accel_step_last = "freeze_rollback"
            if _state.SOLVER_TIMING_DETAILS:
                print(
                    "    Cext active source freeze rolled back: "
                    f"max_delta={max_delta_last:.3e} gate={hybrid_freeze_resid_gate:.3e}"
                )

        improved_best = bool(
            (not step_rejected)
            and np.isfinite(max_delta_last)
            and (
                best_c_ext_gl is None
                or max_delta_last < best_max_delta * (1.0 - 1.0e-4)
                or max_delta_last < best_max_delta - max(0.01 * float(_state.CEXT_VESS_COUPLING_TOL), 1.0e-12)
            )
        )
        if improved_best:
            # max_delta is the residual of current_c_ext_gl -> F(current_c_ext_gl),
            # so rollback must preserve current_c_ext_gl, not the relaxed candidate.
            best_c_ext_gl = np.asarray(current_c_ext_gl, dtype=np.float32).copy()
            best_max_delta = float(max_delta_last)
            best_rel_residual = float(rel_residual_last)
            best_iter = int(iter_idx)
            best_stall_iters = 0
        elif best_c_ext_gl is not None and np.isfinite(best_max_delta):
            if max_delta_last >= best_max_delta or omega_last <= float(omega_floor) * 1.001:
                best_stall_iters += 1
            else:
                best_stall_iters = max(best_stall_iters - 1, 0)

        stop_on_best_seen = False
        if best_c_ext_gl is not None and int(_state.CEXT_VESS_COUPLING_BEST_STALL_ITERS) > 0:
            revert_factor = max(float(_state.CEXT_VESS_COUPLING_BEST_REVERT_FACTOR), 1.0)
            stalled_long_enough = best_stall_iters >= max(int(_state.CEXT_VESS_COUPLING_BEST_STALL_ITERS), 1)
            worse_than_best = max_delta_last >= best_max_delta * revert_factor
            floor_stalled = omega_last <= float(omega_floor) * 1.001 and max_delta_last >= best_max_delta
            if stalled_long_enough and (worse_than_best or floor_stalled):
                # The nonlinear map has stopped improving and relaxation has
                # collapsed or the residual is walking uphill. Keep the best
                # fixed-point iterate seen so far instead of spending the rest
                # of the run moving away from it.
                ext_state["c_ext_gl"] = np.asarray(best_c_ext_gl, dtype=np.float32).copy()
                runtime_state["c_ext_gl"].set(np.asarray(ext_state["c_ext_gl"], dtype=np.float32))
                max_delta_last = float(best_max_delta)
                rel_residual_last = float(best_rel_residual)
                accel_step_last = "best_seen_stop"
                best_seen_stop = True
                stop_on_best_seen = True
                prev_residual_flat = None
                prev_abs_residual = float("inf")
                stable_iters = 0
                anderson_g_history = []
                anderson_r_history = []
                if _state.SOLVER_TIMING_DETAILS:
                    print(
                        "    Cext best-seen stop: "
                        f"reverted_to_iter={best_iter} best_max_delta={best_max_delta:.3e} "
                        f"stall_iters={best_stall_iters} omega_floor={float(omega_floor):.3f}"
                    )

        _maybe_trace_cext_iteration(
            iter_idx,
            ext_state,
            solver=solver_name,
            context=context,
            backend=backend,
            max_delta=max_delta_last,
            rel_residual=rel_residual_last,
        )

        if _state.SOLVER_TIMING_DETAILS:
            print(
                f"    Cext iter {iter_idx}/{int(CEXT_VESS_COUPLING_MAX_ITER)}: "
                f"max_delta={max_delta_last:.3e} rel={rel_residual_last:.3e} "
                f"step={accel_step_last} omega={omega_last:.3f} stable={stable_iters} "
                f"active_src={active_source_count} frozen_src={frozen_source_count} "
                f"active_tgt={active_target_count} frozen_tgt={frozen_target_count} "
                f"local_tgt={int(hybrid_timings.get('local_target_count', active_target_count))}"
            )
        if stop_on_best_seen:
            break
        if max_delta_last < float(_state.CEXT_VESS_COUPLING_TOL):
            break
        if float(_state.CEXT_VESS_COUPLING_REL_TOL) > 0.0 and rel_residual_last < float(_state.CEXT_VESS_COUPLING_REL_TOL):
            break

    # Recompute intravascular quadrature values against the final relaxed Cext
    # field, then cache q_line = k_if * (Civ - Cext) for the final tissue solve.
    cin_seg, cout_seg, c_iv_gl, frozen_backend, final_frozen_transfer = _run_topdown_ext_frozen_step(
        context,
        ext_state,
        inlet_concentration=float(inlet_concentration),
        vmax=float(vmax),
        km=float(km),
        chb_max=np.asarray(chb_max, dtype=np.float32),
        fluid_mode=fluid_mode,
        frozen_backend=frozen_backend,
    )
    final_frozen_timings = dict(_state._LAST_CEXT_FROZEN_STEP_TIMINGS)
    frozen_transfer_total += float(final_frozen_transfer)
    final_frozen_transfer_total = float(final_frozen_transfer)
    final_frozen_kernel_total = float(final_frozen_timings.get("kernel_s", 0.0))
    ext_state["cin_seg"] = np.asarray(cin_seg, dtype=np.float32)
    ext_state["cout_seg"] = np.asarray(cout_seg, dtype=np.float32)
    ext_state["c_iv_gl"] = np.asarray(c_iv_gl, dtype=np.float32)
    t_cache = perf_counter()
    _build_cext_iteration_cache(context, ext_state)
    final_cache_total = perf_counter() - t_cache
    t_source_state = perf_counter()
    _set_last_cext_source_state(
        context,
        ext_state,
        solver=solver_name,
        backend=backend,
    )
    final_source_state_total = perf_counter() - t_source_state

    total_elapsed = perf_counter() - t_total
    _state._LAST_CONCENTRATION_TIMINGS = {
        "backend": backend,
        "t_cext_total_s": float(total_elapsed),
        "t_cext_hct_setup_s": float(hct_setup_s),
        "t_cext_context_build_s": float(context_build_s),
        "t_cext_solver_setup_s": float(setup_s),
        "t_cext_query_s": float(query_total),
        "t_cext_kernel_s": float(kernel_total),
        "t_cext_gpu_transfer_s": float(transfer_total),
        "t_cext_frozen_gpu_transfer_s": float(frozen_transfer_total),
        "t_cext_init_s": float(init_elapsed),
        "t_cext_init_kernel_s": float(init_kernel_total),
        "t_cext_init_gpu_transfer_s": float(init_transfer_total),
        "t_cext_init_frozen_gpu_transfer_s": float(init_frozen_transfer_total),
        "t_cext_init_frozen_kernel_s": float(init_frozen_kernel_total),
        "t_cext_init_cache_s": float(init_cache_total),
        "t_cext_init_hybrid_call_s": float(init_hybrid_call_total),
        "t_cext_iteration_cache_s": float(iteration_cache_total),
        "t_cext_final_frozen_gpu_transfer_s": float(final_frozen_transfer_total),
        "t_cext_final_frozen_kernel_s": float(final_frozen_kernel_total),
        "t_cext_final_cache_s": float(final_cache_total),
        "t_cext_final_source_state_s": float(final_source_state_total),
        "t_cext_hybrid_deposit_s": float(hybrid_deposit_total),
        "t_cext_hybrid_fft_s": float(hybrid_fft_total),
        "t_cext_hybrid_o2_terms_s": float(hybrid_o2_total),
        "t_cext_hybrid_self_subtract_s": float(hybrid_self_sub_total),
        "t_cext_hybrid_local_corr_s": float(hybrid_local_total),
        "t_cext_hybrid_sample_s": float(hybrid_sample_total),
        "cext_hybrid_bg_solver": str(hybrid_bg_solver_mode),
        "cext_init_mode": init_mode,
        "cext_init_performed": bool(init_performed),
        "cext_outer_iterations_completed": int(completed_iters),
        "cext_total_iterations_effective": int(completed_iters + (1 if init_performed else 0)),
        "cext_accel_mode": accel_mode,
        "cext_accel_step_last": accel_step_last,
        "cext_accel_rejections": int(accel_rejections),
        "cext_accel_restarts": int(accel_restarts),
        "cext_anderson_depth_used": int(anderson_depth_used),
        "cext_omega_last": float(omega_last),
        "cext_rel_residual_last": float(rel_residual_last),
        "cext_max_delta_last": float(max_delta_last),
        "cext_best_max_delta": float(best_max_delta if np.isfinite(best_max_delta) else max_delta_last),
        "cext_best_seen_stop": bool(best_seen_stop),
        "cext_step_rejections": int(step_rejections),
        "cext_candidate_batches": 0,
        "cext_candidate_query_mode": "hybrid_bg",
        "cext_frozen_backend": str(frozen_backend),
        "cext_active_source_count": int(active_source_count),
        "cext_frozen_source_count": int(frozen_source_count),
        "cext_active_target_count": int(active_target_count),
        "cext_frozen_target_count": int(frozen_target_count),
        "cext_active_component_count": int(active_component_count),
        "cext_largest_component_size": int(largest_component_size),
        "cext_active_freeze_events": int(active_freeze_events),
        "cext_active_refreshes": int(active_refreshes),
        "cext_target_freeze_events": 0,
        "cext_target_reactivations": 0,
        "cext_hybrid_bg_grid": int(hybrid["grid_n"]),
        "cext_hybrid_lambda_bins": int(hybrid["lambda_bins"]),
        "cext_hybrid_lambda_bin_policy": str(hybrid.get("lambda_bin_policy", "")),
        "cext_hybrid_lambda_bin_edges_hash": str(hybrid.get("lambda_bin_edges_hash", "")),
        "cext_hybrid_near_radius_si": float(hybrid["near_radius_si"]),
    }
    _store_tree_cext_state_cache(tree, cache_key, ext_state)
    return np.asarray(ext_state["cin_seg"], dtype=float), np.asarray(ext_state["cout_seg"], dtype=float)


__all__ = ['_solve_channel_concentrations_topdown_ext_hybrid_bg']
