# Legacy symbol names are bound by the temporary TissueSim compatibility facade.
# ruff: noqa: F821
"""Hybrid-grid field sampling and solve orchestration.

Generated by a behavior-preserving extraction from the frozen TissueSim
baseline. Dependencies are bound by the temporary compatibility facade while
the new typed subsystem APIs replace the legacy global runtime contract.
"""

from __future__ import annotations

from cascade.configuration import _legacy_state as _state
from cascade.runtime import _dependencies

for _dependency_name, _dependency_value in vars(_dependencies).items():
    if not _dependency_name.startswith("__"):
        globals().setdefault(_dependency_name, _dependency_value)
del _dependency_name, _dependency_value

def _sample_cext_hybrid_bg_gpu(
    context: dict,
    hybrid: dict,
    phi_grids_g,
    mass_grids_g,
    *,
    target_plan: dict | None = None,
    runtime_state: dict | None = None,
) -> tuple[object, float]:
    if _state._cp is None:
        raise RuntimeError("CuPy is not available.")
    static = _ensure_cext_hybrid_bg_gpu_static(context, hybrid)
    state = runtime_state if isinstance(runtime_state, dict) else _ensure_cext_hybrid_bg_runtime_state(context, hybrid, {"c_ext_gl": np.zeros((int(np.asarray(context["midpoints_si"]).shape[0]), int(np.asarray(context["gl_points_si"]).shape[1])), dtype=np.float32)})
    if "lambda_bin_centers" not in static:
        centers = np.asarray(hybrid.get("lambda_bin_centers", np.asarray([1.0], dtype=np.float32)), dtype=np.float32)
        static["lambda_bin_centers"] = _state._cp.asarray(np.asarray(centers, dtype=np.float32))
    kernel = _get_cext_hybrid_bg_kernel()
    gl_order = int(np.asarray(context["gl_points_si"]).shape[1])
    nseg = int(np.asarray(context["gl_points_si"]).shape[0])
    target_cfg = target_plan if isinstance(target_plan, dict) else None
    target_count = int(target_cfg.get("target_count", nseg)) if target_cfg is not None else nseg
    if target_count <= 0:
        return _state._cp.zeros((0, gl_order), dtype=_state._cp.float32), 0.0
    if target_cfg is None or bool(target_cfg.get("uses_static", False)):
        target_seg_ids_g = static["all_target_seg_ids"]
    else:
        if "gpu_target_seg_ids" not in target_cfg:
            target_cfg["gpu_target_seg_ids"] = _state._cp.asarray(np.asarray(target_cfg.get("target_seg_ids", np.zeros((0,), dtype=np.int32)), dtype=np.int32))
        target_seg_ids_g = target_cfg["gpu_target_seg_ids"]
    out_bg = state["bg_sample_g"][:target_count]
    threads = 128
    blocks = (target_count * gl_order + threads - 1) // threads
    t_kernel = perf_counter()
    kernel(
        (blocks,),
        (threads,),
        (
            target_seg_ids_g,
            _ensure_cext_gpu_geometry_static(context)["gl_points_si"].ravel(),
            _state._cp.asarray(phi_grids_g, dtype=_state._cp.float32).ravel(),
            _state._cp.asarray(mass_grids_g, dtype=_state._cp.float32).ravel(),
            static["lambda_bin_centers"],
            np.int32(int(static["lambda_bin_centers"].size)),
            np.int32(int(hybrid["grid_n"])),
            np.float32(float(hybrid["origin"][0])),
            np.float32(float(hybrid["origin"][1])),
            np.float32(float(hybrid["origin"][2])),
            np.float32(float(hybrid["spacing"])),
            np.float32(float(hybrid["near_radius_si"])),
            np.int32(gl_order),
            np.int32(target_count),
            np.float32(float(context["diffusivity_si"])),
            out_bg.ravel(),
        ),
    )
    _state._cp.cuda.Stream.null.synchronize()
    return out_bg, perf_counter() - t_kernel


def _compute_cext_hybrid_bg_gpu(
    context: dict,
    ext_state: dict,
    hybrid: dict,
    *,
    active_source_mask: np.ndarray | None = None,
    active_source_plan: dict | None = None,
    target_plan: dict | None = None,
    local_target_plan: dict | None = None,
    local_target_positions: np.ndarray | None = None,
    runtime_state: dict | None = None,
    frozen_mass_grids_g=None,
    frozen_phi_grids_g=None,
) -> tuple[np.ndarray, dict[str, float]]:
    if _state._cp is None:
        raise RuntimeError("CuPy is not available.")
    bg_mode = _resolve_cext_hybrid_bg_mode()
    if bg_mode in ("local_only_nlambda", "local_only"):
        return _compute_cext_local_only_hybrid_gpu(
            context,
            ext_state,
            hybrid,
            use_lambda_cutoff=(bg_mode == "local_only_nlambda"),
            runtime_state=runtime_state,
        )
    if bg_mode == "fft":
        hybrid["near_radius_si"] = 0.0
        hybrid["local_rad_cells"] = 0
    state = runtime_state if isinstance(runtime_state, dict) else _ensure_cext_hybrid_bg_runtime_state(context, hybrid, ext_state)
    _cext_hybrid_init_lambda_bins(hybrid, ext_state)
    active_mass_grids_g, t_deposit = _cext_hybrid_deposit_sources_gpu(
        context,
        hybrid,
        ext_state,
        source_mask=active_source_mask,
        runtime_state=state,
        out_mass_grids_g=state["active_mass_grids_g"],
    )
    active_phi_grids_g, t_fft, bg_solver_mode = _cext_hybrid_solve_background_fft_gpu(
        context,
        hybrid,
        active_mass_grids_g,
        init_phi_grids_g=hybrid.get("active_phi_guess_g"),
    )
    hybrid["active_phi_guess_g"] = active_phi_grids_g
    sample_mass_grids_g = active_mass_grids_g
    sample_phi_grids_g = active_phi_grids_g
    if frozen_mass_grids_g is not None:
        if "total_mass_grids_g" not in state or tuple(state["total_mass_grids_g"].shape) != tuple(active_mass_grids_g.shape):
            state["total_mass_grids_g"] = _state._cp.empty_like(active_mass_grids_g)
        state["total_mass_grids_g"][...] = active_mass_grids_g
        state["total_mass_grids_g"] += frozen_mass_grids_g
        sample_mass_grids_g = state["total_mass_grids_g"]
    if frozen_phi_grids_g is not None:
        if "total_phi_grids_g" not in state or tuple(state["total_phi_grids_g"].shape) != tuple(active_phi_grids_g.shape):
            state["total_phi_grids_g"] = _state._cp.empty_like(active_phi_grids_g)
        state["total_phi_grids_g"][...] = active_phi_grids_g
        state["total_phi_grids_g"] += frozen_phi_grids_g
        sample_phi_grids_g = state["total_phi_grids_g"]
    bg_corr_g, t_sample = _sample_cext_hybrid_bg_gpu(
        context,
        hybrid,
        sample_phi_grids_g,
        sample_mass_grids_g,
        target_plan=target_plan,
        runtime_state=state,
    )
    total_g = _state._cp.asarray(bg_corr_g, dtype=_state._cp.float32).copy()
    if float(hybrid.get("near_radius_si", 0.0)) > 0.0:
        local_plan = local_target_plan if isinstance(local_target_plan, dict) else target_plan
        local_total_g, local_cap_g, t_local, t_transfer_local = _compute_cext_local_corr_gpu(
            context,
            hybrid,
            ext_state,
            source_mask=active_source_mask,
            source_plan=active_source_plan,
            target_plan=local_plan,
            runtime_state=state,
        )
    else:
        local_total_g = None
        local_cap_g = None
        t_local = 0.0
        t_transfer_local = 0.0
    if bool(_state.CEXT_HYBRID_GPU_ITERATION_CACHE) and "seg_cap_gl" in state and int(state["seg_cap_gl"].size) > 0:
        global_cap = float(_state._cp.nanmax(state["seg_cap_gl"]).item())
    else:
        global_cap = float(np.nanmax(np.asarray(ext_state.get("seg_cap_gl", np.zeros((0,), dtype=np.float32)), dtype=float))) if np.asarray(ext_state.get("seg_cap_gl", ())).size else 0.0
    local_count = int(_state._cp.asarray(local_total_g).shape[0]) if local_total_g is not None else 0
    target_count = int(total_g.shape[0])
    local_report_count = local_count if float(hybrid.get("near_radius_si", 0.0)) > 0.0 else 0
    if local_count == target_count:
        total_g += _state._cp.asarray(local_total_g, dtype=_state._cp.float32)
    elif local_count > 0:
        if local_target_positions is None:
            raise ValueError("local_target_positions is required when hybrid local targets are a subset")
        local_pos_g = _state._cp.asarray(np.asarray(local_target_positions, dtype=np.int32))
        if int(local_pos_g.size) != local_count:
            raise ValueError("local_target_positions length does not match local target count")
        total_g[local_pos_g, :] += _state._cp.asarray(local_total_g, dtype=_state._cp.float32)
    if global_cap > 0.0:
        _state._cp.minimum(total_g, _state._cp.float32(global_cap), out=total_g)
    _state._cp.maximum(total_g, _state._cp.float32(0.0), out=total_g)
    t_o2 = 0.0
    t_self_sub = 0.0
    if bg_mode == "fft":
        if bool(_state.CEXT_HYBRID_FFT_O2_CORRECTION):
            o2_corr_g, t_o2 = _cext_fft_o2_term_correction_gpu(
                context,
                hybrid,
                ext_state,
                state,
                target_plan=target_plan,
            )
            if o2_corr_g is not None:
                total_g += _state._cp.asarray(o2_corr_g, dtype=_state._cp.float32)
        if bool(_state.CEXT_HYBRID_FFT_SELF_SUBTRACT):
            same_seg_g, t_self_sub = _cext_fft_discrete_same_segment_contribution_gpu(
                context,
                hybrid,
                ext_state,
                state,
                target_plan=target_plan,
                include_finite=bool(_state.CEXT_HYBRID_FFT_O2_CORRECTION),
            )
            if same_seg_g is not None:
                total_g -= _state._cp.float32(float(_state.CEXT_HYBRID_FFT_SELF_SUB_SCALE)) * _state._cp.asarray(same_seg_g, dtype=_state._cp.float32)
        if global_cap > 0.0:
            _state._cp.minimum(total_g, _state._cp.float32(global_cap), out=total_g)
        _state._cp.maximum(total_g, _state._cp.float32(0.0), out=total_g)
    t_download = perf_counter()
    c_ext_new = _state._cp.asnumpy(total_g)
    _state._cp.cuda.Stream.null.synchronize()
    timings = {
        "deposit_s": float(t_deposit),
        "fft_s": float(t_fft),
        "sample_s": float(t_sample),
        "fft_o2_terms_s": float(t_o2),
        "fft_discrete_self_subtract_s": float(t_self_sub),
        "local_corr_s": float(t_local),
        "transfer_s": float(t_transfer_local + (perf_counter() - t_download)),
        "bg_solver_mode": str(bg_solver_mode),
        "local_target_count": float(local_report_count),
    }
    return np.asarray(c_ext_new, dtype=np.float32), timings


__all__ = ['_sample_cext_hybrid_bg_gpu', '_compute_cext_hybrid_bg_gpu']
