"""Coupled treecode external-field solver.

Generated by a behavior-preserving extraction from the frozen TissueSim
baseline. Dependencies are bound by the temporary compatibility facade while
the new typed subsystem APIs replace the legacy global runtime contract.
"""

from __future__ import annotations

from time import perf_counter
from typing import Tuple

import numpy as np

from cascade.configuration import _legacy_state as _state
from cascade.concentration.vessel.greens import _normalize_cext_lambda_source
from cascade.concentration.vessel.topdown import _solve_channel_concentrations_topdown
from cascade.flow.hematocrit import (
    _get_tree_hematocrit_cache,
    _hematocrit_context_for_tree,
    _store_tree_hematocrit_cache,
    compute_tree_hematocrit,
)

from .acceleration import _cext_apply_component_acceleration
from .backend import _resolve_cext_accel_mode, _resolve_cext_frozen_accel_mode
from .coupling_steps import _run_topdown_ext_frozen_step
from .diagnostics import (
    _cext_should_enable_anderson,
    _cext_source_state_delta_metrics,
    _clip_cext_omega,
    _default_cext_timing_details,
    _maybe_trace_cext_iteration,
)
from .geometry import _build_cext_geometry_context
from .state import (
    _build_cext_iteration_cache,
    _cext_state_cache_key,
    _initialize_cext_state,
)
from .topdown_solver import _solve_channel_concentrations_topdown_ext
from .treecode import (
    _build_cext_treecode_context,
    _cext_should_enter_tail_mode,
    _compute_cext_treecode_gpu,
    _estimate_cext_tail_active_core,
    _solve_cext_treecode_active_core_nk,
)

def _solve_channel_concentrations_topdown_ext_treecode(
    tree: _state.Tree,
    flows: np.ndarray,
    starts: np.ndarray,
    ends: np.ndarray,
    radii: np.ndarray,
    lengths: np.ndarray,
    *,
    inlet_concentration: float,
    diffusivity: float,
    vmax: float,
    km: float,
    fluid: str,
) -> Tuple[np.ndarray, np.ndarray]:
    # Mutable runtime state is centralized in configuration._legacy_state.
    if float(_state.CEXT_WINDOW_FACTOR) <= 0.0:
        cin, cout = _solve_channel_concentrations_topdown(
            tree,
            flows,
            inlet_concentration=inlet_concentration,
            diffusivity=diffusivity,
            vmax=vmax,
            km=km,
            fluid=fluid,
        )
        _state._LAST_CONCENTRATION_TIMINGS = _default_cext_timing_details(backend="disabled")
        return cin, cout
    nseg = int(getattr(tree, "segment_count", 0))
    if nseg <= 0:
        empty = np.empty((0,), dtype=float)
        return empty, empty
    if _state._cp is None:
        return _solve_channel_concentrations_topdown_ext(
            tree,
            flows,
            starts,
            ends,
            radii,
            lengths,
            inlet_concentration=inlet_concentration,
            diffusivity=diffusivity,
            vmax=vmax,
            km=km,
            fluid=fluid,
        )

    t_total = perf_counter()
    t_stage = t_total
    fluid_mode = (fluid or getattr(getattr(tree, "parameters", None), "fluid", None) or _state.ACTIVE_FLUID).lower()
    hct_context = _hematocrit_context_for_tree(tree)
    radii_arr = np.asarray(hct_context["radii"], dtype=float)
    flows_arr = np.asarray(flows, dtype=float)
    chb_max = np.zeros_like(radii_arr)
    hct_source = "none"
    if fluid_mode == "blood":
        cached_hct = _get_tree_hematocrit_cache(
            tree,
            nseg,
            model=_state.HEMATOCRIT_MODEL,
            flows=flows_arr,
        )
        if cached_hct is not None:
            HD, HT = cached_hct
            hct_source = "cache"
        else:
            HD, HT = compute_tree_hematocrit(
                tree,
                hd_root=_state.HD_DISCHARGE,
                flows=flows_arr,
                model=_state.HEMATOCRIT_MODEL,
                order=np.asarray(hct_context["order"], dtype=np.int64),
            )
            _store_tree_hematocrit_cache(
                tree,
                HD,
                HT,
                model=_state.HEMATOCRIT_MODEL,
                flows=flows_arr,
                fixed_flow_bc=False,
            )
            hct_source = "computed"
        chb_max = np.asarray(HT, dtype=float) * float(_state.O2_CAP_PER_HCT)
    hct_setup_s = perf_counter() - t_stage

    t_stage = perf_counter()
    context = _build_cext_geometry_context(
        tree,
        flows_arr,
        starts,
        ends,
        radii,
        lengths,
        inlet_concentration=inlet_concentration,
        diffusivity=diffusivity,
        vmax=vmax,
        km=km,
    )
    backend = _resolve_cext_accel_mode()
    frozen_backend = _resolve_cext_frozen_accel_mode()
    if backend != "gpu":
        return _solve_channel_concentrations_topdown_ext(
            tree,
            flows,
            starts,
            ends,
            radii,
            lengths,
            inlet_concentration=inlet_concentration,
            diffusivity=diffusivity,
            vmax=vmax,
            km=km,
            fluid=fluid,
        )
    context["candidate_query_mode"] = "treecode"
    context["candidate_build_time_s"] = 0.0
    t_build = perf_counter()
    treecode = _build_cext_treecode_context(context)
    leaf_scale = float(treecode["side"]) / float(max(1 << max(int(treecode["max_depth"]), 0), 1))
    treecode["near_radius_si"] = float(max(float(_state.CEXT_TREECODE_NEAR_RADIUS_MULT), 1.0) * max(leaf_scale, 1.0e-9))
    treecode_build_s = perf_counter() - t_build

    cache_key = _cext_state_cache_key(
        fluid_mode=fluid_mode,
        inlet_concentration=float(inlet_concentration),
        diffusivity_si=float(diffusivity * _state.CM2_TO_M2),
        vmax=float(vmax),
        km=float(km),
    )
    ext_state = _initialize_cext_state(
        tree,
        cache_key=cache_key,
        nseg=nseg,
        inlet_concentration=float(inlet_concentration),
        vmax=float(vmax),
        km=float(km),
    )
    accel_mode = str(_state.CEXT_VESS_COUPLING_ACCEL or "none").strip().lower()
    if accel_mode not in ("none", "aitken", "anderson"):
        raise ValueError("--cext-vess-coupling-accel must be 'none', 'aitken', or 'anderson'.")
    init_mode = str(_state.CEXT_INIT_MODE or "zero").strip().lower()
    if init_mode not in ("zero", "decoupled_greens"):
        raise ValueError("--cext-init-mode must be 'zero' or 'decoupled_greens'.")

    aggregate_total = 0.0
    traversal_total = 0.0
    transfer_total = 0.0
    frozen_transfer_total = 0.0
    completed_iters = 0
    max_delta_last = 0.0
    rel_residual_last = 0.0
    omega_last = _clip_cext_omega(_state.CEXT_VESS_COUPLING_OMEGA)
    accel_step_last = "picard"
    accel_rejections = 0
    accel_restarts = 0
    anderson_depth_used = 0
    prev_residual_flat: np.ndarray | None = None
    prev_abs_residual = float("inf")
    stable_iters = 0
    anderson_g_history: list[np.ndarray] = []
    anderson_r_history: list[np.ndarray] = []
    residual_history: list[float] = []
    tail_mode_entered = False
    tail_core_count = 0
    tail_nonlinear_iters = 0
    tail_gmres_iters = 0
    accepted_nodes_last = 0
    opened_nodes_last = 0
    exact_pairs_last = 0
    active_source_mask = np.ones((nseg,), dtype=bool)
    active_source_stable_counts = np.zeros((nseg,), dtype=np.int16)
    prev_source_c_ext_gl: np.ndarray | None = None
    prev_source_c_iv_gl: np.ndarray | None = None
    ext_state["treecode_active_source_mask"] = np.asarray(active_source_mask, dtype=bool)

    if _state.SOLVER_TIMING_DETAILS:
        print(
            "  Concentration topdown_ext_treecode: "
            f"nseg={nseg} fluid={fluid_mode} backend={backend} frozen={frozen_backend} gl_order={_state.GL_ORDER_CEXT} "
            f"hct={hct_source} accel={accel_mode} theta={float(treecode['theta']):.3f} "
            f"cext_lambda={_normalize_cext_lambda_source()} "
            f"leaf={int(treecode['leaf_nodes'])} bins={int(treecode['lambda_bins'])} "
            f"near={float(treecode['near_radius_si']):.3e} nodes={int(treecode['node_count'])} "
            f"leaves={int(treecode['leaf_count'])} depth={int(treecode['max_depth'])}"
        )

    init_performed = False
    if init_mode == "decoupled_greens":
        cin_seg, cout_seg, c_iv_gl, frozen_backend, frozen_transfer = _run_topdown_ext_frozen_step(
            context,
            ext_state,
            inlet_concentration=float(inlet_concentration),
            vmax=float(vmax),
            km=float(km),
            chb_max=np.asarray(chb_max, dtype=np.float32),
            fluid_mode=fluid_mode,
            frozen_backend=frozen_backend,
        )
        frozen_transfer_total += float(frozen_transfer)
        ext_state["cin_seg"] = cin_seg
        ext_state["cout_seg"] = cout_seg
        ext_state["c_iv_gl"] = np.asarray(c_iv_gl, dtype=np.float32)
        ext_state["treecode_active_source_mask"] = np.asarray(active_source_mask, dtype=bool)
        _build_cext_iteration_cache(context, ext_state)
        c_ext_new, tc_metrics = _compute_cext_treecode_gpu(context, treecode, ext_state)
        aggregate_total += float(tc_metrics.get("aggregate_s", 0.0))
        traversal_total += float(tc_metrics.get("traversal_s", 0.0))
        transfer_total += float(tc_metrics.get("transfer_s", 0.0))
        ext_state["c_ext_gl"] = np.asarray(c_ext_new, dtype=np.float32)
        accepted_nodes_last = int(tc_metrics.get("accepted_nodes", 0))
        opened_nodes_last = int(tc_metrics.get("opened_nodes", 0))
        exact_pairs_last = int(tc_metrics.get("exact_pairs", 0))
        if _state.SOLVER_TIMING_DETAILS:
            print(
                "    Cext init predictor: "
                f"max_cext={float(np.nanmax(np.asarray(ext_state['c_ext_gl'], dtype=float))) if ext_state['c_ext_gl'].size else 0.0:.3e}"
            )
        _maybe_trace_cext_iteration(0, ext_state, solver="topdown_ext_treecode", context=context, backend=backend)
        init_performed = True

    if not init_performed:
        _maybe_trace_cext_iteration(0, ext_state, solver="topdown_ext_treecode", context=context, backend=backend)

    for iter_idx in range(1, int(_state.CEXT_VESS_COUPLING_MAX_ITER) + 1):
        cin_seg, cout_seg, c_iv_gl, frozen_backend, frozen_transfer = _run_topdown_ext_frozen_step(
            context,
            ext_state,
            inlet_concentration=float(inlet_concentration),
            vmax=float(vmax),
            km=float(km),
            chb_max=np.asarray(chb_max, dtype=np.float32),
            fluid_mode=fluid_mode,
            frozen_backend=frozen_backend,
        )
        frozen_transfer_total += float(frozen_transfer)
        ext_state["cin_seg"] = cin_seg
        ext_state["cout_seg"] = cout_seg
        ext_state["c_iv_gl"] = np.asarray(c_iv_gl, dtype=np.float32)
        ext_state["treecode_active_source_mask"] = np.asarray(active_source_mask, dtype=bool)
        _build_cext_iteration_cache(context, ext_state)
        current_c_ext_gl = np.asarray(ext_state["c_ext_gl"], dtype=np.float32)
        c_ext_new, tc_metrics = _compute_cext_treecode_gpu(context, treecode, ext_state)
        aggregate_total += float(tc_metrics.get("aggregate_s", 0.0))
        traversal_total += float(tc_metrics.get("traversal_s", 0.0))
        transfer_total += float(tc_metrics.get("transfer_s", 0.0))
        accepted_nodes_last = int(tc_metrics.get("accepted_nodes", 0))
        opened_nodes_last = int(tc_metrics.get("opened_nodes", 0))
        exact_pairs_last = int(tc_metrics.get("exact_pairs", 0))

        candidate_flat, accel_state, accel_metrics = _cext_apply_component_acceleration(
            current_c_ext_gl.reshape(-1),
            np.asarray(c_ext_new, dtype=np.float32).reshape(-1),
            {
                "prev_residual_flat": prev_residual_flat,
                "prev_abs_residual": prev_abs_residual,
                "stable_iters": stable_iters,
                "anderson_g_history": anderson_g_history,
                "anderson_r_history": anderson_r_history,
                "accel_rejections": accel_rejections,
                "accel_restarts": accel_restarts,
                "anderson_depth_used": anderson_depth_used,
                "omega_last": omega_last,
                "iter_count": completed_iters,
            },
            accel_mode=accel_mode,
        )
        ext_state["c_ext_gl"] = np.asarray(candidate_flat.reshape(current_c_ext_gl.shape), dtype=np.float32)
        completed_iters = iter_idx
        prev_residual_flat = np.asarray(accel_state["prev_residual_flat"], dtype=np.float32).copy()
        prev_abs_residual = float(accel_state["prev_abs_residual"])
        stable_iters = int(accel_state["stable_iters"])
        anderson_g_history = [np.asarray(arr, dtype=np.float32).copy() for arr in accel_state["anderson_g_history"]]
        anderson_r_history = [np.asarray(arr, dtype=np.float32).copy() for arr in accel_state["anderson_r_history"]]
        accel_rejections = int(accel_metrics["accel_rejections"])
        accel_restarts = int(accel_metrics["accel_restarts"])
        anderson_depth_used = int(accel_metrics["anderson_depth_used"])
        omega_last = float(accel_metrics["omega_last"])
        accel_step_last = str(accel_metrics["accel_step_last"])
        max_delta_last = float(accel_metrics["max_delta_last"])
        rel_residual_last = float(accel_metrics["rel_residual_last"])
        residual_history.append(float(rel_residual_last))

        source_abs_delta, source_rel_delta = _cext_source_state_delta_metrics(
            prev_source_c_ext_gl,
            prev_source_c_iv_gl,
            np.asarray(ext_state["c_ext_gl"], dtype=np.float32),
            np.asarray(ext_state["c_iv_gl"], dtype=np.float32),
        )
        prev_source_c_ext_gl = np.asarray(ext_state["c_ext_gl"], dtype=np.float32).copy()
        prev_source_c_iv_gl = np.asarray(ext_state["c_iv_gl"], dtype=np.float32).copy()
        q_weighted = np.asarray(ext_state.get("q_weighted_gl", np.zeros_like(ext_state["c_ext_gl"])), dtype=np.float32)
        q_seg = np.max(np.abs(q_weighted), axis=1).astype(np.float32, copy=False) if q_weighted.ndim == 2 else np.zeros((nseg,), dtype=np.float32)
        q_scale = max(float(np.max(q_seg)) if q_seg.size else 0.0, float(_state.VESS_CONC_FLOOR))
        q_rel = np.divide(
            q_seg,
            np.float32(q_scale),
            out=np.zeros_like(q_seg, dtype=np.float32),
            where=q_scale > 0.0,
        )
        stable_now = (
            np.asarray(source_abs_delta, dtype=np.float32) <= float(_state.CEXT_ACTIVE_SET_ABS_TOL)
        ) & (
            np.asarray(source_rel_delta, dtype=np.float32) <= float(_state.CEXT_ACTIVE_SET_REL_TOL)
        )
        active_source_stable_counts[active_source_mask & stable_now] = np.minimum(
            np.asarray(active_source_stable_counts[active_source_mask & stable_now], dtype=np.int32) + 1,
            np.int16(np.iinfo(np.int16).max),
        ).astype(np.int16, copy=False)
        active_source_stable_counts[active_source_mask & (~stable_now)] = np.int16(0)
        reactivate_mask = (~active_source_mask) & (
            (np.asarray(source_abs_delta, dtype=np.float32) > float(_state.CEXT_ACTIVE_SET_ABS_TOL) * 2.0)
            | (np.asarray(source_rel_delta, dtype=np.float32) > float(_state.CEXT_ACTIVE_SET_REL_TOL) * 2.0)
            | (q_rel > float(_state.CEXT_TREECODE_FREEZE_QREL_TOL) * 1.5)
        )
        if np.any(reactivate_mask):
            active_source_mask[reactivate_mask] = True
            active_source_stable_counts[reactivate_mask] = np.int16(0)
        if bool(_state.CEXT_ACTIVE_SET_ENABLE) and iter_idx >= int(_state.CEXT_ACTIVE_SET_START):
            min_active_sources = max(1, int(_state.CEXT_ACTIVE_SET_MIN_ACTIVE_COUNT))
            freeze_candidates = active_source_mask & (
                active_source_stable_counts >= int(_state.CEXT_ACTIVE_SET_STABLE_ITERS)
            ) & (
                q_rel <= float(_state.CEXT_TREECODE_FREEZE_QREL_TOL)
            )
            active_count_now = int(np.count_nonzero(active_source_mask))
            if np.any(freeze_candidates) and active_count_now > min_active_sources:
                freeze_ids = np.flatnonzero(freeze_candidates).astype(np.int32, copy=False)
                max_freeze = max(active_count_now - min_active_sources, 0)
                if freeze_ids.size > max_freeze:
                    order = np.lexsort((
                        np.asarray(source_abs_delta[freeze_ids], dtype=np.float32),
                        np.asarray(source_rel_delta[freeze_ids], dtype=np.float32),
                        np.asarray(q_rel[freeze_ids], dtype=np.float32),
                    ))
                    freeze_ids = np.asarray(freeze_ids[order[:max_freeze]], dtype=np.int32)
                if freeze_ids.size > 0:
                    active_source_mask[freeze_ids] = False
                    active_source_stable_counts[freeze_ids] = np.int16(0)
        ext_state["treecode_active_source_mask"] = np.asarray(active_source_mask, dtype=bool)

        core_ids, _ = _estimate_cext_tail_active_core(context, ext_state, np.asarray(c_ext_new, dtype=np.float32))
        tail_core_count = int(core_ids.size)
        if (not tail_mode_entered) and _cext_should_enter_tail_mode(residual_history, tail_core_count, iter_idx=iter_idx):
            tail_mode_entered = True
            if _state.SOLVER_TIMING_DETAILS:
                print(f"    Cext tail mode: solver={_state.CEXT_TAIL_SOLVER} core={tail_core_count}")
            tail_full, tail_metrics = _solve_cext_treecode_active_core_nk(
                context,
                treecode,
                ext_state,
                core_seg_ids=core_ids,
                inlet_concentration=float(inlet_concentration),
                vmax=float(vmax),
                km=float(km),
                chb_max=np.asarray(chb_max, dtype=np.float32),
                fluid_mode=fluid_mode,
                frozen_backend=frozen_backend,
            )
            tail_nonlinear_iters = int(tail_metrics.get("nonlinear_iters", 0))
            tail_gmres_iters = int(tail_metrics.get("gmres_iters", 0))
            ext_state["c_ext_gl"] = np.asarray(tail_full, dtype=np.float32)
            if isinstance(tail_metrics.get("state"), dict):
                tail_state = dict(tail_metrics["state"])
                for key in (
                    "cin_seg", "cout_seg", "c_iv_gl", "c_bulk_gl", "c_wall_gl",
                    "lambda_iv_gl", "k_if_gl", "q_line_gl", "q_weighted_gl",
                    "mono2_weight_gl", "dipole2_weight_gl", "seg_cap_gl",
                ):
                    if key in tail_state:
                        ext_state[key] = np.asarray(tail_state[key], dtype=np.float32) if key.endswith("_gl") or key.endswith("_seg") else tail_state[key]
            frozen_backend = str(tail_metrics.get("frozen_backend", frozen_backend))
            rel_residual_last = float(tail_metrics.get("rel_residual", rel_residual_last))
            max_delta_last = float(rel_residual_last)
            accel_step_last = str(_state.CEXT_TAIL_SOLVER)
            if bool(tail_metrics.get("success", False)):
                if _state.SOLVER_TIMING_DETAILS:
                    print(
                        f"    Cext tail solved: rel={rel_residual_last:.3e} "
                        f"gmres={tail_gmres_iters} nonlinear={tail_nonlinear_iters}"
                    )
                break

        if _state.SOLVER_TIMING_DETAILS:
            print(
                f"    Cext iter {iter_idx}/{int(_state.CEXT_VESS_COUPLING_MAX_ITER)}: "
                f"max_delta={max_delta_last:.3e} rel={rel_residual_last:.3e} "
                f"step={accel_step_last} omega={omega_last:.3f} stable={stable_iters} "
                f"active_src={int(np.count_nonzero(active_source_mask))} "
                f"frozen_src={int(nseg - np.count_nonzero(active_source_mask))} active_tgt={nseg} frozen_tgt=0 "
                f"accepted={accepted_nodes_last} opened={opened_nodes_last} exact_pairs={exact_pairs_last}"
            )
        if max_delta_last < float(_state.CEXT_VESS_COUPLING_TOL):
            break
        if float(_state.CEXT_VESS_COUPLING_REL_TOL) > 0.0 and rel_residual_last < float(_state.CEXT_VESS_COUPLING_REL_TOL):
            break

    total_elapsed = perf_counter() - t_total
    _state._LAST_CONCENTRATION_TIMINGS = _default_cext_timing_details(backend=backend)
    _state._LAST_CONCENTRATION_TIMINGS.update(
        {
            "backend": backend,
            "t_cext_total_s": float(total_elapsed),
            "t_cext_kernel_s": float(traversal_total),
            "t_cext_gpu_transfer_s": float(transfer_total),
            "t_cext_frozen_gpu_transfer_s": float(frozen_transfer_total),
            "t_cext_treecode_build_s": float(treecode_build_s),
            "t_cext_treecode_aggregate_s": float(aggregate_total),
            "t_cext_treecode_traversal_s": float(traversal_total),
            "t_cext_treecode_exact_s": 0.0,
            "cext_treecode_theta": float(treecode["theta"]),
            "cext_treecode_order": int(treecode["order_mode"]),
            "cext_treecode_leaf_nodes": int(treecode["leaf_nodes"]),
            "cext_treecode_lambda_bins": int(treecode["lambda_bins"]),
            "cext_treecode_near_radius_si": float(treecode["near_radius_si"]),
            "cext_treecode_node_count": int(treecode["node_count"]),
            "cext_treecode_leaf_count": int(treecode["leaf_count"]),
            "cext_treecode_max_depth": int(treecode["max_depth"]),
            "cext_treecode_accepted_nodes": int(accepted_nodes_last),
            "cext_treecode_opened_nodes": int(opened_nodes_last),
            "cext_treecode_exact_pairs": int(exact_pairs_last),
            "cext_init_mode": init_mode,
            "cext_outer_iterations_completed": int(completed_iters),
            "cext_total_iterations_effective": int(completed_iters + (1 if init_mode == "decoupled_greens" else 0)),
            "cext_accel_mode": accel_mode,
            "cext_accel_step_last": accel_step_last,
            "cext_accel_rejections": int(accel_rejections),
            "cext_accel_restarts": int(accel_restarts),
            "cext_anderson_depth_used": int(anderson_depth_used),
            "cext_omega_last": float(omega_last),
            "cext_rel_residual_last": float(rel_residual_last),
            "cext_max_delta_last": float(max_delta_last),
            "cext_candidate_batches": 0,
            "cext_candidate_query_mode": "treecode",
            "cext_frozen_backend": str(frozen_backend),
            "cext_active_source_count": int(nseg),
            "cext_frozen_source_count": 0,
            "cext_active_target_count": int(nseg),
            "cext_frozen_target_count": 0,
            "cext_tail_mode_entered": bool(tail_mode_entered),
            "cext_tail_solver": str(_state.CEXT_TAIL_SOLVER if tail_mode_entered else "none"),
            "cext_tail_core_count": int(tail_core_count),
            "cext_tail_nonlinear_iters": int(tail_nonlinear_iters),
            "cext_tail_gmres_iters": int(tail_gmres_iters),
        }
    )
    return np.asarray(ext_state["cin_seg"], dtype=float), np.asarray(ext_state["cout_seg"], dtype=float)


__all__ = ['_solve_channel_concentrations_topdown_ext_treecode']
