"""Treecode Cext implementation.

Generated by a behavior-preserving extraction from the frozen TissueSim
baseline. Dependencies are bound by the temporary compatibility facade while
the new typed subsystem APIs replace the legacy global runtime contract.
"""

from __future__ import annotations

import math
from time import perf_counter

import numpy as np

from cascade.configuration import _legacy_state as _state
from cascade.runtime.cuda import load_cuda_source

from .coupling_steps import _run_topdown_ext_frozen_step
from .direct import _ensure_cext_gpu_static
from .hybrid_deposit import (
    _cext_hybrid_deposit_sources_gpu,
    _cext_hybrid_solve_background_fft_gpu,
)
from .hybrid_geometry import _ensure_cext_hybrid_bg_runtime_state
from .state import _build_cext_iteration_cache

try:
    import scipy.sparse.linalg as _splinalg
except ImportError:  # pragma: no cover - validated by the selected backend
    _splinalg = None

def _part1by2_64(n: np.ndarray) -> np.ndarray:
    x = np.asarray(n, dtype=np.uint64) & np.uint64(0x1FFFFF)
    x = (x | (x << np.uint64(32))) & np.uint64(0x1F00000000FFFF)
    x = (x | (x << np.uint64(16))) & np.uint64(0x1F0000FF0000FF)
    x = (x | (x << np.uint64(8))) & np.uint64(0x100F00F00F00F00F)
    x = (x | (x << np.uint64(4))) & np.uint64(0x10C30C30C30C30C3)
    x = (x | (x << np.uint64(2))) & np.uint64(0x1249249249249249)
    return x


def _morton3d_codes(points: np.ndarray, origin: np.ndarray, side: float, *, bits: int) -> np.ndarray:
    pts = np.asarray(points, dtype=np.float64)
    if pts.size <= 0:
        return np.zeros((0,), dtype=np.uint64)
    bits = max(min(int(bits), 21), 1)
    scale = float((1 << bits) - 1)
    local = (pts - np.asarray(origin, dtype=np.float64)[None, :]) / max(float(side), 1.0e-30)
    local = np.clip(local, 0.0, 1.0)
    idx = np.floor(local * scale + 0.5).astype(np.uint64)
    return _part1by2_64(idx[:, 0]) | (_part1by2_64(idx[:, 1]) << np.uint64(1)) | (_part1by2_64(idx[:, 2]) << np.uint64(2))


def _treecode_child_offset(slot: int) -> np.ndarray:
    return np.asarray(
        [
            -0.5 if (slot & 0x4) == 0 else 0.5,
            -0.5 if (slot & 0x2) == 0 else 0.5,
            -0.5 if (slot & 0x1) == 0 else 0.5,
        ],
        dtype=np.float32,
    )


def _build_cext_treecode_context(context: dict) -> dict:
    cached = context.get("treecode_context")
    gl_points = np.asarray(context.get("gl_points_si", np.zeros((0, 0, 3), dtype=np.float32)), dtype=np.float32)
    gl_order = int(gl_points.shape[1]) if gl_points.ndim >= 2 else 0
    nseg = int(gl_points.shape[0]) if gl_points.ndim >= 1 else 0
    leaf_nodes = max(int(_state.CEXT_TREECODE_LEAF_NODES), 8)
    theta = max(float(_state.CEXT_TREECODE_THETA), 1.0e-3)
    near_radius_mult = max(float(_state.CEXT_TREECODE_NEAR_RADIUS_MULT), 1.0)
    lambda_bins = max(int(_state.CEXT_TREECODE_LAMBDA_BINS), 1)
    order_mode = max(int(_state.CEXT_TREECODE_ORDER), 0)
    if isinstance(cached, dict):
        if (
            int(cached.get("gl_order", -1)) == gl_order
            and int(cached.get("nseg", -1)) == nseg
            and int(cached.get("leaf_nodes", -1)) == leaf_nodes
            and int(cached.get("lambda_bins", -1)) == lambda_bins
            and float(cached.get("theta", -1.0)) == theta
            and float(cached.get("near_radius_mult", -1.0)) == near_radius_mult
            and int(cached.get("order_mode", -1)) == order_mode
        ):
            return cached
    gl_points_flat = np.asarray(gl_points.reshape(-1, 3), dtype=np.float32)
    n_nodes = int(gl_points_flat.shape[0])
    node_seg_ids = np.repeat(np.arange(nseg, dtype=np.int32), max(gl_order, 1)) if n_nodes > 0 else np.zeros((0,), dtype=np.int32)
    if n_nodes > 0:
        mins = np.min(gl_points_flat, axis=0)
        maxs = np.max(gl_points_flat, axis=0)
    else:
        mins = np.zeros((3,), dtype=np.float32)
        maxs = np.ones((3,), dtype=np.float32)
    center = 0.5 * (mins + maxs)
    span = max(float(np.max(maxs - mins)), 1.0e-8)
    pad = max(float(context.get("max_reach_si", 0.0)), 0.05 * span)
    side = float(span + 2.0 * pad)
    origin = np.asarray(center - 0.5 * side, dtype=np.float32)
    bits = int(min(21, max(8, math.ceil(math.log2(max((n_nodes / max(float(leaf_nodes), 1.0)) ** (1.0 / 3.0), 1.0))) + 3)))
    morton = _morton3d_codes(gl_points_flat, origin, side, bits=bits)
    order = np.argsort(morton, kind="stable")
    sorted_codes = np.asarray(morton[order], dtype=np.uint64)
    sorted_node_ids = np.asarray(order, dtype=np.int32)
    sorted_points = np.asarray(gl_points_flat[sorted_node_ids], dtype=np.float32)
    sorted_seg_ids = np.asarray(node_seg_ids[sorted_node_ids], dtype=np.int32)
    point_leaf_ids = np.full((n_nodes,), -1, dtype=np.int32)
    node_start: list[int] = []
    node_end: list[int] = []
    node_level: list[int] = []
    node_center: list[np.ndarray] = []
    node_half: list[float] = []
    node_parent: list[int] = []
    node_children: list[list[int]] = []
    node_is_leaf: list[bool] = []
    leaf_ids: list[int] = []
    queue: list[tuple[int, int, int, np.ndarray, float, int, int]] = [(0, n_nodes, 0, np.asarray(center, dtype=np.float32), 0.5 * side, -1, -1)]
    max_depth = 0
    while queue:
        lo, hi, level, node_ctr, half, parent_id, child_slot = queue.pop()
        node_id = len(node_start)
        node_start.append(int(lo))
        node_end.append(int(hi))
        node_level.append(int(level))
        node_center.append(np.asarray(node_ctr, dtype=np.float32))
        node_half.append(float(half))
        node_parent.append(int(parent_id))
        node_children.append([-1] * 8)
        count = int(hi - lo)
        is_leaf = count <= leaf_nodes or level >= bits or count <= 1
        node_is_leaf.append(bool(is_leaf))
        if parent_id >= 0 and child_slot >= 0:
            node_children[parent_id][child_slot] = node_id
        max_depth = max(max_depth, int(level))
        if is_leaf:
            leaf_ids.append(node_id)
            if hi > lo:
                point_leaf_ids[lo:hi] = np.int32(node_id)
            continue
        shift = max(3 * (bits - level - 1), 0)
        child_codes = np.asarray((sorted_codes[lo:hi] >> np.uint64(shift)) & np.uint64(0x7), dtype=np.int32)
        if child_codes.size <= 0:
            node_is_leaf[node_id] = True
            leaf_ids.append(node_id)
            continue
        split_idx = np.flatnonzero(np.diff(child_codes)) + 1
        bounds = np.concatenate(([0], split_idx, [child_codes.size]))
        child_half = float(half) * 0.5
        for bound_lo, bound_hi in zip(bounds[:-1], bounds[1:]):
            slot = int(child_codes[int(bound_lo)])
            child_ctr = np.asarray(node_ctr, dtype=np.float32) + np.float32(child_half) * _treecode_child_offset(slot)
            queue.append((int(lo + bound_lo), int(lo + bound_hi), int(level + 1), child_ctr, child_half, int(node_id), int(slot)))
    point_leaf_ids = np.asarray(point_leaf_ids, dtype=np.int32)
    node_level_arr = np.asarray(node_level, dtype=np.int16)
    node_is_leaf_arr = np.asarray(node_is_leaf, dtype=bool)
    upsweep_levels: list[np.ndarray] = []
    for level in range(int(max_depth) - 1, -1, -1):
        ids = np.flatnonzero((node_level_arr == level) & (~node_is_leaf_arr)).astype(np.int32, copy=False)
        if ids.size > 0:
            upsweep_levels.append(np.asarray(ids, dtype=np.int32))
    if upsweep_levels:
        upsweep_node_ids = np.concatenate(upsweep_levels).astype(np.int32, copy=False)
        upsweep_level_offsets = np.zeros((len(upsweep_levels) + 1,), dtype=np.int32)
        upsweep_level_offsets[1:] = np.cumsum(
            np.asarray([arr.size for arr in upsweep_levels], dtype=np.int64),
            dtype=np.int64,
        ).astype(np.int32)
    else:
        upsweep_node_ids = np.zeros((0,), dtype=np.int32)
        upsweep_level_offsets = np.zeros((1,), dtype=np.int32)
    treecode = {
        "gl_order": int(gl_order),
        "nseg": int(nseg),
        "leaf_nodes": int(leaf_nodes),
        "theta": float(theta),
        "lambda_bins": int(lambda_bins),
        "near_radius_mult": float(near_radius_mult),
        "order_mode": int(order_mode),
        "origin": np.asarray(origin, dtype=np.float32),
        "side": float(side),
        "center": np.asarray(center, dtype=np.float32),
        "morton_bits": int(bits),
        "sorted_node_ids": np.asarray(sorted_node_ids, dtype=np.int32),
        "sorted_points": np.asarray(sorted_points, dtype=np.float32),
        "sorted_seg_ids": np.asarray(sorted_seg_ids, dtype=np.int32),
        "point_leaf_ids": point_leaf_ids,
        "node_point_count": np.asarray(np.asarray(node_end, dtype=np.int32) - np.asarray(node_start, dtype=np.int32), dtype=np.int32),
        "node_start": np.asarray(node_start, dtype=np.int32),
        "node_end": np.asarray(node_end, dtype=np.int32),
        "node_level": node_level_arr,
        "node_center": np.asarray(node_center, dtype=np.float32),
        "node_half": np.asarray(node_half, dtype=np.float32),
        "node_parent": np.asarray(node_parent, dtype=np.int32),
        "node_children": np.asarray(node_children, dtype=np.int32),
        "node_is_leaf": node_is_leaf_arr,
        "leaf_ids": np.asarray(leaf_ids, dtype=np.int32),
        "upsweep_node_ids": upsweep_node_ids,
        "upsweep_level_offsets": upsweep_level_offsets,
        "node_count": int(len(node_start)),
        "leaf_count": int(len(leaf_ids)),
        "max_depth": int(max_depth),
        "runtime_state": None,
        "lambda_bin_edges": None,
        "lambda_bin_centers": None,
    }
    context["treecode_context"] = treecode
    return treecode


def _cext_treecode_init_lambda_bins(treecode: dict, ext_state: dict) -> tuple[np.ndarray, np.ndarray]:
    edges = treecode.get("lambda_bin_edges")
    centers = treecode.get("lambda_bin_centers")
    if edges is not None and centers is not None:
        return np.asarray(edges, dtype=np.float32), np.asarray(centers, dtype=np.float32)
    lambda_gl = np.asarray(ext_state["lambda_iv_gl"], dtype=np.float32).reshape(-1)
    finite = lambda_gl[np.isfinite(lambda_gl) & (lambda_gl > 0.0)]
    if finite.size <= 0:
        finite = np.asarray([1.0e-6], dtype=np.float32)
    lam_min = max(float(np.min(finite)), 1.0e-8)
    lam_max = max(float(np.max(finite)), lam_min * (1.0 + 1.0e-6))
    n_bins = max(int(treecode.get("lambda_bins", _state.CEXT_TREECODE_LAMBDA_BINS)), 1)
    if n_bins <= 1 or lam_max <= lam_min * (1.0 + 1.0e-6):
        centers = np.asarray([math.sqrt(lam_min * lam_max)], dtype=np.float32)
        edges = np.asarray([lam_min, lam_max], dtype=np.float32)
    else:
        edges = np.geomspace(lam_min, lam_max, n_bins + 1).astype(np.float32)
        centers = np.sqrt(edges[:-1] * edges[1:]).astype(np.float32)
    treecode["lambda_bin_edges"] = np.asarray(edges, dtype=np.float32)
    treecode["lambda_bin_centers"] = np.asarray(centers, dtype=np.float32)
    return np.asarray(edges, dtype=np.float32), np.asarray(centers, dtype=np.float32)


def _ensure_cext_treecode_runtime_state(context: dict, treecode: dict, ext_state: dict) -> dict:
    if _state._cp is None:
        raise RuntimeError("CuPy is not available.")
    state = treecode.get("runtime_state")
    gl_order = int(np.asarray(context["gl_points_si"]).shape[1])
    nseg = int(np.asarray(context["gl_points_si"]).shape[0])
    n_target_nodes = int(max(nseg * gl_order, 1))
    n_nodes = int(treecode["node_count"])
    n_points = int(np.asarray(treecode["sorted_node_ids"]).size)
    n_bins = max(int(treecode.get("lambda_bins", _state.CEXT_TREECODE_LAMBDA_BINS)), 1)
    if isinstance(state, dict):
        if (
            int(state.get("n_target_nodes", -1)) == n_target_nodes
            and int(state.get("n_tree_nodes", -1)) == n_nodes
            and int(state.get("n_points", -1)) == n_points
            and int(state.get("n_bins", -1)) == n_bins
        ):
            return state
    static = _ensure_cext_gpu_static(context)
    state = {
        "n_target_nodes": int(n_target_nodes),
        "n_tree_nodes": int(n_nodes),
        "n_points": int(n_points),
        "n_bins": int(n_bins),
        "sorted_points": _state._cp.asarray(np.asarray(treecode["sorted_points"], dtype=np.float32)),
        "sorted_seg_ids": _state._cp.asarray(np.asarray(treecode["sorted_seg_ids"], dtype=np.int32)),
        "point_leaf_ids": _state._cp.asarray(np.asarray(treecode["point_leaf_ids"], dtype=np.int32)),
        "node_start": _state._cp.asarray(np.asarray(treecode["node_start"], dtype=np.int32)),
        "node_end": _state._cp.asarray(np.asarray(treecode["node_end"], dtype=np.int32)),
        "node_point_count": _state._cp.asarray(np.asarray(treecode["node_point_count"], dtype=np.int32)),
        "node_center": _state._cp.asarray(np.asarray(treecode["node_center"], dtype=np.float32)),
        "node_half": _state._cp.asarray(np.asarray(treecode["node_half"], dtype=np.float32)),
        "node_children": _state._cp.asarray(np.asarray(treecode["node_children"], dtype=np.int32)),
        "node_is_leaf": _state._cp.asarray(np.asarray(treecode["node_is_leaf"], dtype=np.uint8)),
        "upsweep_node_ids": _state._cp.asarray(np.asarray(treecode["upsweep_node_ids"], dtype=np.int32)),
        "upsweep_level_offsets": _state._cp.asarray(np.asarray(treecode["upsweep_level_offsets"], dtype=np.int32)),
        "all_target_seg_ids": static["all_target_seg_ids"],
        "sorted_lambda": _state._cp.zeros((max(n_points, 1),), dtype=_state._cp.float32),
        "sorted_q": _state._cp.zeros((max(n_points, 1),), dtype=_state._cp.float32),
        "active_seg_mask": _state._cp.ones((max(nseg, 1),), dtype=_state._cp.uint8),
        "sorted_point_active": _state._cp.ones((max(n_points, 1),), dtype=_state._cp.uint8),
        "bin_edges": _state._cp.zeros((max(n_bins + 1, 2),), dtype=_state._cp.float32),
        "node_total_mass": _state._cp.zeros((max(n_bins, 1), max(n_nodes, 1)), dtype=_state._cp.float32),
        "node_total_dipole": _state._cp.zeros((max(n_bins, 1), max(n_nodes, 1), 3), dtype=_state._cp.float32),
        "node_active_mass": _state._cp.zeros((max(n_bins, 1), max(n_nodes, 1)), dtype=_state._cp.float32),
        "node_active_dipole": _state._cp.zeros((max(n_bins, 1), max(n_nodes, 1), 3), dtype=_state._cp.float32),
        "node_active_count": _state._cp.zeros((max(n_nodes, 1),), dtype=_state._cp.int32),
        "lambda_centers": _state._cp.zeros((max(n_bins, 1),), dtype=_state._cp.float32),
        "out_total": _state._cp.zeros((max(nseg, 1), max(gl_order, 1)), dtype=_state._cp.float32),
        "metrics": _state._cp.zeros((3,), dtype=_state._cp.uint64),
    }
    treecode["runtime_state"] = state
    return state


def _sync_cext_treecode_runtime_state(treecode: dict, ext_state: dict, runtime_state: dict) -> np.ndarray:
    sorted_node_ids = np.asarray(treecode["sorted_node_ids"], dtype=np.int32)
    q_sorted = np.asarray(ext_state["q_weighted_gl"], dtype=np.float32).reshape(-1)[sorted_node_ids] if sorted_node_ids.size else np.zeros((0,), dtype=np.float32)
    lam_sorted = np.asarray(ext_state["lambda_iv_gl"], dtype=np.float32).reshape(-1)[sorted_node_ids] if sorted_node_ids.size else np.zeros((0,), dtype=np.float32)
    if q_sorted.size:
        runtime_state["sorted_q"][: q_sorted.size].set(np.asarray(q_sorted, dtype=np.float32))
        runtime_state["sorted_lambda"][: lam_sorted.size].set(np.asarray(lam_sorted, dtype=np.float32))
    edges, centers = _cext_treecode_init_lambda_bins(treecode, ext_state)
    active_mask = np.asarray(ext_state.get("treecode_active_source_mask", np.ones((treecode["nseg"],), dtype=bool)), dtype=bool).reshape(-1)
    if active_mask.size != int(treecode["nseg"]):
        active_mask = np.ones((int(treecode["nseg"]),), dtype=bool)
    runtime_state["active_seg_mask"][: active_mask.size].set(np.asarray(active_mask, dtype=np.uint8))
    runtime_state["sorted_point_active"][:] = runtime_state["active_seg_mask"][runtime_state["sorted_seg_ids"]]
    runtime_state["bin_edges"][: edges.size].set(np.asarray(edges, dtype=np.float32))
    runtime_state["lambda_centers"][: centers.size].set(centers)
    runtime_state["metrics"].fill(np.uint64(0))
    return np.asarray(centers, dtype=np.float32)


def _get_cext_treecode_deposit_kernel():
    # Mutable runtime state is centralized in configuration._legacy_state.
    if _state._CEXT_TREECODE_DEPOSIT_KERNEL is not None:
        return _state._CEXT_TREECODE_DEPOSIT_KERNEL
    if _state._cp is None:
        raise RuntimeError("CuPy is not available.")
    _state.code = load_cuda_source("cext_treecode_deposit_kernel.cu")
    _state._CEXT_TREECODE_DEPOSIT_KERNEL = _state._cp.RawKernel(_state.code, "cext_treecode_deposit_kernel")
    return _state._CEXT_TREECODE_DEPOSIT_KERNEL


def _get_cext_treecode_upsweep_kernel():
    # Mutable runtime state is centralized in configuration._legacy_state.
    if _state._CEXT_TREECODE_UPSWEEP_KERNEL is not None:
        return _state._CEXT_TREECODE_UPSWEEP_KERNEL
    if _state._cp is None:
        raise RuntimeError("CuPy is not available.")
    _state.code = load_cuda_source("cext_treecode_upsweep_kernel.cu")
    _state._CEXT_TREECODE_UPSWEEP_KERNEL = _state._cp.RawKernel(_state.code, "cext_treecode_upsweep_kernel")
    return _state._CEXT_TREECODE_UPSWEEP_KERNEL


def _get_cext_treecode_kernel():
    # Mutable runtime state is centralized in configuration._legacy_state.
    if _state._CEXT_TREECODE_KERNEL is not None:
        return _state._CEXT_TREECODE_KERNEL
    if _state._cp is None:
        raise RuntimeError("CuPy is not available.")
    _state.code = load_cuda_source("cext_treecode_kernel.cu")
    _state._CEXT_TREECODE_KERNEL = _state._cp.RawKernel(_state.code, "cext_treecode_kernel")
    return _state._CEXT_TREECODE_KERNEL


def _compute_cext_treecode_gpu(context: dict, treecode: dict, ext_state: dict) -> tuple[np.ndarray, dict[str, float | int]]:
    if _state._cp is None:
        raise RuntimeError("CuPy is not available.")
    t_aggregate = perf_counter()
    state = _ensure_cext_treecode_runtime_state(context, treecode, ext_state)
    centers = _sync_cext_treecode_runtime_state(treecode, ext_state, state)
    n_bins = int(max(centers.size, 1))
    state["node_total_mass"].fill(_state._cp.float32(0.0))
    state["node_total_dipole"].fill(_state._cp.float32(0.0))
    state["node_active_mass"].fill(_state._cp.float32(0.0))
    state["node_active_dipole"].fill(_state._cp.float32(0.0))
    state["node_active_count"].fill(np.int32(0))
    n_points = int(state["n_points"])
    if n_points > 0:
        threads = 256
        blocks = (n_points + threads - 1) // threads
        deposit_kernel = _get_cext_treecode_deposit_kernel()
        deposit_kernel(
            (blocks,),
            (threads,),
            (
                state["point_leaf_ids"],
                state["sorted_points"].ravel(),
                state["sorted_lambda"],
                state["sorted_q"],
                state["sorted_point_active"],
                state["node_center"].ravel(),
                state["bin_edges"],
                np.int32(n_bins),
                np.int32(int(treecode["node_count"])),
                np.int32(n_points),
                state["node_total_mass"].ravel(),
                state["node_total_dipole"].ravel(),
                state["node_active_mass"].ravel(),
                state["node_active_dipole"].ravel(),
                state["node_active_count"],
            ),
        )
        level_offsets = np.asarray(treecode["upsweep_level_offsets"], dtype=np.int32)
        upsweep_kernel = _get_cext_treecode_upsweep_kernel()
        for level_idx in range(max(level_offsets.size - 1, 0)):
            lo = int(level_offsets[level_idx])
            hi = int(level_offsets[level_idx + 1])
            if hi <= lo:
                continue
            n_level = hi - lo
            blocks_level = (n_level + threads - 1) // threads
            upsweep_kernel(
                (blocks_level,),
                (threads,),
                (
                    state["upsweep_node_ids"][lo:hi],
                    state["node_children"].ravel(),
                    state["node_center"].ravel(),
                    np.int32(n_bins),
                    np.int32(n_level),
                    np.int32(int(treecode["node_count"])),
                    state["node_total_mass"].ravel(),
                    state["node_total_dipole"].ravel(),
                    state["node_active_mass"].ravel(),
                    state["node_active_dipole"].ravel(),
                    state["node_active_count"],
                ),
            )
    _state._cp.cuda.Stream.null.synchronize()
    t_aggregate = perf_counter() - t_aggregate
    static = _ensure_cext_gpu_static(context)
    gl_order = int(np.asarray(context["gl_points_si"]).shape[1])
    nseg = int(np.asarray(context["gl_points_si"]).shape[0])
    target_count = int(nseg)
    out_total = state["out_total"][:target_count]
    out_total.fill(_state._cp.float32(0.0))
    threads = 128
    blocks = (target_count * gl_order + threads - 1) // threads
    kernel = _get_cext_treecode_kernel()
    global_cap = float(np.nanmax(np.asarray(ext_state.get("seg_cap_gl", np.zeros((0,), dtype=np.float32)), dtype=float))) if np.asarray(ext_state.get("seg_cap_gl", ())).size else 0.0
    t_traversal = perf_counter()
    kernel(
        (blocks,),
        (threads,),
        (
            state["all_target_seg_ids"],
            static["gl_points_si"].ravel(),
            static["radii_si"],
            static["exclude_idx"].ravel(),
            static["exclude_count"],
            state["sorted_points"].ravel(),
            state["sorted_seg_ids"],
            state["sorted_lambda"],
            state["sorted_q"],
            state["node_start"],
            state["node_end"],
            state["node_center"].ravel(),
            state["node_half"],
            state["node_children"].ravel(),
            state["node_is_leaf"],
            state["node_point_count"],
            state["node_active_count"],
            state["sorted_point_active"],
            state["node_total_mass"].ravel(),
            state["node_total_dipole"].ravel(),
            state["node_active_mass"].ravel(),
            state["node_active_dipole"].ravel(),
            state["lambda_centers"],
            np.int32(n_bins),
            np.int32(gl_order),
            np.int32(int(np.asarray(context["exclude_idx"]).shape[1])),
            np.int32(int(treecode["node_count"])),
            np.int32(target_count),
            np.int32(int(treecode.get("order_mode", 0))),
            np.float32(float(treecode.get("theta", _state.CEXT_TREECODE_THETA))),
            np.float32(float(treecode.get("near_radius_si", 0.0))),
            np.float32(float(context["diffusivity_si"])),
            np.float32(float(_state.CEXT_WINDOW_FACTOR)),
            np.float32(global_cap),
            out_total.ravel(),
            state["metrics"],
        ),
    )
    _state._cp.cuda.Stream.null.synchronize()
    t_traversal = perf_counter() - t_traversal
    t_download = perf_counter()
    c_ext_new = _state._cp.asnumpy(out_total)
    metrics = _state._cp.asnumpy(state["metrics"])
    _state._cp.cuda.Stream.null.synchronize()
    t_download = perf_counter() - t_download
    return np.asarray(c_ext_new, dtype=np.float32), {
        "aggregate_s": float(t_aggregate),
        "traversal_s": float(t_traversal),
        "transfer_s": float(t_download),
        "exact_s": 0.0,
        "accepted_nodes": int(metrics[0]) if metrics.size > 0 else 0,
        "opened_nodes": int(metrics[1]) if metrics.size > 1 else 0,
        "exact_pairs": int(metrics[2]) if metrics.size > 2 else 0,
    }


def _estimate_cext_tail_active_core(context: dict, ext_state: dict, mapped_gl: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    current = np.asarray(ext_state["c_ext_gl"], dtype=np.float32)
    mapped = np.asarray(mapped_gl, dtype=np.float32)
    q_weighted = np.asarray(ext_state.get("q_weighted_gl", np.zeros_like(mapped)), dtype=np.float32)
    if current.shape != mapped.shape:
        return np.zeros((0,), dtype=np.int32), np.zeros((0,), dtype=np.float32)
    delta_seg = np.max(np.abs(mapped - current), axis=1).astype(np.float32, copy=False)
    q_seg = np.max(np.abs(q_weighted), axis=1).astype(np.float32, copy=False) if q_weighted.ndim == 2 else np.zeros((current.shape[0],), dtype=np.float32)
    bound = np.maximum(delta_seg, np.sqrt(np.maximum(q_seg, np.float32(0.0)))).astype(np.float32, copy=False)
    scale = max(float(np.max(np.abs(np.asarray(mapped, dtype=float)))) if mapped.size else 0.0, float(_state.VESS_CONC_FLOOR))
    thresh = max(float(_state.CEXT_TAIL_CORE_ABS_THRESHOLD), float(_state.CEXT_TAIL_CORE_REL_THRESHOLD) * scale)
    core = np.flatnonzero(bound > thresh).astype(np.int32, copy=False)
    if core.size > int(_state.CEXT_TAIL_TRIGGER_ACTIVE_COUNT):
        order = np.argsort(bound[core], kind="stable")[::-1][: int(_state.CEXT_TAIL_TRIGGER_ACTIVE_COUNT)]
        core = np.asarray(core[order], dtype=np.int32)
    return core, bound


def _cext_should_enter_tail_mode(residual_history: list[float], core_size: int, *, iter_idx: int) -> bool:
    if str(_state.CEXT_TAIL_SOLVER).strip().lower() == "none":
        return False
    if int(iter_idx) < int(_state.CEXT_TAIL_TRIGGER_START_ITER):
        return False
    if core_size <= 0 or core_size > int(_state.CEXT_TAIL_TRIGGER_ACTIVE_COUNT):
        return False
    stall_iters = max(int(_state.CEXT_TAIL_TRIGGER_STALL_ITERS), 2)
    if len(residual_history) < stall_iters:
        return False
    recent = np.asarray(residual_history[-stall_iters:], dtype=float)
    best = float(np.min(recent))
    first = float(recent[0])
    if np.isfinite(first) and np.isfinite(best) and best > float(_state.CEXT_TAIL_TRIGGER_IMPROVEMENT_RATIO) * max(first, 1.0e-30):
        return True
    if np.any(recent < float(_state.CEXT_TAIL_REBOUND_ARM_REL)) and recent[-1] > float(_state.CEXT_TAIL_REBOUND_REL):
        return True
    return False


def _evaluate_cext_treecode_map(
    context: dict,
    treecode: dict,
    ext_state_base: dict,
    *,
    c_ext_candidate: np.ndarray,
    inlet_concentration: float,
    vmax: float,
    km: float,
    chb_max: np.ndarray,
    fluid_mode: str,
    frozen_backend: str,
) -> tuple[np.ndarray, dict, str]:
    ext_trial = {
        "c_ext_gl": np.asarray(c_ext_candidate, dtype=np.float32).copy(),
        "c_iv_gl": np.asarray(ext_state_base["c_iv_gl"], dtype=np.float32).copy(),
        "cin_seg": np.asarray(ext_state_base["cin_seg"], dtype=np.float32).copy(),
        "cout_seg": np.asarray(ext_state_base["cout_seg"], dtype=np.float32).copy(),
        "vmax": float(vmax),
        "km": float(km),
        "window_factor": float(_state.CEXT_WINDOW_FACTOR),
    }
    cin_seg, cout_seg, c_iv_gl, frozen_backend, _ = _run_topdown_ext_frozen_step(
        context,
        ext_trial,
        inlet_concentration=float(inlet_concentration),
        vmax=float(vmax),
        km=float(km),
        chb_max=np.asarray(chb_max, dtype=np.float32),
        fluid_mode=fluid_mode,
        frozen_backend=frozen_backend,
    )
    ext_trial["cin_seg"] = np.asarray(cin_seg, dtype=np.float32)
    ext_trial["cout_seg"] = np.asarray(cout_seg, dtype=np.float32)
    ext_trial["c_iv_gl"] = np.asarray(c_iv_gl, dtype=np.float32)
    _build_cext_iteration_cache(context, ext_trial)
    mapped_gl, _ = _compute_cext_treecode_gpu(context, treecode, ext_trial)
    return np.asarray(mapped_gl, dtype=np.float32), ext_trial, frozen_backend


def _solve_cext_treecode_active_core_nk(
    context: dict,
    treecode: dict,
    ext_state: dict,
    *,
    core_seg_ids: np.ndarray,
    inlet_concentration: float,
    vmax: float,
    km: float,
    chb_max: np.ndarray,
    fluid_mode: str,
    frozen_backend: str,
) -> tuple[np.ndarray, dict]:
    core_ids = np.asarray(core_seg_ids, dtype=np.int32).reshape(-1)
    gl_order = int(np.asarray(ext_state["c_ext_gl"]).shape[1])
    x = np.asarray(ext_state["c_ext_gl"][core_ids], dtype=np.float32).reshape(-1).copy()
    base_full = np.asarray(ext_state["c_ext_gl"], dtype=np.float32).copy()
    gmres_iters_total = 0
    nonlinear_iters = 0
    success = False
    last_rel = float("inf")

    def build_full(active_flat: np.ndarray) -> np.ndarray:
        full = np.asarray(base_full, dtype=np.float32).copy()
        full[core_ids] = np.asarray(active_flat, dtype=np.float32).reshape((-1, gl_order))
        return full

    def residual(active_flat: np.ndarray) -> tuple[np.ndarray, np.ndarray, dict, str]:
        full = build_full(active_flat)
        mapped_gl, trial_state, backend_out = _evaluate_cext_treecode_map(
            context,
            treecode,
            ext_state,
            c_ext_candidate=full,
            inlet_concentration=inlet_concentration,
            vmax=vmax,
            km=km,
            chb_max=chb_max,
            fluid_mode=fluid_mode,
            frozen_backend=frozen_backend,
        )
        return (
            np.asarray(mapped_gl[core_ids], dtype=np.float32).reshape(-1) - np.asarray(active_flat, dtype=np.float32).reshape(-1),
            mapped_gl,
            trial_state,
            backend_out,
        )

    mapped_last = np.asarray(ext_state["c_ext_gl"], dtype=np.float32).copy()
    state_last = ext_state
    backend_last = frozen_backend
    if not _state._HAVE_SCIPY_SPARSE or _splinalg is None:
        for _ in range(max(int(_state.CEXT_TAIL_MAX_NONLINEAR_ITERS), 1)):
            nonlinear_iters += 1
            res, mapped_last, state_last, backend_last = residual(x)
            last_rel = float(np.max(np.abs(res))) / max(float(np.max(np.abs(mapped_last[core_ids]))) if core_ids.size else 0.0, float(_state.VESS_CONC_FLOOR))
            x = np.asarray(x + np.float32(0.5) * res, dtype=np.float32)
            if last_rel <= max(float(_state.CEXT_VESS_COUPLING_REL_TOL), 1.0e-3):
                success = True
                break
    else:
        for _ in range(max(int(_state.CEXT_TAIL_MAX_NONLINEAR_ITERS), 1)):
            nonlinear_iters += 1
            res, mapped_last, state_last, backend_last = residual(x)
            res_norm = float(np.max(np.abs(res))) if res.size else 0.0
            last_rel = res_norm / max(float(np.max(np.abs(mapped_last[core_ids]))) if core_ids.size else 0.0, float(_state.VESS_CONC_FLOOR))
            if last_rel <= max(float(_state.CEXT_VESS_COUPLING_REL_TOL), 1.0e-3):
                success = True
                break
            eps_base = 1.0e-4

            def mv(v: np.ndarray) -> np.ndarray:
                v_arr = np.asarray(v, dtype=np.float32).reshape(-1)
                scale = float(np.linalg.norm(v_arr))
                if scale <= 1.0e-30:
                    return -v_arr
                eps = np.float32(eps_base / scale)
                res_p, _, _, _ = residual(np.asarray(x + eps * v_arr, dtype=np.float32))
                return np.asarray((res_p - res) / eps, dtype=np.float32)

            linop = _splinalg.LinearOperator((x.size, x.size), matvec=mv, dtype=np.float32)
            gmres_counter = {"n": 0}

            def gmres_cb(_rk=None):
                gmres_counter["n"] += 1

            step, info = _splinalg.gmres(
                linop,
                -np.asarray(res, dtype=np.float32),
                restart=max(int(_state.CEXT_TAIL_GMRES_RESTART), 4),
                maxiter=max(int(_state.CEXT_TAIL_GMRES_MAXITER), 8),
                callback=gmres_cb,
            )
            gmres_iters_total += int(gmres_counter["n"])
            if info != 0 or not np.all(np.isfinite(step)):
                x = np.asarray(x + np.float32(0.5) * res, dtype=np.float32)
                continue
            alpha = 1.0
            accepted = False
            for _ls in range(8):
                trial_x = np.asarray(x + np.float32(alpha) * np.asarray(step, dtype=np.float32), dtype=np.float32)
                res_trial, mapped_trial, state_trial, backend_trial = residual(trial_x)
                trial_norm = float(np.max(np.abs(res_trial))) if res_trial.size else 0.0
                if trial_norm < res_norm:
                    x = np.asarray(trial_x, dtype=np.float32)
                    mapped_last = np.asarray(mapped_trial, dtype=np.float32)
                    state_last = state_trial
                    backend_last = backend_trial
                    accepted = True
                    break
                alpha *= 0.5
            if not accepted:
                x = np.asarray(x + np.float32(0.5) * res, dtype=np.float32)
        if not success:
            res, mapped_last, state_last, backend_last = residual(x)
            last_rel = float(np.max(np.abs(res))) / max(float(np.max(np.abs(mapped_last[core_ids]))) if core_ids.size else 0.0, float(_state.VESS_CONC_FLOOR))
            success = last_rel <= max(float(_state.CEXT_VESS_COUPLING_REL_TOL), 1.0e-3)
    full_out = np.asarray(base_full, dtype=np.float32).copy()
    full_out[core_ids] = np.asarray(x, dtype=np.float32).reshape((-1, gl_order))
    return full_out, {
        "success": bool(success),
        "rel_residual": float(last_rel),
        "gmres_iters": int(gmres_iters_total),
        "nonlinear_iters": int(nonlinear_iters),
        "mapped_gl": np.asarray(mapped_last, dtype=np.float32),
        "state": state_last,
        "frozen_backend": backend_last,
    }


def _rebuild_cext_hybrid_frozen_cache(
    context: dict,
    ext_state: dict,
    hybrid: dict,
    frozen_source_mask: np.ndarray,
    *,
    runtime_state: dict | None = None,
) -> tuple[object, object, dict[str, float]]:
    if _state._cp is None:
        raise RuntimeError("CuPy is not available.")
    state = runtime_state if isinstance(runtime_state, dict) else _ensure_cext_hybrid_bg_runtime_state(context, hybrid, ext_state)
    mass_grids_g, t_deposit = _cext_hybrid_deposit_sources_gpu(
        context,
        hybrid,
        ext_state,
        source_mask=frozen_source_mask,
        runtime_state=state,
    )
    phi_grids_g, t_fft, bg_solver_mode = _cext_hybrid_solve_background_fft_gpu(
        context,
        hybrid,
        mass_grids_g,
        init_phi_grids_g=hybrid.get("frozen_phi_guess_g"),
    )
    hybrid["frozen_phi_guess_g"] = phi_grids_g
    return mass_grids_g, phi_grids_g, {
        "deposit_s": float(t_deposit),
        "fft_s": float(t_fft),
        "bg_solver_mode": str(bg_solver_mode),
    }


__all__ = ['_part1by2_64', '_morton3d_codes', '_treecode_child_offset', '_build_cext_treecode_context', '_cext_treecode_init_lambda_bins', '_ensure_cext_treecode_runtime_state', '_sync_cext_treecode_runtime_state', '_get_cext_treecode_deposit_kernel', '_get_cext_treecode_upsweep_kernel', '_get_cext_treecode_kernel', '_compute_cext_treecode_gpu', '_estimate_cext_tail_active_core', '_cext_should_enter_tail_mode', '_evaluate_cext_treecode_map', '_solve_cext_treecode_active_core_nk', '_rebuild_cext_hybrid_frozen_cache']
