"""Legacy TissueSim argument parser.

Generated by a behavior-preserving extraction from the frozen TissueSim
baseline. Dependencies are bound by the temporary compatibility facade while
the new typed subsystem APIs replace the legacy global runtime contract.
"""

from __future__ import annotations

from cascade.configuration import _legacy_state as _state
from cascade.runtime import _dependencies

for _dependency_name, _dependency_value in vars(_dependencies).items():
    if not _dependency_name.startswith("__"):
        globals().setdefault(_dependency_name, _dependency_value)
del _dependency_name, _dependency_value

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Tree flow + Greens concentration script.")
    parser.add_argument("--n-closest-vessels", type=int, default=2, help="n_closest_vessels for growth.")
    parser.add_argument("--n-points", type=int, default=50, help="n_points for candidate terminal sampling.")
    parser.add_argument(
        "--weighted-sampling",
        type=str,
        default="false",
        choices=("true", "false"),
        help="Use weighted mesh-cell sampling: true/false (default: false).",
    )
    parser.add_argument(
        "--ignore-collisions",
        type=str,
        default="true",
        choices=("true", "false"),
        help="Skip collision checks during add_vessel: true/false (default: false).",
    )
    parser.add_argument(
        "--allow-inside-vessels",
        type=str,
        default="true",
        choices=("true", "false"),
        help="Allow candidate growth points inside existing vessels.",
    )
    parser.add_argument("--ef", type=int, default=20, help="USearchTree expansion_search (ef) for kNN queries.")
    parser.add_argument("--max-iter", type=int, default=20, help="Optimizer max_iter passed to add_vessel.")
    parser.add_argument(
        "--n-equal-bifurcations",
        type=int,
        default=200000,
        help="Switch to equal-bifurcation growth after this many terminals (disable with < 0).",
    )
    parser.add_argument(
        "--line-profile",
        type=str,
        default="false",
        choices=("true", "false"),
        help="Enable line-level profiling (requires line_profiler).",
    )
    parser.add_argument(
        "--line-profile-out",
        type=str,
        default="TissueSim_line_profile.txt",
        help="Output path for line-level profiler stats.",
    )
    parser.add_argument("--profile", type=str, default="false", choices=("true", "false"),
                        help="Enable cProfile for the run.")
    parser.add_argument("--profile-out", type=str, default="TissueSim_profile.prof",
                        help="Output path for profiler stats.")
    parser.add_argument(
        "--plot-flow",
        type=str,
        default="false",
        choices=("true", "false"),
        help="Plot flow magnitude on each tree before continuing.",
    )
    parser.add_argument(
        "--plot-concentration",
        type=str,
        default="false",
        choices=("true", "false"),
        help="Plot vessel concentration on each tree before continuing.",
    )
    parser.add_argument(
        "--plot-concentration-points",
        type=str,
        default="false",
        choices=("true", "false"),
        help="Plot vessel + tissue concentration on each tree before continuing.",
    )
    parser.add_argument(
        "--plot-viability",
        type=str,
        default="false",
        choices=("true", "false"),
        help="Plot live/dead vessels + points on each tree before continuing.",
    )

    parser.add_argument(
        "--concentration-solver",
        type=str,
        default=_state.CONCENTRATION_SOLVER,
        choices=("network_ext", "network_ext_hybrid_bg", "topdown_ext", "topdown_ext_hybrid_bg", "network", "topdown", "topdown_ext_treecode"),
        help="Channel concentration solver: network/top-down with direct, FFT/hybrid, or uncoupled oxygen transport.",
    )
    parser.add_argument(
        "--cext-accel",
        type=str,
        default=_state.CEXT_ACCEL_MODE,
        choices=("cpu", "gpu", "auto"),
        help="External-field backend for topdown_ext. Auto uses GPU when available.",
    )
    parser.add_argument(
        "--cext-frozen-accel",
        type=str,
        default=_state.CEXT_FROZEN_ACCEL_MODE,
        choices=("cpu", "gpu", "auto"),
        help="Frozen intravessel backend for topdown_ext. Auto uses GPU when available.",
    )
    parser.add_argument(
        "--finite-radius-o2-terms",
        type=str,
        default=_state.FINITE_RADIUS_O2_TERMS,
        choices=("none", "monopole", "dipole", "both"),
        help="Finite-radius O(a^2) source terms to include in Cext/tissue Green's fields.",
    )
    parser.add_argument(
        "--lumen-wall-closure",
        type=str,
        default=_state.LUMEN_WALL_CLOSURE,
        choices=("wellmixed", "graetz"),
        help="Lumen wall closure. c_iv_gl remains bulk; Graetz stores true c_wall_gl.",
    )
    parser.add_argument(
        "--graetz-n-radial",
        type=int,
        default=_state.GRAETZ_N_RADIAL,
        help="Radial FE nodes for the Graetz lumen closure.",
    )
    parser.add_argument(
        "--graetz-n-modes",
        type=int,
        default=_state.GRAETZ_N_MODES,
        help="Retained radial eigenmodes for the Graetz lumen closure.",
    )
    parser.add_argument(
        "--graetz-max-fp-iters",
        type=int,
        default=_state.GRAETZ_MAX_FP_ITERS,
        help="Fixed-point iterations for wall-lambda/Biot coupling in each frozen Graetz step.",
    )
    parser.add_argument(
        "--graetz-profile",
        type=str,
        default=_state.GRAETZ_VELOCITY_PROFILE,
        choices=("poiseuille", "plug"),
        help="Velocity profile used in the Graetz eigenproblem.",
    )
    parser.add_argument(
        "--lumen-diffusivity-cm2-s",
        type=float,
        default=None,
        help="Override lumen molecular diffusivity in cm^2/s for Graetz radial diffusion.",
    )
    parser.add_argument(
        "--cext-init-mode",
        type=str,
        default=_state.CEXT_INIT_MODE,
        choices=("zero", "decoupled_greens"),
        help="topdown_ext Cext initialization mode. 'decoupled_greens' runs one zero-Cext predictor before Picard.",
    )
    parser.add_argument(
        "--cext-lambda-source",
        type=str,
        default=_state.CEXT_LAMBDA_SOURCE,
        choices=("lambda_vv", "lambda_t"),
        help="Lambda field used by the Cext Green's evaluator. lambda_t uses lambda_tissue(c_wall, Cext).",
    )
    parser.add_argument(
        "--cext-window-factor",
        type=float,
        default=_state.CEXT_WINDOW_FACTOR,
        help="External-field interaction window factor. Set 0 to collapse topdown_ext to topdown.",
    )
    parser.add_argument(
        "--cext-vess-coupling-max-iter",
        type=int,
        default=_state.CEXT_VESS_COUPLING_MAX_ITER,
        help="Maximum outer Picard iterations for topdown_ext vessel coupling.",
    )
    parser.add_argument(
        "--cext-vess-coupling-tol",
        type=float,
        default=_state.CEXT_VESS_COUPLING_TOL,
        help="Convergence tolerance for topdown_ext vessel coupling.",
    )
    parser.add_argument(
        "--cext-vess-coupling-rel-tol",
        type=float,
        default=_state.CEXT_VESS_COUPLING_REL_TOL,
        help="Relative convergence tolerance for topdown_ext vessel coupling. Set 0 to disable.",
    )
    parser.add_argument(
        "--cext-vess-coupling-omega",
        type=float,
        default=_state.CEXT_VESS_COUPLING_OMEGA,
        help="Relaxation factor for topdown_ext vessel coupling.",
    )
    parser.add_argument(
        "--cext-vess-coupling-accel",
        type=str,
        default=_state.CEXT_VESS_COUPLING_ACCEL,
        choices=("none", "aitken", "anderson"),
        help="Nonlinear acceleration mode for topdown_ext vessel coupling.",
    )
    parser.add_argument(
        "--cext-vess-coupling-omega-min",
        type=float,
        default=_state.CEXT_VESS_COUPLING_OMEGA_MIN,
        help="Minimum adaptive relaxation factor for topdown_ext vessel coupling.",
    )
    parser.add_argument(
        "--cext-vess-coupling-omega-max",
        type=float,
        default=_state.CEXT_VESS_COUPLING_OMEGA_MAX,
        help="Maximum adaptive relaxation factor for topdown_ext vessel coupling.",
    )
    parser.add_argument(
        "--cext-vess-coupling-trust-abs",
        type=float,
        default=_state.CEXT_VESS_COUPLING_TRUST_ABS,
        help="Absolute per-entry trust-region cap for topdown_ext Cext updates.",
    )
    parser.add_argument(
        "--cext-vess-coupling-trust-rel",
        type=float,
        default=_state.CEXT_VESS_COUPLING_TRUST_REL,
        help="Relative per-entry trust-region cap for topdown_ext Cext updates.",
    )
    parser.add_argument(
        "--cext-vess-coupling-anderson-depth",
        type=int,
        default=_state.CEXT_VESS_COUPLING_ANDERSON_DEPTH,
        help="History depth for Anderson acceleration in topdown_ext vessel coupling.",
    )
    parser.add_argument(
        "--cext-vess-coupling-anderson-reg",
        type=float,
        default=_state.CEXT_VESS_COUPLING_ANDERSON_REG,
        help="Tikhonov regularization for Anderson acceleration in topdown_ext vessel coupling.",
    )
    parser.add_argument(
        "--cext-vess-coupling-anderson-start",
        type=int,
        default=_state.CEXT_VESS_COUPLING_ANDERSON_START,
        help="Iteration index at which Anderson acceleration becomes eligible.",
    )
    parser.add_argument(
        "--cext-vess-coupling-anderson-gate-ratio",
        type=float,
        default=_state.CEXT_VESS_COUPLING_ANDERSON_GATE_RATIO,
        help="Residual-ratio threshold below which Anderson acceleration becomes eligible.",
    )
    parser.add_argument(
        "--cext-vess-coupling-anderson-min-stable-iters",
        type=int,
        default=_state.CEXT_VESS_COUPLING_ANDERSON_MIN_STABLE_ITERS,
        help="Number of improving iterations required before Anderson acceleration is allowed.",
    )
    parser.add_argument(
        "--cext-vess-coupling-anderson-omega-gate-factor",
        type=float,
        default=_state.CEXT_VESS_COUPLING_ANDERSON_OMEGA_GATE_FACTOR,
        help="Disable Anderson when adaptive omega falls below omega_min times this factor.",
    )
    parser.add_argument(
        "--cext-vess-coupling-accept-factor",
        type=float,
        default=_state.CEXT_VESS_COUPLING_ACCEL_ACCEPT_FACTOR,
        help="Safeguard factor for accepting Anderson candidate residual predictions.",
    )
    parser.add_argument(
        "--cext-vess-coupling-step-factor",
        type=float,
        default=_state.CEXT_VESS_COUPLING_ACCEL_STEP_FACTOR,
        help="Maximum multiple of the fallback step allowed for accelerated topdown_ext updates.",
    )
    parser.add_argument(
        "--cext-vess-coupling-restart-factor",
        type=float,
        default=_state.CEXT_VESS_COUPLING_ACCEL_RESTART_FACTOR,
        help="Residual growth factor that triggers an Anderson history restart.",
    )
    parser.add_argument(
        "--cext-vess-coupling-best-stall-iters",
        type=int,
        default=_state.CEXT_VESS_COUPLING_BEST_STALL_ITERS,
        help="Stop and revert to the best Cext iterate after this many non-improving iterations. Set 0 to disable.",
    )
    parser.add_argument(
        "--cext-vess-coupling-best-revert-factor",
        type=float,
        default=_state.CEXT_VESS_COUPLING_BEST_REVERT_FACTOR,
        help="Residual growth over the best seen Cext iterate that permits best-seen rollback.",
    )
    parser.add_argument(
        "--cext-vess-coupling-step-reject-factor",
        type=float,
        default=_state.CEXT_VESS_COUPLING_STEP_REJECT_FACTOR,
        help="Reject and retry a Cext update when the next residual exceeds the previous evaluated residual by this factor.",
    )
    parser.add_argument(
        "--cext-vess-coupling-step-retry-factor",
        type=float,
        default=_state.CEXT_VESS_COUPLING_STEP_RETRY_FACTOR,
        help="Multiplier applied to omega when retrying a rejected Cext update.",
    )
    parser.add_argument(
        "--cext-active-set-enable",
        type=str,
        default="true" if _state.CEXT_ACTIVE_SET_ENABLE else "false",
        choices=("true", "false"),
        help="Freeze locally converged source segments and keep their Cext contribution in a cached field.",
    )
    parser.add_argument(
        "--cext-active-set-start",
        type=int,
        default=_state.CEXT_ACTIVE_SET_START,
        help="First outer iteration where converged Cext sources may be moved into the frozen active set cache.",
    )
    parser.add_argument(
        "--cext-active-set-stable-iters",
        type=int,
        default=_state.CEXT_ACTIVE_SET_STABLE_ITERS,
        help="Consecutive locally stable iterations required before a source segment is frozen.",
    )
    parser.add_argument(
        "--cext-active-set-rel-tol",
        type=float,
        default=_state.CEXT_ACTIVE_SET_REL_TOL,
        help="Relative local source-state tolerance used to freeze converged Cext source segments.",
    )
    parser.add_argument(
        "--cext-active-set-abs-tol",
        type=float,
        default=_state.CEXT_ACTIVE_SET_ABS_TOL,
        help="Absolute local source-state tolerance used to freeze converged Cext source segments.",
    )
    parser.add_argument(
        "--cext-active-set-refresh-period",
        type=int,
        default=_state.CEXT_ACTIVE_SET_REFRESH_PERIOD,
        help="Rebuild the frozen-source Cext field every N outer iterations. Set 0 to disable periodic refresh.",
    )
    parser.add_argument(
        "--cext-active-set-min-active-count",
        type=int,
        default=_state.CEXT_ACTIVE_SET_MIN_ACTIVE_COUNT,
        help="Absolute minimum number of active Cext source segments to keep in the nonlinear solve.",
    )
    parser.add_argument(
        "--cext-active-set-min-active-fraction",
        type=float,
        default=_state.CEXT_ACTIVE_SET_MIN_ACTIVE_FRACTION,
        help="Legacy minimum active-source fraction safeguard. Set 0 to disable; absolute count is primary.",
    )
    parser.add_argument(
        "--cext-hybrid-bg-mode",
        type=str,
        default=_state.CEXT_HYBRID_BG_MODE,
        choices=("local_only_nlambda", "local_only", "fft", "hybrid"),
        help=(
            "Cext background mode for topdown_ext_hybrid_bg. "
            "fft is the default regular-grid solve with O2 correction and self-subtraction; "
            "local_only_nlambda is the screened pairwise solve with r <= N*lambda; "
            "hybrid is FFT plus configured local correction."
        ),
    )
    parser.add_argument(
        "--cext-hybrid-bg-grid",
        type=int,
        default=_state.CEXT_HYBRID_BG_GRID,
        help="Regular-grid resolution per axis for local cell lists or the FFT Cext background field.",
    )
    parser.add_argument(
        "--cext-hybrid-bg-lambda-bins",
        type=int,
        default=_state.CEXT_HYBRID_BG_LAMBDA_BINS,
        help="Number of fixed lambda bins used by topdown_ext_hybrid_bg.",
    )
    parser.add_argument(
        "--cext-hybrid-bg-near-radius-mult",
        type=float,
        default=_state.CEXT_HYBRID_BG_NEAR_RADIUS_MULT,
        help="Exact-local correction radius in background-grid spacings for topdown_ext_hybrid_bg. Set 0 for pure-grid fast mode.",
    )
    parser.add_argument(
        "--cext-hybrid-bg-vcycles",
        type=int,
        default=_state.CEXT_HYBRID_BG_VCYCLES,
        help="Hybrid background solve work budget per outer iteration.",
    )
    parser.add_argument(
        "--cext-hybrid-bg-assignment",
        type=str,
        default=_state.CEXT_HYBRID_BG_ASSIGNMENT,
        choices=("cic", "tsc"),
        help="Source deposition assignment for topdown_ext_hybrid_bg.",
    )
    parser.add_argument(
        "--cext-hybrid-bg-solver",
        type=str,
        default=_state.CEXT_HYBRID_BG_SOLVER,
        choices=("auto", "fft", "jacobi"),
        help="Background-grid solver for topdown_ext_hybrid_bg. 'auto' prefers FFT when cuFFT is available.",
    )
    parser.add_argument(
        "--cext-hybrid-bg-enable-source-freezing",
        type=str,
        default="true" if _state.CEXT_HYBRID_BG_ENABLE_SOURCE_FREEZING else "false",
        choices=("true", "false"),
        help="Allow frozen-source caching in the hybrid Cext solver.",
    )
    parser.add_argument(
        "--cext-hybrid-fft-quantile-bins",
        type=str,
        default="true" if _state.CEXT_HYBRID_FFT_QUANTILE_BINS else "false",
        choices=("true", "false"),
        help="Use dynamic quantile lambda bins for the FFT Cext solver.",
    )
    parser.add_argument(
        "--cext-hybrid-fft-o2-correction",
        type=str,
        default="true" if _state.CEXT_HYBRID_FFT_O2_CORRECTION else "false",
        choices=("true", "false"),
        help="Apply the finite-radius O2 moment correction in FFT mode.",
    )
    parser.add_argument(
        "--cext-hybrid-fft-self-subtract",
        type=str,
        default="true" if _state.CEXT_HYBRID_FFT_SELF_SUBTRACT else "false",
        choices=("true", "false"),
        help="Subtract the grid-consistent same-segment self contribution in FFT mode.",
    )
    parser.add_argument(
        "--cext-hybrid-fft-self-sub-target-sampling",
        type=str,
        default=_state.CEXT_HYBRID_FFT_SELF_SUB_TARGET_SAMPLING,
        choices=("cic", "tsc", "matched", "assignment", "source"),
        help="Target stencil used for FFT same-segment self-subtraction.",
    )
    parser.add_argument(
        "--cext-hybrid-fft-self-sub-scale",
        type=float,
        default=_state.CEXT_HYBRID_FFT_SELF_SUB_SCALE,
        help="Scale factor for FFT same-segment self-subtraction.",
    )
    parser.add_argument(
        "--cext-treecode-theta",
        type=float,
        default=_state.CEXT_TREECODE_THETA,
        help="Treecode acceptance ratio theta for topdown_ext_treecode.",
    )
    parser.add_argument(
        "--cext-treecode-order",
        type=int,
        default=_state.CEXT_TREECODE_ORDER,
        help="Treecode far-field order for topdown_ext_treecode. 0=monopole, 1=monopole+dipole.",
    )
    parser.add_argument(
        "--cext-treecode-leaf-nodes",
        type=int,
        default=_state.CEXT_TREECODE_LEAF_NODES,
        help="Maximum source GL nodes per treecode leaf.",
    )
    parser.add_argument(
        "--cext-treecode-lambda-bins",
        type=int,
        default=_state.CEXT_TREECODE_LAMBDA_BINS,
        help="Number of lambda bins used by topdown_ext_treecode.",
    )
    parser.add_argument(
        "--cext-treecode-near-radius-mult",
        type=float,
        default=_state.CEXT_TREECODE_NEAR_RADIUS_MULT,
        help="Near-field exact radius in leaf-cell widths for topdown_ext_treecode.",
    )
    parser.add_argument(
        "--cext-treecode-gpu-local",
        type=str,
        default="true" if _state.CEXT_TREECODE_GPU_LOCAL else "false",
        choices=("true", "false"),
        help="Reserved compatibility switch for the treecode GPU local path.",
    )
    parser.add_argument(
        "--cext-tail-solver",
        type=str,
        default=_state.CEXT_TAIL_SOLVER,
        choices=("none", "active_core_nk"),
        help="Tail solver used by topdown_ext_treecode after fixed-point stall detection.",
    )
    parser.add_argument(
        "--cext-tail-trigger-start-iter",
        type=int,
        default=_state.CEXT_TAIL_TRIGGER_START_ITER,
        help="First outer iteration where the treecode active-core tail solver may activate.",
    )
    parser.add_argument(
        "--cext-tail-trigger-stall-iters",
        type=int,
        default=_state.CEXT_TAIL_TRIGGER_STALL_ITERS,
        help="Number of recent iterations inspected for stalled treecode residual improvement.",
    )
    parser.add_argument(
        "--cext-tail-trigger-active-count",
        type=int,
        default=_state.CEXT_TAIL_TRIGGER_ACTIVE_COUNT,
        help="Maximum active-core size eligible for the treecode Newton-Krylov tail solve.",
    )
    parser.add_argument(
        "--cext-tail-max-nonlinear-iters",
        type=int,
        default=_state.CEXT_TAIL_MAX_NONLINEAR_ITERS,
        help="Maximum nonlinear Newton-Krylov iterations in the treecode tail solve.",
    )
    parser.add_argument(
        "--cext-tail-gmres-restart",
        type=int,
        default=_state.CEXT_TAIL_GMRES_RESTART,
        help="GMRES restart used by the treecode active-core tail solve.",
    )
    parser.add_argument(
        "--cext-tail-gmres-maxiter",
        type=int,
        default=_state.CEXT_TAIL_GMRES_MAXITER,
        help="GMRES maxiter used by the treecode active-core tail solve.",
    )
    parser.add_argument(
        "--cext-target-active-set-enable",
        type=str,
        default="true" if _state.CEXT_TARGET_ACTIVE_SET_ENABLE else "false",
        choices=("true", "false"),
        help="Freeze locally converged target segments when nearby active-source influence is weak.",
    )
    parser.add_argument(
        "--cext-target-active-set-start",
        type=int,
        default=_state.CEXT_TARGET_ACTIVE_SET_START,
        help="First outer iteration where target freezing becomes eligible.",
    )
    parser.add_argument(
        "--cext-target-active-set-stable-iters",
        type=int,
        default=_state.CEXT_TARGET_ACTIVE_SET_STABLE_ITERS,
        help="Consecutive locally stable iterations required before a target can freeze.",
    )
    parser.add_argument(
        "--cext-target-active-set-rel-tol",
        type=float,
        default=_state.CEXT_TARGET_ACTIVE_SET_REL_TOL,
        help="Relative local target-update tolerance for target freezing.",
    )
    parser.add_argument(
        "--cext-target-active-set-abs-tol",
        type=float,
        default=_state.CEXT_TARGET_ACTIVE_SET_ABS_TOL,
        help="Absolute local target-update tolerance for target freezing.",
    )
    parser.add_argument(
        "--cext-target-active-set-min-active-count",
        type=int,
        default=_state.CEXT_TARGET_ACTIVE_SET_MIN_ACTIVE_COUNT,
        help="Absolute minimum number of active Cext targets to keep in the nonlinear solve.",
    )
    parser.add_argument(
        "--cext-target-active-set-neighbor-pad",
        type=int,
        default=_state.CEXT_TARGET_ACTIVE_SET_NEIGHBOR_PAD,
        help="Extra GPU-direct cell padding used when checking conservative target freeze/reactivation influence.",
    )
    parser.add_argument(
        "--cext-grid-cell-factor",
        type=float,
        default=_state.CEXT_GRID_CELL_FACTOR,
        help="Uniform-grid cell size multiplier for Cext candidate search.",
    )
    parser.add_argument(
        "--cext-streaming-target-candidate-slots",
        type=int,
        default=_state.CEXT_STREAMING_TARGET_CANDIDATE_SLOTS,
        help="Approximate max target-to-source candidate slots per streamed Cext batch.",
    )
    parser.add_argument(
        "--cext-gpu-validate-segments",
        type=int,
        default=_state.CEXT_GPU_VALIDATE_SEGMENTS,
        help="Validate the first N target segments in each GPU Cext batch against the CPU kernel.",
    )
    parser.add_argument(
        "--cext-approx-window-scale",
        type=float,
        default=_state.CEXT_APPROX_WINDOW_SCALE,
        help="Optional coarse-query reach scale for Cext candidate precompute. 1.0 keeps the exact default behavior.",
    )
    parser.add_argument(
        "--cext-max-candidates-per-target",
        type=int,
        default=_state.CEXT_MAX_CANDIDATES_PER_TARGET,
        help="Optional coarse-query cap on source candidates per target segment. 0 disables trimming.",
    )
    parser.add_argument(
        "--hematocrit-model",
        type=str,
        default=_state.HEMATOCRIT_MODEL,
        choices=("uniform_tube", "pries_secomb"),
        help="Blood hematocrit model: current uniform discharge-to-tube correction or NetFlowV2/Pries-Secomb bifurcation partitioning.",
    )
    parser.add_argument(
        "--hematocrit-flow-iterations",
        type=int,
        default=_state.HEMATOCRIT_FLOW_ITERATIONS,
        help="Optional viscosity-flow feedback iterations for pries_secomb hematocrit; 0 keeps flow viscosity behavior unchanged.",
    )
    parser.add_argument(
        "--hematocrit-relaxation",
        type=float,
        default=_state.HEMATOCRIT_RELAXATION,
        help="Initial NetFlow-style relaxation factor for optional hematocrit-flow feedback iterations; reduced by 0.8 every fifth iteration.",
    )
    parser.add_argument(
        "--hematocrit-qtol-nl-min",
        type=float,
        default=_state.HEMATOCRIT_QTOL_NL_MIN,
        help="NetFlow-style nonlinear flow convergence tolerance in nl/min.",
    )
    parser.add_argument(
        "--hematocrit-hdtol",
        type=float,
        default=_state.HEMATOCRIT_HDTOL,
        help="NetFlow-style nonlinear discharge hematocrit convergence tolerance.",
    )
    parser.add_argument(
        "--gl-order",
        type=int,
        default=_state.GL_ORDER,
        choices=(5, 9, 20),
        help="Gauss-Legendre points per segment for Greens integral.",
    )
    parser.add_argument(
        "--cext-gl-order",
        type=int,
        default=_state.GL_ORDER_CEXT,
        help="Gauss-Legendre points per segment for explicit vessel Cext coupling.",
    )
    parser.add_argument(
        "--distance-sample-count",
        type=int,
        default=_state.DISTANCE_SAMPLE_COUNT,
        help="Override DISTANCE_SAMPLE_COUNT for tissue/DNC sample points.",
    )
    parser.add_argument(
        "--distance-sample-counts",
        type=str,
        default=None,
        help=(
            "Comma-separated DISTANCE_SAMPLE_COUNT values for timing scaling. "
            "The tree/flow/concentration solve is reused and only tissue sampling is repeated per M."
        ),
    )
    parser.add_argument(
        "--compute-avg-distance-to-channel",
        choices=("true", "false"),
        default="true" if _state.COMPUTE_AVG_DISTANCE_TO_CHANNEL else "false",
        help="Compute avg_distance_to_channel summary metric. Disable to skip the expensive nearest-channel distance diagnostic.",
    )
    parser.add_argument(
        "--target-counts",
        type=str,
        default=None,
        help="Comma-separated override for TARGET_TERMINAL_COUNTS, e.g. 5000000.",
    )
    parser.add_argument(
        "--qin-target",
        type=str,
        nargs="+",
        default=str(_state.QIN_TARGET),
        help=(
            "Target inlet flow rate(s) in uL/min. Accepts one value or a comma/list string, "
            "e.g. 900, 100 200 300, or '(100, 200, 300)'. "
            "Tree cache lookup ignores this value so geometry caches can be reused."
        ),
    )
    parser.add_argument(
        "--nearest-tissue-vessels",
        type=int,
        default=_state.NEAREST_TISSUE_VESSELS,
        help="Override NEAREST_TISSUE_VESSELS.",
    )
    parser.add_argument(
        "--window-factor",
        type=float,
        default=_state.WINDOW_FACTOR,
        help="Override WINDOW_FACTOR.",
    )
    parser.add_argument(
        "--solver-timing-details",
        type=str,
        default="true" if _state.SOLVER_TIMING_DETAILS else "false",
        choices=("true", "false"),
        help="Print detailed sub-timings for concentration and tissue geometry/Greens solves.",
    )
    parser.add_argument(
        "--tissue-cache-chunk-size",
        type=int,
        default=_state.TISSUE_CACHE_CHUNK_SIZE,
        help="Point chunk size for exact tissue geometry cache construction.",
    )
    parser.add_argument(
        "--tissue-kdtree-workers",
        type=int,
        default=_state.TISSUE_KDTREE_WORKERS,
        help="Workers passed to scipy cKDTree.query during tissue cache construction; use -1 for all cores.",
    )
    parser.add_argument(
        "--tissue-kdtree-candidate-mult",
        type=int,
        default=_state.TISSUE_KDTREE_CANDIDATE_MULT,
        help="Multiplier for midpoint KDTree candidates before exact point-to-segment refinement in tissue solves.",
    )
    parser.add_argument(
        "--tissue-accel",
        type=str,
        default=_state.TISSUE_ACCEL_MODE,
        choices=("cpu", "gpu", "auto"),
        help="Tissue solve backend. GPU mode keeps segment arrays on GPU and streams point chunks.",
    )
    parser.add_argument(
        "--tissue-gpu-chunk-points",
        type=int,
        default=_state.TISSUE_GPU_CHUNK_POINTS,
        help="Point chunk size for GPU tissue refinement/Greens solve.",
    )
    parser.add_argument(
        "--tissue-gpu-validate-points",
        type=int,
        default=_state.TISSUE_GPU_VALIDATE_POINTS,
        help="If >0, compare GPU tissue results against CPU for this many leading points.",
    )
    parser.add_argument(
        "--output-csv",
        type=str,
        default=_state.OUTPUT_CSV_NAME,
        help="Override output CSV filename.",
    )
    parser.add_argument(
        "--tree-fast-cache",
        type=str,
        default="true" if _state.TREE_FAST_CACHE_ENABLE else "false",
        choices=("true", "false"),
        help="If a sibling .fast.tree.npz exists, load it instead of the compressed .tree.npz.",
    )
    parser.add_argument(
        "--kirchhoff-diagnostics",
        type=str,
        default="true" if _state.KIRCHHOFF_DIAGNOSTICS else "false",
        choices=("true", "false"),
        help="Print detailed Kirchhoff/GMRES diagnostics to CLI (no CSV changes).",
    )
    parser.add_argument(
        "--kirchhoff-solver",
        type=str,
        default=_state.KIRCHHOFF_SOLVER,
        choices=("tree", "auto", "cg", "spsolve", "gmres_ilu"),
        help="Kirchhoff solver. 'tree' is the O(N) tree-specific solver for the selected Kirchhoff BC mode.",
    )
    parser.add_argument(
        "--kirchhoff-bc-mode",
        type=str,
        default=_state.KIRCHHOFF_BC_MODE,
        choices=(
            "terminal_pressure",
            "mixed",
            "legacy_equal_terminal_flow",
            "legacy",
            "equal_terminal_flow",
            "current_outlets",
            "neumann",
        ),
        help=(
            "Kirchhoff boundary condition mode. terminal_pressure prescribes inlet flow and terminal pressures; "
            "legacy_equal_terminal_flow matches TissueSim_cube_new by prescribing inlet flow and equal terminal outflow sinks."
        ),
    )
    parser.add_argument(
        "--kirchhoff-validate-tree",
        type=str,
        default="true" if _state.KIRCHHOFF_VALIDATE_TREE else "false",
        choices=("true", "false"),
        help="When using --kirchhoff-solver tree, also run sparse spsolve and print speed/error comparison.",
    )
    parser.add_argument(
        "--kirchhoff-validation-sparse-solver",
        type=str,
        default=_state.KIRCHHOFF_VALIDATE_SPARSE_SOLVER,
        choices=("auto", "cg", "spsolve", "gmres_ilu"),
        help="Sparse solver used as the reference for --kirchhoff-validate-tree.",
    )
    parser.add_argument(
        "--tissue-streaming",
        type=str,
        default="true" if _state.TISSUE_STREAMING_ENABLED else "false",
        choices=("true", "false"),
        help="Use chunked streaming tissue oxygen solve for large sample counts.",
    )
    parser.add_argument(
        "--tissue-streaming-min-points",
        type=int,
        default=_state.TISSUE_STREAMING_MIN_POINTS,
        help="Minimum sample-point count that triggers streaming tissue solve.",
    )
    parser.add_argument(
        "--tissue-streaming-target-candidate-slots",
        type=int,
        default=_state.TISSUE_STREAMING_TARGET_CANDIDATE_SLOTS,
        help="Approximate max point*candidate slots per streaming chunk.",
    )
    parser.add_argument(
        "--tissue-streaming-max-chunk-points",
        type=int,
        default=_state.TISSUE_STREAMING_MAX_CHUNK_POINTS,
        help="Maximum points per streaming tissue chunk.",
    )
    parser.add_argument(
        "--tissue-streaming-chunk-workers",
        type=int,
        default=_state.TISSUE_STREAMING_CHUNK_WORKERS,
        help="Parallel outer chunk workers for streaming tissue solve.",
    )
    parser.add_argument(
        "--tissue-streaming-numba-threads-per-worker",
        type=int,
        default=_state.TISSUE_STREAMING_NUMBA_THREADS_PER_WORKER,
        help="Numba threads used inside each streaming chunk worker.",
    )
    parser.add_argument(
        "--tissue-streaming-prune-by-window",
        type=str,
        default="true" if _state.TISSUE_STREAMING_PRUNE_BY_WINDOW else "false",
        choices=("true", "false"),
        help="Conservatively remove candidates that cannot pass the Greens window cutoff before the kernel.",
    )
    return parser.parse_args()


__all__ = ['parse_args']
