"""Legacy TissueSim command runner and profiling hooks.

Generated by a behavior-preserving extraction from the frozen TissueSim
baseline. Dependencies are bound by the temporary compatibility facade while
the new typed subsystem APIs replace the legacy global runtime contract.
"""

from __future__ import annotations

import cProfile
from pathlib import Path
from time import perf_counter
import pstats
import traceback

import numpy as np

from cascade.configuration import _legacy_state as _state
from cascade.configuration._legacy_state import _lumen_diffusivity_cm2_s_for_fluid
from cascade.concentration.tissue.cache import build_tissue_cache_from_tree
from cascade.concentration.tissue.geometry import get_analysis_fluids
from cascade.concentration.vessel.dispatch import _resolve_concentration_solver
from cascade.concentration.vessel.greens import (
    _finite_radius_o2_term_flags,
    _normalize_cext_lambda_source,
)
from cascade.diagnostics.runtime import (
    _dbg,
    _fmt_seconds,
    _progress_snapshot,
    _set_progress,
    _write_crash_log,
)
from cascade.domain.builders import build_domain
from cascade.domain.sampling import compute_distance_to_nearest_channel, sample_domain_points
from cascade.exporting.statistics import aggregate_trials
from cascade.exporting.tables import (
    _iter_theta_values,
    _nondimensional_numbers_row,
    _normalize_angles,
    _normalize_lengths,
    _parse_distance_sample_count_values,
    _parse_qin_target_values,
    _pi_phi_gamma_columns,
    append_nondimensional_row,
    append_row,
)
from cascade.exporting.visualization import (
    _fit_truncnorm_mu_sigma_lower0,
    _init_violin_points_csv,
    _plot_concentration,
    _plot_dnc_gaussians,
    _plot_flow,
    _plot_viability_points,
    _update_violin_points_csv,
    plot_checker_tree,
)
from cascade.exporting.paths import resolve_output_path
from cascade.flow.hematocrit import _normalize_hematocrit_model
from cascade.flow.topology import _normalize_kirchhoff_bc_mode
from cascade.vessels.generation.legacy import _apply_run_tree_params, grow_tree, set_tree_fluid
from cascade.workflows.tree_cache import (
    _append_tree_cache_row,
    _build_tree_cache_config,
    _ensure_tree_domain,
    _find_cached_tree,
    _find_cached_tree_lower,
    _load_tree_cache_index,
    _load_tree_cached_fast,
    _prepare_loaded_tree,
    _sync_loaded_tree_params,
    _tree_cache_dir,
    _tree_cache_index_path,
    _tree_cache_row,
)
from cascade.workflows.tree_simulation import summarize_tissue_only_from_details, summarize_tree

from .legacy_arguments import parse_args

def main() -> None:
    # Mutable runtime state is centralized in configuration._legacy_state.
    _state.args = parse_args()
    qin_target_values = _parse_qin_target_values(getattr(_state.args, "qin_target", _state.QIN_TARGET))
    _state.QIN_TARGET = float(qin_target_values[0])
    if len(qin_target_values) > 1:
        print(
            "Qin target sweep enabled: "
            + ", ".join(f"{float(q):g}" for q in qin_target_values)
            + " uL/min"
        )
    # Mutable runtime state is centralized in configuration._legacy_state.
    _state.GL_ORDER = int(_state.args.gl_order)
    _state.GL_ORDER_CEXT = int(getattr(_state.args, "cext_gl_order", _state.GL_ORDER_CEXT))
    if _state.GL_ORDER_CEXT <= 0:
        raise ValueError(f"Unsupported --cext-gl-order={_state.GL_ORDER_CEXT}. Use a positive integer.")
    # Mutable runtime state is centralized in configuration._legacy_state.
    # Mutable runtime state is centralized in configuration._legacy_state.
    _state.DISTANCE_SAMPLE_COUNT = int(getattr(_state.args, "distance_sample_count", _state.DISTANCE_SAMPLE_COUNT))
    distance_sample_count_values = _parse_distance_sample_count_values(
        getattr(_state.args, "distance_sample_counts", None) or _state.DISTANCE_SAMPLE_COUNT
    )
    _state.DISTANCE_SAMPLE_COUNT = max(distance_sample_count_values)
    if len(distance_sample_count_values) > 1:
        print(
            "Distance sample count sweep enabled: "
            + ", ".join(f"{int(m):g}" for m in distance_sample_count_values)
            + f" points (max sampled once: {int(_state.DISTANCE_SAMPLE_COUNT):g})."
        )
    _state.COMPUTE_AVG_DISTANCE_TO_CHANNEL = (
        str(getattr(_state.args, "compute_avg_distance_to_channel", "true" if _state.COMPUTE_AVG_DISTANCE_TO_CHANNEL else "false")).lower()
        == "true"
    )
    _state.NEAREST_TISSUE_VESSELS = int(getattr(_state.args, "nearest_tissue_vessels", _state.NEAREST_TISSUE_VESSELS))
    _state.WINDOW_FACTOR = float(getattr(_state.args, "window_factor", _state.WINDOW_FACTOR))
    _state.OUTPUT_CSV_NAME = str(getattr(_state.args, "output_csv", _state.OUTPUT_CSV_NAME))
    _state.TREE_FAST_CACHE_ENABLE = str(getattr(_state.args, "tree_fast_cache", "true")).lower() == "true"
    _state.SOLVER_TIMING_DETAILS = str(getattr(_state.args, "solver_timing_details", "true")).lower() == "true"
    _state.TISSUE_CACHE_CHUNK_SIZE = int(getattr(_state.args, "tissue_cache_chunk_size", _state.TISSUE_CACHE_CHUNK_SIZE))
    _state.TISSUE_KDTREE_WORKERS = int(getattr(_state.args, "tissue_kdtree_workers", _state.TISSUE_KDTREE_WORKERS))
    _state.TISSUE_KDTREE_CANDIDATE_MULT = int(getattr(_state.args, "tissue_kdtree_candidate_mult", _state.TISSUE_KDTREE_CANDIDATE_MULT))
    _state.TISSUE_ACCEL_MODE = str(getattr(_state.args, "tissue_accel", _state.TISSUE_ACCEL_MODE)).lower()
    _state.TISSUE_GPU_CHUNK_POINTS = int(getattr(_state.args, "tissue_gpu_chunk_points", _state.TISSUE_GPU_CHUNK_POINTS))
    _state.TISSUE_GPU_VALIDATE_POINTS = int(getattr(_state.args, "tissue_gpu_validate_points", _state.TISSUE_GPU_VALIDATE_POINTS))
    _state.CEXT_ACCEL_MODE = str(getattr(_state.args, "cext_accel", _state.CEXT_ACCEL_MODE)).lower()
    _state.CEXT_FROZEN_ACCEL_MODE = str(getattr(_state.args, "cext_frozen_accel", _state.CEXT_FROZEN_ACCEL_MODE)).lower()
    _state.FINITE_RADIUS_O2_TERMS = str(getattr(_state.args, "finite_radius_o2_terms", _state.FINITE_RADIUS_O2_TERMS)).lower()
    _state.LUMEN_WALL_CLOSURE = str(getattr(_state.args, "lumen_wall_closure", _state.LUMEN_WALL_CLOSURE)).lower()
    _state.GRAETZ_N_RADIAL = int(getattr(_state.args, "graetz_n_radial", _state.GRAETZ_N_RADIAL))
    _state.GRAETZ_N_MODES = int(getattr(_state.args, "graetz_n_modes", _state.GRAETZ_N_MODES))
    _state.GRAETZ_MAX_FP_ITERS = int(getattr(_state.args, "graetz_max_fp_iters", _state.GRAETZ_MAX_FP_ITERS))
    _state.GRAETZ_VELOCITY_PROFILE = str(getattr(_state.args, "graetz_profile", _state.GRAETZ_VELOCITY_PROFILE)).lower()
    if getattr(_state.args, "lumen_diffusivity_cm2_s", None) is not None:
        _state.LUMEN_DIFFUSIVITY_OVERRIDE_CM2_S = float(_state.args.lumen_diffusivity_cm2_s)
        _state.LUMEN_DIFFUSIVITY_CM2_S = float(_state.args.lumen_diffusivity_cm2_s)
    _finite_radius_o2_term_flags()
    if _state.LUMEN_WALL_CLOSURE == "graetz" and _state.CEXT_FROZEN_ACCEL_MODE == "cpu":
        raise ValueError("Graetz lumen closure requires --cext-frozen-accel gpu or auto.")
    _state.CEXT_INIT_MODE = str(getattr(_state.args, "cext_init_mode", _state.CEXT_INIT_MODE)).lower()
    _state.CEXT_LAMBDA_SOURCE = _normalize_cext_lambda_source(getattr(_state.args, "cext_lambda_source", _state.CEXT_LAMBDA_SOURCE))
    _state.CEXT_WINDOW_FACTOR = float(getattr(_state.args, "cext_window_factor", _state.CEXT_WINDOW_FACTOR))
    _state.CEXT_VESS_COUPLING_MAX_ITER = int(getattr(_state.args, "cext_vess_coupling_max_iter", _state.CEXT_VESS_COUPLING_MAX_ITER))
    _state.CEXT_VESS_COUPLING_TOL = float(getattr(_state.args, "cext_vess_coupling_tol", _state.CEXT_VESS_COUPLING_TOL))
    _state.CEXT_VESS_COUPLING_REL_TOL = float(getattr(_state.args, "cext_vess_coupling_rel_tol", _state.CEXT_VESS_COUPLING_REL_TOL))
    _state.CEXT_VESS_COUPLING_OMEGA = float(getattr(_state.args, "cext_vess_coupling_omega", _state.CEXT_VESS_COUPLING_OMEGA))
    _state.CEXT_VESS_COUPLING_ACCEL = str(getattr(_state.args, "cext_vess_coupling_accel", _state.CEXT_VESS_COUPLING_ACCEL)).lower()
    _state.CEXT_VESS_COUPLING_OMEGA_MIN = float(getattr(_state.args, "cext_vess_coupling_omega_min", _state.CEXT_VESS_COUPLING_OMEGA_MIN))
    _state.CEXT_VESS_COUPLING_OMEGA_MAX = float(getattr(_state.args, "cext_vess_coupling_omega_max", _state.CEXT_VESS_COUPLING_OMEGA_MAX))
    _state.CEXT_VESS_COUPLING_TRUST_ABS = float(getattr(_state.args, "cext_vess_coupling_trust_abs", _state.CEXT_VESS_COUPLING_TRUST_ABS))
    _state.CEXT_VESS_COUPLING_TRUST_REL = float(getattr(_state.args, "cext_vess_coupling_trust_rel", _state.CEXT_VESS_COUPLING_TRUST_REL))
    _state.CEXT_VESS_COUPLING_ANDERSON_DEPTH = int(getattr(_state.args, "cext_vess_coupling_anderson_depth", _state.CEXT_VESS_COUPLING_ANDERSON_DEPTH))
    _state.CEXT_VESS_COUPLING_ANDERSON_REG = float(getattr(_state.args, "cext_vess_coupling_anderson_reg", _state.CEXT_VESS_COUPLING_ANDERSON_REG))
    _state.CEXT_VESS_COUPLING_ANDERSON_START = int(getattr(_state.args, "cext_vess_coupling_anderson_start", _state.CEXT_VESS_COUPLING_ANDERSON_START))
    _state.CEXT_VESS_COUPLING_ANDERSON_GATE_RATIO = float(getattr(_state.args, "cext_vess_coupling_anderson_gate_ratio", _state.CEXT_VESS_COUPLING_ANDERSON_GATE_RATIO))
    _state.CEXT_VESS_COUPLING_ANDERSON_MIN_STABLE_ITERS = int(getattr(_state.args, "cext_vess_coupling_anderson_min_stable_iters", _state.CEXT_VESS_COUPLING_ANDERSON_MIN_STABLE_ITERS))
    _state.CEXT_VESS_COUPLING_ANDERSON_OMEGA_GATE_FACTOR = float(getattr(_state.args, "cext_vess_coupling_anderson_omega_gate_factor", _state.CEXT_VESS_COUPLING_ANDERSON_OMEGA_GATE_FACTOR))
    _state.CEXT_VESS_COUPLING_ACCEL_ACCEPT_FACTOR = float(getattr(_state.args, "cext_vess_coupling_accept_factor", _state.CEXT_VESS_COUPLING_ACCEL_ACCEPT_FACTOR))
    _state.CEXT_VESS_COUPLING_ACCEL_STEP_FACTOR = float(getattr(_state.args, "cext_vess_coupling_step_factor", _state.CEXT_VESS_COUPLING_ACCEL_STEP_FACTOR))
    _state.CEXT_VESS_COUPLING_ACCEL_RESTART_FACTOR = float(getattr(_state.args, "cext_vess_coupling_restart_factor", _state.CEXT_VESS_COUPLING_ACCEL_RESTART_FACTOR))
    _state.CEXT_VESS_COUPLING_BEST_STALL_ITERS = int(getattr(_state.args, "cext_vess_coupling_best_stall_iters", _state.CEXT_VESS_COUPLING_BEST_STALL_ITERS))
    _state.CEXT_VESS_COUPLING_BEST_REVERT_FACTOR = float(getattr(_state.args, "cext_vess_coupling_best_revert_factor", _state.CEXT_VESS_COUPLING_BEST_REVERT_FACTOR))
    _state.CEXT_VESS_COUPLING_STEP_REJECT_FACTOR = float(getattr(_state.args, "cext_vess_coupling_step_reject_factor", _state.CEXT_VESS_COUPLING_STEP_REJECT_FACTOR))
    _state.CEXT_VESS_COUPLING_STEP_RETRY_FACTOR = float(getattr(_state.args, "cext_vess_coupling_step_retry_factor", _state.CEXT_VESS_COUPLING_STEP_RETRY_FACTOR))
    _state.CEXT_ACTIVE_SET_ENABLE = str(getattr(_state.args, "cext_active_set_enable", "true" if _state.CEXT_ACTIVE_SET_ENABLE else "false")).lower() == "true"
    _state.CEXT_ACTIVE_SET_START = int(getattr(_state.args, "cext_active_set_start", _state.CEXT_ACTIVE_SET_START))
    _state.CEXT_ACTIVE_SET_STABLE_ITERS = int(getattr(_state.args, "cext_active_set_stable_iters", _state.CEXT_ACTIVE_SET_STABLE_ITERS))
    _state.CEXT_ACTIVE_SET_REL_TOL = float(getattr(_state.args, "cext_active_set_rel_tol", _state.CEXT_ACTIVE_SET_REL_TOL))
    _state.CEXT_ACTIVE_SET_ABS_TOL = float(getattr(_state.args, "cext_active_set_abs_tol", _state.CEXT_ACTIVE_SET_ABS_TOL))
    _state.CEXT_ACTIVE_SET_REFRESH_PERIOD = int(getattr(_state.args, "cext_active_set_refresh_period", _state.CEXT_ACTIVE_SET_REFRESH_PERIOD))
    _state.CEXT_ACTIVE_SET_MIN_ACTIVE_COUNT = int(getattr(_state.args, "cext_active_set_min_active_count", _state.CEXT_ACTIVE_SET_MIN_ACTIVE_COUNT))
    _state.CEXT_ACTIVE_SET_MIN_ACTIVE_FRACTION = float(getattr(_state.args, "cext_active_set_min_active_fraction", _state.CEXT_ACTIVE_SET_MIN_ACTIVE_FRACTION))
    _state.CEXT_TARGET_ACTIVE_SET_ENABLE = str(getattr(_state.args, "cext_target_active_set_enable", "true" if _state.CEXT_TARGET_ACTIVE_SET_ENABLE else "false")).lower() == "true"
    _state.CEXT_TARGET_ACTIVE_SET_START = int(getattr(_state.args, "cext_target_active_set_start", _state.CEXT_TARGET_ACTIVE_SET_START))
    _state.CEXT_TARGET_ACTIVE_SET_STABLE_ITERS = int(getattr(_state.args, "cext_target_active_set_stable_iters", _state.CEXT_TARGET_ACTIVE_SET_STABLE_ITERS))
    _state.CEXT_TARGET_ACTIVE_SET_REL_TOL = float(getattr(_state.args, "cext_target_active_set_rel_tol", _state.CEXT_TARGET_ACTIVE_SET_REL_TOL))
    _state.CEXT_TARGET_ACTIVE_SET_ABS_TOL = float(getattr(_state.args, "cext_target_active_set_abs_tol", _state.CEXT_TARGET_ACTIVE_SET_ABS_TOL))
    _state.CEXT_TARGET_ACTIVE_SET_MIN_ACTIVE_COUNT = int(getattr(_state.args, "cext_target_active_set_min_active_count", _state.CEXT_TARGET_ACTIVE_SET_MIN_ACTIVE_COUNT))
    _state.CEXT_TARGET_ACTIVE_SET_NEIGHBOR_PAD = int(getattr(_state.args, "cext_target_active_set_neighbor_pad", _state.CEXT_TARGET_ACTIVE_SET_NEIGHBOR_PAD))
    _state.CEXT_HYBRID_BG_MODE = str(getattr(_state.args, "cext_hybrid_bg_mode", _state.CEXT_HYBRID_BG_MODE)).lower()
    _state.CEXT_HYBRID_BG_GRID = int(getattr(_state.args, "cext_hybrid_bg_grid", _state.CEXT_HYBRID_BG_GRID))
    _state.CEXT_HYBRID_BG_LAMBDA_BINS = int(getattr(_state.args, "cext_hybrid_bg_lambda_bins", _state.CEXT_HYBRID_BG_LAMBDA_BINS))
    _state.CEXT_HYBRID_BG_NEAR_RADIUS_MULT = float(getattr(_state.args, "cext_hybrid_bg_near_radius_mult", _state.CEXT_HYBRID_BG_NEAR_RADIUS_MULT))
    _state.CEXT_HYBRID_BG_VCYCLES = int(getattr(_state.args, "cext_hybrid_bg_vcycles", _state.CEXT_HYBRID_BG_VCYCLES))
    _state.CEXT_HYBRID_BG_ASSIGNMENT = str(getattr(_state.args, "cext_hybrid_bg_assignment", _state.CEXT_HYBRID_BG_ASSIGNMENT)).lower()
    _state.CEXT_HYBRID_BG_SOLVER = str(getattr(_state.args, "cext_hybrid_bg_solver", _state.CEXT_HYBRID_BG_SOLVER)).lower()
    _state.CEXT_HYBRID_BG_ENABLE_SOURCE_FREEZING = str(
        getattr(_state.args, "cext_hybrid_bg_enable_source_freezing", "true" if _state.CEXT_HYBRID_BG_ENABLE_SOURCE_FREEZING else "false")
    ).lower() == "true"
    _state.CEXT_HYBRID_FFT_QUANTILE_BINS = str(
        getattr(_state.args, "cext_hybrid_fft_quantile_bins", "true" if _state.CEXT_HYBRID_FFT_QUANTILE_BINS else "false")
    ).lower() == "true"
    _state.CEXT_HYBRID_FFT_O2_CORRECTION = str(
        getattr(_state.args, "cext_hybrid_fft_o2_correction", "true" if _state.CEXT_HYBRID_FFT_O2_CORRECTION else "false")
    ).lower() == "true"
    _state.CEXT_HYBRID_FFT_SELF_SUBTRACT = str(
        getattr(_state.args, "cext_hybrid_fft_self_subtract", "true" if _state.CEXT_HYBRID_FFT_SELF_SUBTRACT else "false")
    ).lower() == "true"
    _state.CEXT_HYBRID_FFT_SELF_SUB_TARGET_SAMPLING = str(
        getattr(_state.args, "cext_hybrid_fft_self_sub_target_sampling", _state.CEXT_HYBRID_FFT_SELF_SUB_TARGET_SAMPLING)
    ).lower()
    _state.CEXT_HYBRID_FFT_SELF_SUB_SCALE = float(getattr(_state.args, "cext_hybrid_fft_self_sub_scale", _state.CEXT_HYBRID_FFT_SELF_SUB_SCALE))
    _state.CEXT_TREECODE_THETA = float(getattr(_state.args, "cext_treecode_theta", _state.CEXT_TREECODE_THETA))
    _state.CEXT_TREECODE_ORDER = int(getattr(_state.args, "cext_treecode_order", _state.CEXT_TREECODE_ORDER))
    _state.CEXT_TREECODE_LEAF_NODES = int(getattr(_state.args, "cext_treecode_leaf_nodes", _state.CEXT_TREECODE_LEAF_NODES))
    _state.CEXT_TREECODE_LAMBDA_BINS = int(getattr(_state.args, "cext_treecode_lambda_bins", _state.CEXT_TREECODE_LAMBDA_BINS))
    _state.CEXT_TREECODE_NEAR_RADIUS_MULT = float(getattr(_state.args, "cext_treecode_near_radius_mult", _state.CEXT_TREECODE_NEAR_RADIUS_MULT))
    _state.CEXT_TREECODE_GPU_LOCAL = str(getattr(_state.args, "cext_treecode_gpu_local", "true" if _state.CEXT_TREECODE_GPU_LOCAL else "false")).lower() == "true"
    _state.CEXT_TAIL_SOLVER = str(getattr(_state.args, "cext_tail_solver", _state.CEXT_TAIL_SOLVER)).lower()
    _state.CEXT_TAIL_TRIGGER_START_ITER = int(getattr(_state.args, "cext_tail_trigger_start_iter", _state.CEXT_TAIL_TRIGGER_START_ITER))
    _state.CEXT_TAIL_TRIGGER_STALL_ITERS = int(getattr(_state.args, "cext_tail_trigger_stall_iters", _state.CEXT_TAIL_TRIGGER_STALL_ITERS))
    _state.CEXT_TAIL_TRIGGER_ACTIVE_COUNT = int(getattr(_state.args, "cext_tail_trigger_active_count", _state.CEXT_TAIL_TRIGGER_ACTIVE_COUNT))
    _state.CEXT_TAIL_MAX_NONLINEAR_ITERS = int(getattr(_state.args, "cext_tail_max_nonlinear_iters", _state.CEXT_TAIL_MAX_NONLINEAR_ITERS))
    _state.CEXT_TAIL_GMRES_RESTART = int(getattr(_state.args, "cext_tail_gmres_restart", _state.CEXT_TAIL_GMRES_RESTART))
    _state.CEXT_TAIL_GMRES_MAXITER = int(getattr(_state.args, "cext_tail_gmres_maxiter", _state.CEXT_TAIL_GMRES_MAXITER))
    _state.CEXT_GRID_CELL_FACTOR = float(getattr(_state.args, "cext_grid_cell_factor", _state.CEXT_GRID_CELL_FACTOR))
    _state.CEXT_STREAMING_TARGET_CANDIDATE_SLOTS = int(
        getattr(_state.args, "cext_streaming_target_candidate_slots", _state.CEXT_STREAMING_TARGET_CANDIDATE_SLOTS)
    )
    _state.CEXT_GPU_VALIDATE_SEGMENTS = int(getattr(_state.args, "cext_gpu_validate_segments", _state.CEXT_GPU_VALIDATE_SEGMENTS))
    _state.CEXT_APPROX_WINDOW_SCALE = float(getattr(_state.args, "cext_approx_window_scale", _state.CEXT_APPROX_WINDOW_SCALE))
    _state.CEXT_MAX_CANDIDATES_PER_TARGET = int(getattr(_state.args, "cext_max_candidates_per_target", _state.CEXT_MAX_CANDIDATES_PER_TARGET))
    # Mutable runtime state is centralized in configuration._legacy_state.
    # Mutable runtime state is centralized in configuration._legacy_state.
    _state.HEMATOCRIT_MODEL = _normalize_hematocrit_model(getattr(_state.args, "hematocrit_model", _state.HEMATOCRIT_MODEL))
    _state.HEMATOCRIT_FLOW_ITERATIONS = int(getattr(_state.args, "hematocrit_flow_iterations", _state.HEMATOCRIT_FLOW_ITERATIONS))
    _state.HEMATOCRIT_RELAXATION = float(getattr(_state.args, "hematocrit_relaxation", _state.HEMATOCRIT_RELAXATION))
    _state.HEMATOCRIT_QTOL_NL_MIN = float(getattr(_state.args, "hematocrit_qtol_nl_min", _state.HEMATOCRIT_QTOL_NL_MIN))
    _state.HEMATOCRIT_HDTOL = float(getattr(_state.args, "hematocrit_hdtol", _state.HEMATOCRIT_HDTOL))
    target_counts_arg = getattr(_state.args, "target_counts", None)
    if target_counts_arg:
        _state.TARGET_TERMINAL_COUNTS = tuple(
            int(part.strip()) for part in str(target_counts_arg).split(",") if part.strip()
        )
    # Mutable runtime state is centralized in configuration._legacy_state.
    # Mutable runtime state is centralized in configuration._legacy_state.
    _state.KIRCHHOFF_DIAGNOSTICS = str(getattr(_state.args, "kirchhoff_diagnostics", "false")).lower() == "true"
    _state.KIRCHHOFF_SOLVER = str(getattr(_state.args, "kirchhoff_solver", _state.KIRCHHOFF_SOLVER)).lower()
    _state.KIRCHHOFF_BC_MODE = _normalize_kirchhoff_bc_mode(getattr(_state.args, "kirchhoff_bc_mode", _state.KIRCHHOFF_BC_MODE))
    _state.KIRCHHOFF_VALIDATE_TREE = str(getattr(_state.args, "kirchhoff_validate_tree", "false")).lower() == "true"
    _state.KIRCHHOFF_VALIDATE_SPARSE_SOLVER = str(
        getattr(_state.args, "kirchhoff_validation_sparse_solver", _state.KIRCHHOFF_VALIDATE_SPARSE_SOLVER)
    ).lower()
    if _state.KIRCHHOFF_SOLVER != "tree":
        _state.KIRCHHOFF_SPARSE_SOLVER = _state.KIRCHHOFF_SOLVER
    # Mutable runtime state is centralized in configuration._legacy_state.
    # Mutable runtime state is centralized in configuration._legacy_state.
    # Mutable runtime state is centralized in configuration._legacy_state.
    # Mutable runtime state is centralized in configuration._legacy_state.
    _state.TISSUE_STREAMING_ENABLED = str(getattr(_state.args, "tissue_streaming", "true")).lower() == "true"
    _state.TISSUE_STREAMING_MIN_POINTS = int(getattr(_state.args, "tissue_streaming_min_points", _state.TISSUE_STREAMING_MIN_POINTS))
    _state.TISSUE_STREAMING_TARGET_CANDIDATE_SLOTS = int(
        getattr(_state.args, "tissue_streaming_target_candidate_slots", _state.TISSUE_STREAMING_TARGET_CANDIDATE_SLOTS)
    )
    _state.TISSUE_STREAMING_MAX_CHUNK_POINTS = int(
        getattr(_state.args, "tissue_streaming_max_chunk_points", _state.TISSUE_STREAMING_MAX_CHUNK_POINTS)
    )
    _state.TISSUE_STREAMING_CHUNK_WORKERS = int(
        getattr(_state.args, "tissue_streaming_chunk_workers", _state.TISSUE_STREAMING_CHUNK_WORKERS)
    )
    _state.TISSUE_STREAMING_NUMBA_THREADS_PER_WORKER = int(
        getattr(_state.args, "tissue_streaming_numba_threads_per_worker", _state.TISSUE_STREAMING_NUMBA_THREADS_PER_WORKER)
    )
    _state.TISSUE_STREAMING_PRUNE_BY_WINDOW = (
        str(getattr(_state.args, "tissue_streaming_prune_by_window", "true")).lower() == "true"
    )
    # Mutable runtime state is centralized in configuration._legacy_state.
    if _state.args.n_equal_bifurcations is not None and int(_state.args.n_equal_bifurcations) >= 0:
        _state.N_EQUAL_BIFURCATIONS = int(_state.args.n_equal_bifurcations)
    else:
        _state.N_EQUAL_BIFURCATIONS = None
    # Mutable runtime state is centralized in configuration._legacy_state.
    _state.CONCENTRATION_SOLVER = _state.args.concentration_solver.lower()
    # Mutable runtime state is centralized in configuration._legacy_state.
    _state.PLOT_FLOW = _state.args.plot_flow.lower() == "true"
    _state.PLOT_CONC_VESSELS = _state.args.plot_concentration.lower() == "true"
    _state.PLOT_CONC_VESSELS_POINTS = _state.args.plot_concentration_points.lower() == "true"
    _state.PLOT_VIABILITY_POINTS = _state.args.plot_viability.lower() == "true"
    weighted_sampling = _state.args.weighted_sampling.lower() == "true"
    ignore_collisions = _state.args.ignore_collisions.lower() == "true"
    allow_inside_vessels = _state.args.allow_inside_vessels.lower() == "true"
    if _state.TISSUE_USE_NUMBA and not _state._HAVE_NUMBA:
        print("WARNING: Numba is not available; tissue kernel will run without numba.")
    analysis_fluids = get_analysis_fluids()
    _state.ACTIVE_FLUID = analysis_fluids[0]
    solver_logged = False
    cache_enabled = _state.USE_TREE_CACHE or _state.SAVE_TREES
    cache_rows: list[dict[str, str]] = []
    cache_index_path: Path | None = None
    if cache_enabled:
        cache_index_path = _tree_cache_index_path()
        cache_rows = _load_tree_cache_index(cache_index_path)

    run_configs = [
        {
            "name": "baseline",
            "output_csv_name": _state.OUTPUT_CSV_NAME,
            "target_counts": _state.TARGET_TERMINAL_COUNTS,
            "trials_per_combo": _state.TRIALS_PER_COMBO,
            "fluid": _state.FLUID,
            "cube_side_lengths": _state.CUBE_SIDE_LENGTHS,
            "dlp_angles": _state.DLP_ANGLE_VALUES,
        },
    ]

    nondim_output_path: Path | None = None
    if _state.NONDIMENSIONAL_NUMBERS:
        nondim_output_path = resolve_output_path(_state.NONDIMENSIONAL_CSV_NAME)
        nondim_output_path.parent.mkdir(parents=True, exist_ok=True)
        if nondim_output_path.exists():
            nondim_output_path.unlink()
        append_nondimensional_row(nondim_output_path, row=None, write_header=True)
        print(
            f"Nondimensional mode: enabled. Writing dimensional/nondimensional metrics to "
            f"{nondim_output_path.name}."
        )

    for run in run_configs:
        _set_progress("run_start", run_name=run["name"], output_csv=run["output_csv_name"])
        side_lengths = _normalize_lengths(run.get("cube_side_lengths", _state.CUBE_SIDE_LENGTHS))
        if _state.BUILD_ON_PREVIOUS:
            if len(side_lengths) > 1:
                raise ValueError("BUILD_ON_PREVIOUS requires a single cube side length per run.")
            trials = int(run.get("trials_per_combo", _state.TRIALS_PER_COMBO))
            if trials > 1:
                raise ValueError("BUILD_ON_PREVIOUS requires trials_per_combo == 1.")
        output_path = resolve_output_path(run["output_csv_name"])
        output_path.parent.mkdir(parents=True, exist_ok=True)
        if output_path.exists():
            output_path.unlink()

        append_row(output_path, row=None, write_header=True)

        for side_len in side_lengths:
            _set_progress("side_start", side_len=side_len, theta=None, target=None, trial=None, fluid=None)
            domain = build_domain(side_len)
            sample_points = sample_domain_points(domain, _state.DISTANCE_SAMPLE_COUNT)

            checker_done = False
            if "dlp_angles" in run:
                angles = _normalize_angles(run["dlp_angles"])
            else:
                angles = _iter_theta_values()
            for min_theta in angles:
                _set_progress("theta_start", theta=min_theta, target=None, trial=None, fluid=None)
                dlp_enable = False  # DLP disabled in this build
                previous_tree = None
                previous_target = 0
                dnc_history: dict[str, object] = {}
                if _state.PLOT_HISTOGRAM:
                    dnc_history = {"targets": [], "mu_sigma": []}
                violin_path = resolve_output_path(_state.VIOLIN_CSV_NAME)
                violin_path.parent.mkdir(parents=True, exist_ok=True)
                if _state.VIOLIN_DNC:
                    _init_violin_points_csv(
                        violin_path,
                        target_counts=list(run["target_counts"]),
                        n_rows=int(sample_points.shape[0]),
                    )
                for target in run["target_counts"]:
                    _set_progress("target_start", target=target, trial=None, fluid=None)
                    trials = int(run["trials_per_combo"])
                    print(
                        f"\nRun '{run['name']}': build_fluid={_state.BUILD_FLUID}, analysis={','.join(analysis_fluids)}, "
                        f"theta={min_theta} deg, target={target}, trials={trials}, side={side_len}, "
                        f"qin={','.join(f'{float(q):g}' for q in qin_target_values)} uL/min"
                    )
                    qin_trial_rows = {
                        float(qin): {
                            int(m): {fluid: [] for fluid in analysis_fluids}
                            for m in distance_sample_count_values
                        }
                        for qin in qin_target_values
                    }
                    need_dnc_fit = bool(_state.PLOT_HISTOGRAM or _state.SAVE_DNC_GAUSSIAN_FITS)
                    need_dnc_violin = bool(_state.VIOLIN_DNC)
                    need_dnc_any = bool(need_dnc_fit or need_dnc_violin)
                    dnc_mu_trials: list[float] = []
                    dnc_sigma_trials: list[float] = []
                    dnc_violin_trials: list[np.ndarray] = []
                    for trial_idx in range(1, trials + 1):
                        _set_progress("trial_start", trial=trial_idx)
                        _dbg(f"trial {trial_idx}: start")
                        volume_scale = side_len * side_len * side_len
                        scale_factor = volume_scale if _state.SCALE_NTERMS_BY_VOLUME else 1.0
                        effective_target = max(int(round(target * scale_factor)), 1)
                        q_scale = volume_scale if _state.SCALE_Q_BY_VOLUME else 1.0
                        build_qin_target = float(qin_target_values[0])
                        _state.QIN_TARGET = build_qin_target
                        q_inlet_cm3_s = build_qin_target * 1e-3 / 60.0 * q_scale
                        per_seg_flow = q_inlet_cm3_s / (effective_target + 1)
                        terminal_flow_override = per_seg_flow if _state.SCALE_Q_BY_VOLUME else None
                        terminal_flow_cm3_s = per_seg_flow
                        base_config = None
                        full_config = None
                        config_id = None
                        legacy_config_id = None
                        if cache_enabled:
                            base_config, full_config, config_id, legacy_config_id = _build_tree_cache_config(
                                target_raw=target,
                                target_terminals=effective_target,
                                side_length=side_len,
                                domain_seed=getattr(domain, "random_seed", None),
                                q_inlet_cm3_s=q_inlet_cm3_s,
                                terminal_flow_cm3_s=terminal_flow_cm3_s,
                                dlp_enable=dlp_enable,
                                min_theta=min_theta,
                                weighted_sampling=weighted_sampling,
                                ignore_collisions=ignore_collisions,
                                allow_inside_vessels=allow_inside_vessels,
                                n_closest_vessels=_state.args.n_closest_vessels,
                                n_points=_state.args.n_points,
                            )
                        t_tree_build_start = perf_counter()
                        tree = None
                        cache_exact_hit = False
                        cache_status = "miss"
                        cache_note = ""
                        cached = None
                        lower = None
                        if _state.USE_TREE_CACHE and config_id is not None:
                            cached = _find_cached_tree(cache_rows, config_id, effective_target)
                            if cached is None and legacy_config_id and legacy_config_id != config_id:
                                cached = _find_cached_tree(cache_rows, legacy_config_id, effective_target)
                            if cached is None:
                                lower = _find_cached_tree_lower(cache_rows, config_id, effective_target)
                        if cached is not None:
                            _, tree_path = cached
                            # Avoid loading the cached Domain/mesh (can be extremely large) unless explicitly needed.
                            # We'll reuse the already-built run domain when we need the boundary/mesh (growth/plots).
                            need_tree_domain = bool(
                                _state.CHECKER_PLOT
                                or _state.PLOT_FLOW
                                or _state.PLOT_CONC_VESSELS
                                or _state.PLOT_CONC_VESSELS_POINTS
                                or _state.PLOT_VIABILITY_POINTS
                            )
                            tree = _load_tree_cached_fast(
                                Path(tree_path),
                                data_dtype=_state.TREE_DATA_DTYPE,
                                index_dtype=_state.TREE_INDEX_DTYPE,
                                analysis_only=not need_tree_domain,
                            )
                            if need_tree_domain:
                                _ensure_tree_domain(tree, domain)
                            _prepare_loaded_tree(tree)
                            _sync_loaded_tree_params(
                                tree,
                                side_length=side_len,
                                terminal_flow_override=terminal_flow_override,
                            )
                            cache_exact_hit = True
                            cache_status = "hit"
                        else:
                            prev_ok = (
                                _state.BUILD_ON_PREVIOUS
                                and previous_tree is not None
                                and not bool(getattr(previous_tree, "_analysis_only_load", False))
                            )
                            if prev_ok and effective_target < previous_target:
                                raise ValueError("BUILD_ON_PREVIOUS requires non-decreasing target counts.")
                            use_previous = False
                            use_lower = False
                            cached_target = None
                            cached_path = None
                            if lower is not None:
                                _, cached_target, cached_path = lower
                            if prev_ok:
                                if cached_target is not None:
                                    prev_gap = effective_target - previous_target
                                    cache_gap = effective_target - cached_target
                                    if cache_gap < prev_gap:
                                        use_lower = True
                                    else:
                                        use_previous = True
                                else:
                                    use_previous = True
                            elif cached_target is not None:
                                use_lower = True

                            if use_lower and cached_path is not None and cached_target is not None:
                                vessels_to_add = effective_target - cached_target
                                tree = _load_tree_cached_fast(
                                    Path(cached_path),
                                    data_dtype=_state.TREE_DATA_DTYPE,
                                    index_dtype=_state.TREE_INDEX_DTYPE,
                                )
                                _prepare_loaded_tree(tree)
                                _sync_loaded_tree_params(
                                    tree,
                                    side_length=side_len,
                                    terminal_flow_override=terminal_flow_override,
                                )
                                if vessels_to_add > 0:
                                    _ensure_tree_domain(tree, domain)
                                    tree.n_add(
                                        vessels_to_add,
                                        n_closest_vessels=_state.args.n_closest_vessels,
                                        n_points=_state.args.n_points,
                                        use_random_int=not weighted_sampling,
                                        ignore_collisions=ignore_collisions,
                                        allow_inside_vessels=allow_inside_vessels,
                                        debug_add_vessel=_state.DEBUG_ADD_VESSEL,
                                    )
                                cache_status = "extend"
                            elif use_previous:
                                tree = previous_tree
                                _sync_loaded_tree_params(
                                    tree,
                                    side_length=side_len,
                                    terminal_flow_override=terminal_flow_override,
                                )
                                vessels_to_add = effective_target - previous_target
                                if vessels_to_add > 0:
                                    _ensure_tree_domain(tree, domain)
                                    tree.n_add(
                                        vessels_to_add,
                                        n_closest_vessels=_state.args.n_closest_vessels,
                                        n_points=_state.args.n_points,
                                        use_random_int=not weighted_sampling,
                                        ignore_collisions=ignore_collisions,
                                        allow_inside_vessels=allow_inside_vessels,
                                        debug_add_vessel=_state.DEBUG_ADD_VESSEL,
                                    )
                                cache_note = "previous"

                            if tree is None:
                                tree = grow_tree(
                                    domain,
                                    effective_target,
                                    dlp_enable=dlp_enable,
                                    min_theta=min_theta,
                                    side_length=side_len,
                                    terminal_flow_override=terminal_flow_override,
                                    fluid=_state.BUILD_FLUID,
                                    n_closest_vessels=_state.args.n_closest_vessels,
                                    n_points=_state.args.n_points,
                                    weighted_sampling=weighted_sampling,
                                    ignore_collisions=ignore_collisions,
                                )
                                cache_note = "build"
                        _apply_run_tree_params(tree, side_len, terminal_flow_override)
                        if _state.USE_TREE_CACHE:
                            suffix = f" ({cache_note})" if cache_note else ""
                            print(f"  Cache: {cache_status}{suffix}")
                        if _state.SAVE_TREES and not cache_exact_hit:
                            t_tree_save_start = perf_counter()
                            if tree is None:
                                raise RuntimeError("Tree build failed; nothing to save.")
                            if cache_index_path is None or base_config is None or full_config is None or config_id is None:
                                raise RuntimeError("Tree cache config missing; cannot save.")
                            set_tree_fluid(tree, _state.BUILD_FLUID)
                            domain_obj = getattr(tree, "domain", None)
                            if domain_obj is None:
                                raise ValueError("Tree has no domain; cannot save to cache.")
                            if domain_obj.mesh is None or getattr(domain_obj, "volume", None) is None:
                                domain_obj.build()
                            if getattr(domain_obj, "boundary", None) is None:
                                domain_obj.get_boundary()
                            cache_dir = _tree_cache_dir()
                            cache_dir.mkdir(parents=True, exist_ok=True)
                            tree_filename = f"tree_{config_id}_t{effective_target}.tree.npz"
                            tree_path = cache_dir / tree_filename
                            tree.save(
                                str(tree_path),
                                include_domain=True,
                                domain_save_kwargs={"include_mesh": True, "include_boundary": True},
                            )
                            cache_row = _tree_cache_row(
                                config_id=config_id,
                                tree_path=tree_path,
                                base_config=base_config,
                                full_config=full_config,
                                target_raw=target,
                                target_terminals=effective_target,
                            )
                            _append_tree_cache_row(cache_index_path, cache_row)
                            cache_rows.append(cache_row)
                            print(f"  Tree save time: {_fmt_seconds(perf_counter() - t_tree_save_start)}")
                        tree_build_elapsed = perf_counter() - t_tree_build_start
                        if cache_status == "hit":
                            print(f"  Tree load time (cache hit): {_fmt_seconds(tree_build_elapsed)}")
                        elif cache_status == "extend":
                            print(f"  Tree extend time (cache lower): {_fmt_seconds(tree_build_elapsed)}")
                        elif cache_status == "miss" and cache_note == "build":
                            print(f"  Tree build time (cache miss): {_fmt_seconds(tree_build_elapsed)}")
                        elif cache_status == "miss" and cache_note == "previous":
                            print(f"  Tree extend time (previous tree): {_fmt_seconds(tree_build_elapsed)}")
                        else:
                            print(f"  Tree build/load time: {_fmt_seconds(tree_build_elapsed)}")
                        _set_progress("tree_ready", trial=trial_idx)
                        metrics_by_qin: dict[float, dict[int, dict[str, dict]]] = {}
                        try:
                            if _state.CHECKER_PLOT and not checker_done and target == 250:
                                checker_done = True
                                print("Checker: displaying first 250-terminal tree for inspection...")
                                _state.ACTIVE_FLUID = analysis_fluids[0]
                                plot_checker_tree(
                                    tree,
                                    sample_points,
                                    inlet_flow_cm3_s=q_inlet_cm3_s,
                                    fluid=analysis_fluids[0],
                                )
                            if need_dnc_any:
                                seg_count = int(getattr(tree, "segment_count", 0))
                                data = np.asarray(tree.data[:seg_count]) if seg_count > 0 else np.empty((0, 0), dtype=float)
                                starts = data[:, 0:3] if data.size else np.empty((0, 3), dtype=float)
                                ends = data[:, 3:6] if data.size else np.empty((0, 3), dtype=float)
                                radii = data[:, 21] if (data.size and data.shape[1] > 21) else np.zeros((starts.shape[0],), dtype=float)
                                print("Starting DNC Calculations")
                                dnc_values_cm = compute_distance_to_nearest_channel(sample_points, starts, ends, radii)
                                print("Ending DNC Calculations")
                                dnc_values_um = dnc_values_cm * _state.CM_TO_UM
                                finite = dnc_values_um[np.isfinite(dnc_values_um)]
                                if need_dnc_fit:
                                    mu, sigma = _fit_truncnorm_mu_sigma_lower0(finite)
                                    dnc_mu_trials.append(float(mu))
                                    dnc_sigma_trials.append(float(sigma))
                                if need_dnc_violin:
                                    # Save per-point DNC (one value per sample point) for violin plots.
                                    dnc_violin_trials.append(np.asarray(dnc_values_um, dtype=float).reshape(-1))
                            sample_points_by_count = {
                                int(m): sample_points[: int(m)]
                                for m in distance_sample_count_values
                            }
                            max_sample_count = int(_state.DISTANCE_SAMPLE_COUNT)
                            for qin_target_value in qin_target_values:
                                qin_key = float(qin_target_value)
                                _state.QIN_TARGET = qin_key
                                q_inlet_cm3_s_analysis = qin_key * 1e-3 / 60.0 * q_scale
                                per_seg_flow_analysis = q_inlet_cm3_s_analysis / (effective_target + 1)
                                terminal_flow_override_analysis = (
                                    per_seg_flow_analysis if _state.SCALE_Q_BY_VOLUME else None
                                )
                                _apply_run_tree_params(tree, side_len, terminal_flow_override_analysis)
                                metrics_by_sample = {
                                    int(m): {} for m in distance_sample_count_values
                                }
                                metrics_by_qin[qin_key] = metrics_by_sample
                                print(f"  Flowrate analysis: qin={qin_key:g} uL/min")
                                for fluid in analysis_fluids:
                                    _set_progress("analyze", fluid=fluid)
                                    _state.ACTIVE_FLUID = fluid
                                    if not solver_logged:
                                        solver_kind = (
                                            "tree"
                                            if str(_state.KIRCHHOFF_SOLVER).strip().lower() in ("tree", "tree_neumann", "tree-current-bc")
                                            else ("sparse" if _state._HAVE_SCIPY_SPARSE else "dense")
                                        )
                                        print(
                                            f"Analysis solver: {solver_kind} Kirchhoff "
                                            f"(bc={_normalize_kirchhoff_bc_mode()}) "
                                            f"concentration={_resolve_concentration_solver(_state.CONCENTRATION_SOLVER)} "
                                            f"finite_radius_o2={_state.FINITE_RADIUS_O2_TERMS} "
                                            f"lumen_wall={_state.LUMEN_WALL_CLOSURE}"
                                        )
                                        if _state.LUMEN_WALL_CLOSURE == "graetz":
                                            print(
                                                f"  Graetz closure: profile={_state.GRAETZ_VELOCITY_PROFILE} "
                                                f"n_radial={_state.GRAETZ_N_RADIAL} n_modes={_state.GRAETZ_N_MODES} "
                                                f"max_fp_iters={_state.GRAETZ_MAX_FP_ITERS} "
                                                f"D_lumen={_lumen_diffusivity_cm2_s_for_fluid(_state.ACTIVE_FLUID):.4g} cm^2/s"
                                            )
                                        solver_logged = True
                                    plot_any = _state.PLOT_FLOW or _state.PLOT_CONC_VESSELS or _state.PLOT_CONC_VESSELS_POINTS or _state.PLOT_VIABILITY_POINTS
                                    max_points = sample_points_by_count[max_sample_count]
                                    t_tissue_cache_start = perf_counter()
                                    tissue_cache = build_tissue_cache_from_tree(tree, max_points)
                                    tissue_cache_build_elapsed = perf_counter() - t_tissue_cache_start
                                    print(
                                        f"  Tissue cache build M={max_sample_count:g}: "
                                        f"{_fmt_seconds(tissue_cache_build_elapsed)}"
                                    )
                                    if _state.CEXT_TRACE_CALLBACK is not None and bool(_state.CEXT_TRACE_TISSUE_ENABLED):
                                        globals()["CEXT_TRACE_TISSUE_POINTS"] = max_points
                                        globals()["CEXT_TRACE_TISSUE_CACHE"] = tissue_cache
                                    print(f"Starting summarize_tree. Fluid: {_state.ACTIVE_FLUID}")
                                    summary = summarize_tree(
                                        tree,
                                        max_points,
                                        effective_target,
                                        side_length=side_len,
                                        fluid=fluid,
                                        inlet_flow_cm3_s=q_inlet_cm3_s_analysis,
                                        tissue_cache=tissue_cache,
                                        return_details=True,
                                    )
                                    print(f"Ending summarize_tree. Fluid: {_state.ACTIVE_FLUID}")
                                    base_metrics, details = summary
                                    base_core_assembly_s = max(
                                        float(base_metrics.get("t_assembly_s", 0.0))
                                        - float(base_metrics.get("t_tissue_geometry_s", 0.0) or 0.0),
                                        0.0,
                                    )
                                    base_metrics["t_load_s"] = float(tree_build_elapsed)
                                    base_metrics["t_assembly_s"] = (
                                        base_core_assembly_s
                                        + float(tissue_cache_build_elapsed)
                                        + float(base_metrics.get("t_tissue_geometry_s", 0.0) or 0.0)
                                    )
                                    metrics_by_sample[max_sample_count][fluid] = base_metrics
                                    if not (_state.CEXT_TRACE_CALLBACK is not None and bool(_state.CEXT_TRACE_TISSUE_ENABLED)):
                                        del tissue_cache
                                    if plot_any:
                                        domain_obj = getattr(tree, "domain", None)
                                        if domain_obj is None:
                                            raise RuntimeError("Tree has no domain; cannot plot.")
                                        if _state.PLOT_FLOW:
                                            _plot_flow(
                                                domain_obj,
                                                details["starts"],
                                                details["ends"],
                                                details["radii"],
                                                details["flows"],
                                            )
                                        if _state.PLOT_CONC_VESSELS:
                                            _plot_concentration(
                                                domain_obj,
                                                details["starts"],
                                                details["ends"],
                                                details["radii"],
                                                details["cin"],
                                                details["cout"],
                                                details["tissue_points"],
                                                details["tissue_values"],
                                                show_points=False,
                                                inlet_concentration=details["inlet_concentration"],
                                            )
                                        if _state.PLOT_CONC_VESSELS_POINTS:
                                            _plot_concentration(
                                                domain_obj,
                                                details["starts"],
                                                details["ends"],
                                                details["radii"],
                                                details["cin"],
                                                details["cout"],
                                                details["tissue_points"],
                                                details["tissue_values"],
                                                show_points=True,
                                                inlet_concentration=details["inlet_concentration"],
                                            )
                                        if _state.PLOT_VIABILITY_POINTS:
                                            _plot_viability_points(
                                                domain_obj,
                                                details["starts"],
                                                details["ends"],
                                                details["radii"],
                                                details["cin"],
                                                details["cout"],
                                                details["tissue_points"],
                                                details["tissue_values"],
                                                inlet_concentration=details["inlet_concentration"],
                                            )
                                    for sample_count in distance_sample_count_values:
                                        sample_count = int(sample_count)
                                        if sample_count == max_sample_count:
                                            continue
                                        points_m = sample_points_by_count[sample_count]
                                        t_tissue_cache_start = perf_counter()
                                        tissue_cache_m = build_tissue_cache_from_tree(tree, points_m)
                                        tissue_cache_build_elapsed_m = perf_counter() - t_tissue_cache_start
                                        print(
                                            f"  Tissue cache build M={sample_count:g}: "
                                            f"{_fmt_seconds(tissue_cache_build_elapsed_m)}"
                                        )
                                        metrics_by_sample[sample_count][fluid] = summarize_tissue_only_from_details(
                                            base_metrics,
                                            details,
                                            points_m,
                                            tissue_cache=tissue_cache_m,
                                            tissue_cache_build_elapsed=tissue_cache_build_elapsed_m,
                                            base_core_assembly_s=base_core_assembly_s,
                                        )
                                        del tissue_cache_m
                        finally:
                            if not _state.BUILD_ON_PREVIOUS:
                                del tree
                        for qin_target_value in qin_target_values:
                            qin_key = float(qin_target_value)
                            metrics_by_sample = metrics_by_qin.get(qin_key, {})
                            for sample_count in distance_sample_count_values:
                                sample_count = int(sample_count)
                                metrics = metrics_by_sample.get(sample_count, {})
                                for fluid in analysis_fluids:
                                    if metrics.get(fluid) is not None:
                                        qin_trial_rows[qin_key][sample_count][fluid].append(metrics[fluid])
                                        _dbg(
                                            f"trial {trial_idx} qin={qin_key:g} M={sample_count:g} ({fluid}): "
                                            f"metrics keys={list(metrics[fluid].keys())}"
                                        )
                                        print(
                                            f"  trial {trial_idx} qin={qin_key:g} M={sample_count:g} ({fluid}): "
                                            f"segs={metrics[fluid]['total_segments']} "
                                            f"dRnet={metrics[fluid]['dRnet']:.4e} "
                                            f"C_LQ={metrics[fluid]['C_LQ_over_Cmax']:.4f} "
                                            f"C_tiss={metrics[fluid]['C_tiss_over_Cmax']:.4f}"
                                        )
                                        print(
                                            f"    timings: load={_fmt_seconds(metrics[fluid].get('t_load_s'))} "
                                            f"assembly={_fmt_seconds(metrics[fluid].get('t_assembly_s'))} "
                                            f"kirchhoff={_fmt_seconds(metrics[fluid].get('t_kirchhoff_s'))} "
                                            f"conc={_fmt_seconds(metrics[fluid].get('t_concentration_s'))} "
                                            f"tissue_greens={_fmt_seconds(metrics[fluid].get('t_tissue_s'))}"
                                        )
                                        if str(metrics[fluid].get("concentration_solver", "")) in {
                                            "network_ext",
                                            "topdown_ext",
                                            "topdown_ext_hybrid_bg",
                                            "network_ext_hybrid_bg",
                                            "topdown_ext_treecode",
                                        }:
                                            print(
                                                f"    cext timing ({metrics[fluid].get('concentration_solver')} / "
                                                f"{metrics[fluid].get('t_cext_backend', metrics[fluid].get('concentration_solver'))}): "
                                                f"total={_fmt_seconds(metrics[fluid].get('t_cext_total_s'))} "
                                                f"iters={int(metrics[fluid].get('cext_outer_iterations_completed', 0) or 0)} "
                                                f"delta={float(metrics[fluid].get('cext_max_delta_last', 0.0) or 0.0):.3e} "
                                                f"rel={float(metrics[fluid].get('cext_rel_residual_last', 0.0) or 0.0):.3e}"
                                            )
                                        print(
                                            f"    tissue timing ({metrics[fluid].get('t_tissue_backend', 'unknown')}): "
                                            f"geometry/refine/cache={_fmt_seconds(metrics[fluid].get('t_tissue_geometry_s'))} "
                                            f"oxygen_greens={_fmt_seconds(metrics[fluid].get('t_tissue_oxygen_s'))} "
                                            f"total={_fmt_seconds(metrics[fluid].get('t_tissue_total_s'))}"
                                        )
                                    else:
                                        print(
                                            f"  trial {trial_idx} qin={qin_key:g} M={sample_count:g} ({fluid}): "
                                            "FAILED (metrics None)"
                                        )
                    dnc_mu = float("nan")
                    dnc_sigma = float("nan")
                    if need_dnc_fit and dnc_mu_trials and dnc_sigma_trials:
                        dnc_mu = float(np.nanmean(np.asarray(dnc_mu_trials, dtype=float)))
                        dnc_sigma = float(np.nanmean(np.asarray(dnc_sigma_trials, dtype=float)))
                    if _state.PLOT_HISTOGRAM and need_dnc_fit:
                        dnc_history["targets"].append(int(effective_target))
                        dnc_history["mu_sigma"].append((dnc_mu, dnc_sigma))
                    if _state.VIOLIN_DNC:
                        col_idx = list(run["target_counts"]).index(target)
                        if dnc_violin_trials:
                            values = np.nanmean(np.vstack(dnc_violin_trials), axis=0)
                        else:
                            values = np.full((int(sample_points.shape[0]),), np.nan, dtype=float)
                        min_keep = float(_state.VIOLIN_MIN_KEEP_UM)
                        if np.isfinite(min_keep):
                            values = np.where(values <= min_keep, np.nan, values)
                        keep = values[np.isfinite(values)]
                        if keep.size:
                            keep = np.sort(keep)
                        sorted_values = np.full_like(values, np.nan, dtype=float)
                        sorted_values[: keep.size] = keep
                        _update_violin_points_csv(
                            violin_path,
                            target_counts=list(run["target_counts"]),
                            col_idx=col_idx,
                            values_um=sorted_values,
                        )
                    if _state.BUILD_ON_PREVIOUS:
                        previous_tree = tree
                        previous_target = effective_target
                    any_rows = False
                    for qin_target_value in qin_target_values:
                        qin_key = float(qin_target_value)
                        trial_rows_by_sample = qin_trial_rows[qin_key]
                        for sample_count in distance_sample_count_values:
                            sample_count = int(sample_count)
                            trial_rows = trial_rows_by_sample[sample_count]
                            for fluid in analysis_fluids:
                                if not trial_rows[fluid]:
                                    _dbg(
                                        f"No trial rows collected for qin={qin_key:g} "
                                        f"M={sample_count:g} {fluid}; skipping aggregation."
                                    )
                                    continue
                                any_rows = True
                                aggregated = aggregate_trials(trial_rows[fluid])
                                aggregated["fluid"] = fluid
                                aggregated.update(_pi_phi_gamma_columns(aggregated))
                                if _state.SAVE_DNC_GAUSSIAN_FITS:
                                    aggregated["dnc_gaussian_mu_um"] = dnc_mu
                                    aggregated["dnc_gaussian_sigma_um"] = dnc_sigma
                                else:
                                    aggregated["dnc_gaussian_mu_um"] = float("nan")
                                    aggregated["dnc_gaussian_sigma_um"] = float("nan")
                                _dbg(
                                    f"Aggregated keys qin={qin_key:g} M={sample_count:g} "
                                    f"({fluid})={list(aggregated.keys())}"
                                )
                                append_row(output_path, aggregated)
                                if _state.NONDIMENSIONAL_NUMBERS and nondim_output_path is not None:
                                    append_nondimensional_row(
                                        nondim_output_path,
                                        _nondimensional_numbers_row(aggregated, run_name=str(run["name"])),
                                    )
                                print(
                                    f"  -> averages qin={qin_key:g} M={sample_count:g} ({fluid}): "
                                    f"vol={aggregated['total_volume_mean']:.4e}+/-{aggregated['total_volume_std']:.1e} "
                                    f"Qmin/Qin={aggregated['Qmin_over_Qinlet_mean']:.4f}+/-{aggregated['Qmin_over_Qinlet_std']:.2e} "
                                    f"C_LQ={aggregated['C_LQ_over_Cmax_mean']:.4f}+/-{aggregated['C_LQ_over_Cmax_std']:.2e} "
                                    f"C_tiss={aggregated['C_tiss_over_Cmax_mean']:.4f}+/-{aggregated['C_tiss_over_Cmax_std']:.2e}"
                                )
                    if not any_rows:
                        _dbg("No trial rows collected; skipping aggregation.")
                    _set_progress("target_done", trial=None, fluid=None)
                if _state.PLOT_HISTOGRAM:
                    mu_sigma = dnc_history.get("mu_sigma") or []
                    targets = dnc_history.get("targets") or []
                    if mu_sigma and targets:
                        _plot_dnc_gaussians(
                            mu_sigma=mu_sigma,
                            target_terminals=targets,
                            title=f"DNC Gaussian fits (geometry) | run={run['name']} | side={side_len} | theta={min_theta}",
                        )

    print(f"\nSaved metrics to: {output_path}")
    if _state.NONDIMENSIONAL_NUMBERS and nondim_output_path is not None:
        print(f"Saved nondimensional metrics to: {nondim_output_path}")


def _run_main_with_profile(profile_out: str) -> None:
    profile_path = resolve_output_path(profile_out)
    profile_path.parent.mkdir(parents=True, exist_ok=True)
    profiler = cProfile.Profile()
    profiler.enable()
    try:
        main()
    finally:
        profiler.disable()
        profiler.dump_stats(profile_path)
        stats = pstats.Stats(profiler).sort_stats('cumtime')
        print(f"Profile written to: {profile_path}")
        stats.print_stats(40)


def _run_main_with_line_profile(profile_out: str) -> None:
    profile_path = resolve_output_path(profile_out) if profile_out else None
    if profile_path is not None:
        profile_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        import line_profiler  # type: ignore
    except Exception:
        print("line_profiler not installed; install with `pip install line_profiler` or use `kernprof`.")
        main()
        return

    profiler = line_profiler.LineProfiler()

    def _maybe_add(name: str) -> None:
        fn = globals().get(name)
        if callable(fn):
            profiler.add_function(fn)

    for fn_name in (
        "compute_tissue_samples_greens",
        "solve_tree_greens",
        "compute_concentration_profiles",
        "solve_network_concentrations",
        "_solve_channel_concentrations",
        "solve_kirchhoff",
        "build_tissue_cache_from_tree",
    ):
        _maybe_add(fn_name)

    profiler.enable_by_count()
    try:
        main()
    finally:
        profiler.disable_by_count()
        if profile_path is not None:
            with profile_path.open("w", encoding="ascii") as handle:
                profiler.print_stats(stream=handle)
            print(f"Line profile written to: {profile_path}")
        else:
            profiler.print_stats()


if __name__ == "__main__":
    try:
        _state.args = parse_args()
        if str(getattr(_state.args, 'line_profile', 'false')).lower() == 'true':
            _run_main_with_line_profile(getattr(_state.args, 'line_profile_out', 'cascade_line_profile.txt'))
        elif str(getattr(_state.args, 'profile', 'false')).lower() == 'true':
            _run_main_with_profile(getattr(_state.args, 'profile_out', 'cascade_profile.prof'))
        else:
            main()
    except SystemExit as exc:
        _state.code = exc.code if isinstance(exc.code, int) else 0
        if _state.code == 0:
            raise
        print("\nFATAL ERROR: unhandled exception in CASCADE.")
        print(f"Last progress: {_progress_snapshot()}")
        _write_crash_log(exc)
        traceback.print_exc()
        raise
    except BaseException as exc:
        print("\nFATAL ERROR: unhandled exception in CASCADE.")
        print(f"Last progress: {_progress_snapshot()}")
        _write_crash_log(exc)
        traceback.print_exc()
        raise


__all__ = ['main', '_run_main_with_profile', '_run_main_with_line_profile']
